<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>5 Importing Data in R | Data Analysis for Economic Research</title>
  <meta name="description" content="5 Importing Data in R | Data Analysis for Economic Research" />
  <meta name="generator" content="bookdown 0.34 and GitBook 2.6.7" />

  <meta property="og:title" content="5 Importing Data in R | Data Analysis for Economic Research" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="5 Importing Data in R | Data Analysis for Economic Research" />
  
  
  



<meta name="date" content="2023-07-04" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="r-data-types-and-structures.html"/>
<link rel="next" href="downloading-data-in-r.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="index.html">Data Analysis for Economic Research</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html"><i class="fa fa-check"></i><em>Preface</em></a>
<ul>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html#introduction"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html#author"><i class="fa fa-check"></i>Author</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="module-i-introduction-to-r-for-economic-research.html"><a href="module-i-introduction-to-r-for-economic-research.html"><i class="fa fa-check"></i><em>Module I: Introduction to R for Economic Research</em></a></li>
<li class="chapter" data-level="1" data-path="software-overview.html"><a href="software-overview.html"><i class="fa fa-check"></i><b>1</b> Software Overview</a></li>
<li class="chapter" data-level="2" data-path="software-installation.html"><a href="software-installation.html"><i class="fa fa-check"></i><b>2</b> Software Installation</a>
<ul>
<li class="chapter" data-level="2.1" data-path="software-installation.html"><a href="software-installation.html#install-r"><i class="fa fa-check"></i><b>2.1</b> Install R</a></li>
<li class="chapter" data-level="2.2" data-path="software-installation.html"><a href="software-installation.html#install-rstudio"><i class="fa fa-check"></i><b>2.2</b> Install RStudio</a></li>
<li class="chapter" data-level="2.3" data-path="software-installation.html"><a href="software-installation.html#install-r-markdown"><i class="fa fa-check"></i><b>2.3</b> Install R Markdown</a></li>
<li class="chapter" data-level="2.4" data-path="software-installation.html"><a href="software-installation.html#install-latex"><i class="fa fa-check"></i><b>2.4</b> Install LaTeX</a></li>
<li class="chapter" data-level="2.5" data-path="software-installation.html"><a href="software-installation.html#install-r-packages"><i class="fa fa-check"></i><b>2.5</b> Install R Packages</a></li>
<li class="chapter" data-level="2.6" data-path="software-installation.html"><a href="software-installation.html#step-test"><i class="fa fa-check"></i><b>2.6</b> 18-Step Test</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="rstudio-interface.html"><a href="rstudio-interface.html"><i class="fa fa-check"></i><b>3</b> RStudio Interface</a>
<ul>
<li class="chapter" data-level="3.1" data-path="rstudio-interface.html"><a href="rstudio-interface.html#rstudio-sections"><i class="fa fa-check"></i><b>3.1</b> RStudio Sections</a></li>
<li class="chapter" data-level="3.2" data-path="rstudio-interface.html"><a href="rstudio-interface.html#r-scripts"><i class="fa fa-check"></i><b>3.2</b> R Scripts</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="r-data-types-and-structures.html"><a href="r-data-types-and-structures.html"><i class="fa fa-check"></i><b>4</b> R Data Types and Structures</a>
<ul>
<li class="chapter" data-level="4.1" data-path="r-data-types-and-structures.html"><a href="r-data-types-and-structures.html#scalar"><i class="fa fa-check"></i><b>4.1</b> Scalar</a></li>
<li class="chapter" data-level="4.2" data-path="r-data-types-and-structures.html"><a href="r-data-types-and-structures.html#vector"><i class="fa fa-check"></i><b>4.2</b> Vector</a></li>
<li class="chapter" data-level="4.3" data-path="r-data-types-and-structures.html"><a href="r-data-types-and-structures.html#matrix-matrix"><i class="fa fa-check"></i><b>4.3</b> Matrix (<code>matrix</code>)</a></li>
<li class="chapter" data-level="4.4" data-path="r-data-types-and-structures.html"><a href="r-data-types-and-structures.html#list-list"><i class="fa fa-check"></i><b>4.4</b> List (<code>list</code>)</a></li>
<li class="chapter" data-level="4.5" data-path="r-data-types-and-structures.html"><a href="r-data-types-and-structures.html#data-frame-data.frame"><i class="fa fa-check"></i><b>4.5</b> Data Frame (<code>data.frame</code>)</a></li>
<li class="chapter" data-level="4.6" data-path="r-data-types-and-structures.html"><a href="r-data-types-and-structures.html#tibble"><i class="fa fa-check"></i><b>4.6</b> Tibble (<code>tbl_df</code>)</a></li>
<li class="chapter" data-level="4.7" data-path="r-data-types-and-structures.html"><a href="r-data-types-and-structures.html#data-table-data.table"><i class="fa fa-check"></i><b>4.7</b> Data Table (<code>data.table</code>)</a></li>
<li class="chapter" data-level="4.8" data-path="r-data-types-and-structures.html"><a href="r-data-types-and-structures.html#xts"><i class="fa fa-check"></i><b>4.8</b> Extensible Time Series (<code>xts</code>)</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="importing-data-in-r.html"><a href="importing-data-in-r.html"><i class="fa fa-check"></i><b>5</b> Importing Data in R</a>
<ul>
<li class="chapter" data-level="5.1" data-path="importing-data-in-r.html"><a href="importing-data-in-r.html#working-directory"><i class="fa fa-check"></i><b>5.1</b> Working Directory</a></li>
<li class="chapter" data-level="5.2" data-path="importing-data-in-r.html"><a href="importing-data-in-r.html#yield-curve"><i class="fa fa-check"></i><b>5.2</b> Yield Curve</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="importing-data-in-r.html"><a href="importing-data-in-r.html#import-csv-file"><i class="fa fa-check"></i><b>5.2.1</b> Import CSV File</a></li>
<li class="chapter" data-level="5.2.2" data-path="importing-data-in-r.html"><a href="importing-data-in-r.html#plotting-historical-yields"><i class="fa fa-check"></i><b>5.2.2</b> Plotting Historical Yields</a></li>
<li class="chapter" data-level="5.2.3" data-path="importing-data-in-r.html"><a href="importing-data-in-r.html#plotting-yield-curve"><i class="fa fa-check"></i><b>5.2.3</b> Plotting Yield Curve</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="importing-data-in-r.html"><a href="importing-data-in-r.html#michigan-survey"><i class="fa fa-check"></i><b>5.3</b> Michigan Survey</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="importing-data-in-r.html"><a href="importing-data-in-r.html#import-tsv-file"><i class="fa fa-check"></i><b>5.3.1</b> Import TSV File</a></li>
<li class="chapter" data-level="5.3.2" data-path="importing-data-in-r.html"><a href="importing-data-in-r.html#plotting-consumer-indices"><i class="fa fa-check"></i><b>5.3.2</b> Plotting Consumer Indices</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="importing-data-in-r.html"><a href="importing-data-in-r.html#tealbook"><i class="fa fa-check"></i><b>5.4</b> Tealbook</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="importing-data-in-r.html"><a href="importing-data-in-r.html#import-excel-workbook"><i class="fa fa-check"></i><b>5.4.1</b> Import Excel Workbook</a></li>
<li class="chapter" data-level="5.4.2" data-path="importing-data-in-r.html"><a href="importing-data-in-r.html#nowcast-and-backcast"><i class="fa fa-check"></i><b>5.4.2</b> Nowcast and Backcast</a></li>
<li class="chapter" data-level="5.4.3" data-path="importing-data-in-r.html"><a href="importing-data-in-r.html#information-date-and-realization-date"><i class="fa fa-check"></i><b>5.4.3</b> Information Date and Realization Date</a></li>
<li class="chapter" data-level="5.4.4" data-path="importing-data-in-r.html"><a href="importing-data-in-r.html#plotting-forecasts"><i class="fa fa-check"></i><b>5.4.4</b> Plotting Forecasts</a></li>
<li class="chapter" data-level="5.4.5" data-path="importing-data-in-r.html"><a href="importing-data-in-r.html#plotting-forecast-errors"><i class="fa fa-check"></i><b>5.4.5</b> Plotting Forecast Errors</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="downloading-data-in-r.html"><a href="downloading-data-in-r.html"><i class="fa fa-check"></i><b>6</b> Downloading Data in R</a>
<ul>
<li class="chapter" data-level="6.1" data-path="downloading-data-in-r.html"><a href="downloading-data-in-r.html#web-api"><i class="fa fa-check"></i><b>6.1</b> Web API</a></li>
<li class="chapter" data-level="6.2" data-path="downloading-data-in-r.html"><a href="downloading-data-in-r.html#using-getsymbols"><i class="fa fa-check"></i><b>6.2</b> Using <code>getSymbols()</code></a></li>
<li class="chapter" data-level="6.3" data-path="downloading-data-in-r.html"><a href="downloading-data-in-r.html#using-quandl"><i class="fa fa-check"></i><b>6.3</b> Using <code>Quandl()</code></a></li>
<li class="chapter" data-level="6.4" data-path="downloading-data-in-r.html"><a href="downloading-data-in-r.html#saving-data"><i class="fa fa-check"></i><b>6.4</b> Saving Data</a></li>
<li class="chapter" data-level="6.5" data-path="downloading-data-in-r.html"><a href="downloading-data-in-r.html#summary-and-resources"><i class="fa fa-check"></i><b>6.5</b> Summary and Resources</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="writing-reports-with-r-markdown.html"><a href="writing-reports-with-r-markdown.html"><i class="fa fa-check"></i><b>7</b> Writing Reports with R Markdown</a>
<ul>
<li class="chapter" data-level="7.1" data-path="writing-reports-with-r-markdown.html"><a href="writing-reports-with-r-markdown.html#creating-an-r-markdown-document"><i class="fa fa-check"></i><b>7.1</b> Creating an R Markdown Document</a></li>
<li class="chapter" data-level="7.2" data-path="writing-reports-with-r-markdown.html"><a href="writing-reports-with-r-markdown.html#yaml-header"><i class="fa fa-check"></i><b>7.2</b> YAML Header</a></li>
<li class="chapter" data-level="7.3" data-path="writing-reports-with-r-markdown.html"><a href="writing-reports-with-r-markdown.html#markdown-syntax"><i class="fa fa-check"></i><b>7.3</b> Markdown Syntax</a></li>
<li class="chapter" data-level="7.4" data-path="writing-reports-with-r-markdown.html"><a href="writing-reports-with-r-markdown.html#r-chunks"><i class="fa fa-check"></i><b>7.4</b> R Chunks</a></li>
<li class="chapter" data-level="7.5" data-path="writing-reports-with-r-markdown.html"><a href="writing-reports-with-r-markdown.html#embedding-r-variables-into-text"><i class="fa fa-check"></i><b>7.5</b> Embedding R Variables into Text</a></li>
<li class="chapter" data-level="7.6" data-path="writing-reports-with-r-markdown.html"><a href="writing-reports-with-r-markdown.html#latex-syntax-for-math"><i class="fa fa-check"></i><b>7.6</b> LaTeX Syntax for Math</a></li>
<li class="chapter" data-level="7.7" data-path="writing-reports-with-r-markdown.html"><a href="writing-reports-with-r-markdown.html#printing-tables"><i class="fa fa-check"></i><b>7.7</b> Printing Tables</a></li>
<li class="chapter" data-level="7.8" data-path="writing-reports-with-r-markdown.html"><a href="writing-reports-with-r-markdown.html#summary-and-resources-1"><i class="fa fa-check"></i><b>7.8</b> Summary and Resources</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="learning-r-with-datacamp.html"><a href="learning-r-with-datacamp.html"><i class="fa fa-check"></i><b>8</b> Learning R with DataCamp</a>
<ul>
<li class="chapter" data-level="8.1" data-path="learning-r-with-datacamp.html"><a href="learning-r-with-datacamp.html#preparing-for-the-course"><i class="fa fa-check"></i><b>8.1</b> Preparing for the Course</a></li>
<li class="chapter" data-level="8.2" data-path="learning-r-with-datacamp.html"><a href="learning-r-with-datacamp.html#xp-system-and-course-completion"><i class="fa fa-check"></i><b>8.2</b> XP System and Course Completion</a></li>
<li class="chapter" data-level="8.3" data-path="learning-r-with-datacamp.html"><a href="learning-r-with-datacamp.html#developing-your-skills"><i class="fa fa-check"></i><b>8.3</b> Developing Your Skills</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="data-report-on-yield-curve.html"><a href="data-report-on-yield-curve.html"><i class="fa fa-check"></i><b>9</b> Data Report on Yield Curve</a>
<ul>
<li class="chapter" data-level="9.1" data-path="data-report-on-yield-curve.html"><a href="data-report-on-yield-curve.html#preparations"><i class="fa fa-check"></i><b>9.1</b> Preparations</a></li>
<li class="chapter" data-level="9.2" data-path="data-report-on-yield-curve.html"><a href="data-report-on-yield-curve.html#data-guidelines"><i class="fa fa-check"></i><b>9.2</b> Data Guidelines</a></li>
<li class="chapter" data-level="9.3" data-path="data-report-on-yield-curve.html"><a href="data-report-on-yield-curve.html#r-markdown-guidelines"><i class="fa fa-check"></i><b>9.3</b> R Markdown Guidelines</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="module-ii-traditional-economic-indicators.html"><a href="module-ii-traditional-economic-indicators.html"><i class="fa fa-check"></i><em>Module II: Traditional Economic Indicators</em></a></li>
<li class="chapter" data-level="10" data-path="economic-performance-indicators.html"><a href="economic-performance-indicators.html"><i class="fa fa-check"></i><b>10</b> Economic Performance Indicators</a></li>
<li class="chapter" data-level="11" data-path="time-series-comparison-of-economic-indicators.html"><a href="time-series-comparison-of-economic-indicators.html"><i class="fa fa-check"></i><b>11</b> Time-Series Comparison of Economic Indicators</a></li>
<li class="chapter" data-level="12" data-path="cross-sectional-comparison-of-economic-indicators.html"><a href="cross-sectional-comparison-of-economic-indicators.html"><i class="fa fa-check"></i><b>12</b> Cross-Sectional Comparison of Economic Indicators</a></li>
<li class="chapter" data-level="13" data-path="data-report-on-traditional-economic-indicators.html"><a href="data-report-on-traditional-economic-indicators.html"><i class="fa fa-check"></i><b>13</b> Data Report on Traditional Economic Indicators</a>
<ul>
<li class="chapter" data-level="13.1" data-path="data-report-on-traditional-economic-indicators.html"><a href="data-report-on-traditional-economic-indicators.html#preparations-2"><i class="fa fa-check"></i><b>13.1</b> Preparations</a></li>
<li class="chapter" data-level="13.2" data-path="data-report-on-traditional-economic-indicators.html"><a href="data-report-on-traditional-economic-indicators.html#data-guidelines-2"><i class="fa fa-check"></i><b>13.2</b> Data Guidelines</a></li>
<li class="chapter" data-level="13.3" data-path="data-report-on-traditional-economic-indicators.html"><a href="data-report-on-traditional-economic-indicators.html#r-markdown-guidelines-2"><i class="fa fa-check"></i><b>13.3</b> R Markdown Guidelines</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="module-iii-survey--and-text-based-economic-indicators.html"><a href="module-iii-survey--and-text-based-economic-indicators.html"><i class="fa fa-check"></i><em>Module III: Survey- and Text-Based Economic Indicators</em></a></li>
<li class="chapter" data-level="14" data-path="why-subjective-information-matters.html"><a href="why-subjective-information-matters.html"><i class="fa fa-check"></i><b>14</b> Why Subjective Information Matters</a></li>
<li class="chapter" data-level="15" data-path="michigan-consumer-survey.html"><a href="michigan-consumer-survey.html"><i class="fa fa-check"></i><b>15</b> Michigan Consumer Survey</a></li>
<li class="chapter" data-level="16" data-path="real-time-and-forecaster-data.html"><a href="real-time-and-forecaster-data.html"><i class="fa fa-check"></i><b>16</b> Real-Time and Forecaster Data</a></li>
<li class="chapter" data-level="17" data-path="text-based-economic-indicators.html"><a href="text-based-economic-indicators.html"><i class="fa fa-check"></i><b>17</b> Text-Based Economic Indicators</a></li>
<li class="chapter" data-level="18" data-path="data-report-on-survey--and-text-based-economic-indicators.html"><a href="data-report-on-survey--and-text-based-economic-indicators.html"><i class="fa fa-check"></i><b>18</b> Data Report on Survey- and Text-Based Economic Indicators</a>
<ul>
<li class="chapter" data-level="18.1" data-path="data-report-on-survey--and-text-based-economic-indicators.html"><a href="data-report-on-survey--and-text-based-economic-indicators.html#preparations-3"><i class="fa fa-check"></i><b>18.1</b> Preparations</a></li>
<li class="chapter" data-level="18.2" data-path="data-report-on-survey--and-text-based-economic-indicators.html"><a href="data-report-on-survey--and-text-based-economic-indicators.html#data-guidelines-3"><i class="fa fa-check"></i><b>18.2</b> Data Guidelines</a></li>
<li class="chapter" data-level="18.3" data-path="data-report-on-survey--and-text-based-economic-indicators.html"><a href="data-report-on-survey--and-text-based-economic-indicators.html#r-markdown-guidelines-3"><i class="fa fa-check"></i><b>18.3</b> R Markdown Guidelines</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://www.julianfludwig.com/" target="blank">Julian F. Ludwig</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data Analysis for Economic Research</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="importing-data-in-r" class="section level1 hasAnchor" number="5">
<h1><span class="header-section-number">5</span> Importing Data in R<a href="importing-data-in-r.html#importing-data-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>R is a software specialized for data analysis. To analyze data using R, the data must first be imported into the R environment. R offers robust functionality for importing data in a variety of formats. This chapter explores how to import data from CSV, TSV, and Excel files. Before we dive into specifics, let’s ensure RStudio can locate the data stored on your computer.</p>
<div id="working-directory" class="section level2 hasAnchor" number="5.1">
<h2><span class="header-section-number">5.1</span> Working Directory<a href="importing-data-in-r.html#working-directory" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The working directory in R is the folder where R starts when it’s looking for files to read or write. If you’re not sure where your current working directory is, you can use the <code>getwd()</code> (get working directory) command in R to find out:</p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="importing-data-in-r.html#cb139-1" tabindex="-1"></a><span class="fu">getwd</span>()</span></code></pre></div>
<pre><code>## [1] &quot;/Users/julianludwig/Library/CloudStorage/Dropbox/Economics/teaching/4300_2023/daer&quot;</code></pre>
<p>To change your working directory, use the <code>setwd()</code> (set working directory) function:</p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="importing-data-in-r.html#cb141-1" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">&quot;your/folder/path&quot;</span>)</span></code></pre></div>
<p>Be sure to replace <code>"your/folder/path"</code> with the actual path to your folder.</p>
<p>When your files are stored in the same directory as your working directory, defined using the <code>setwd()</code> function, you can directly access these files by their names. For instance, <code>read_csv("yieldcurve.csv")</code> will successfully read the file if “yieldcurve.csv” is in the working directory. If the file is located in a subfolder within the working directory, for example a folder named <code>files</code>, you would need to specify the folder in the file path when calling the file: <code>read_csv("files/yieldcurve.csv")</code>.</p>
<p>To find out the folder path for a specific file or folder on your computer, you can follow these steps:</p>
<div id="for-windows-1" class="section level4 unnumbered hasAnchor">
<h4>For Windows:<a href="importing-data-in-r.html#for-windows-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ol style="list-style-type: decimal">
<li>Navigate to the folder using the File Explorer.</li>
<li>Once you are in the folder, click on the address bar at the top of the File Explorer window. The address bar will now show the full path to the folder. This is the path you can set in R using the <code>setwd()</code> function.</li>
</ol>
<p>An example of a folder path on Windows might look like this: <code>C:/Users/YourName/Documents/R</code>.</p>
</div>
<div id="for-macos-1" class="section level4 unnumbered hasAnchor">
<h4>For MacOS:<a href="importing-data-in-r.html#for-macos-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ol style="list-style-type: decimal">
<li>Open Finder and navigate to the folder.</li>
<li>Once you are in the folder, Command-click (or right-click and hold, if you have a mouse) on the folder’s name at the top of the Finder window. A drop-down menu will appear showing the folder hierarchy.</li>
<li>Hover over each folder in the hierarchy to show the full path, then copy this path.</li>
</ol>
<p>An example of a folder path on macOS might look like this: <code>/Users/YourName/Documents/R</code>.</p>
<p>Remember, when setting the working directory in R, you need to use forward slashes (<code>/</code>) in the folder path, even on Windows where the convention is to use backslashes (<code>\</code>).</p>
</div>
</div>
<div id="yield-curve" class="section level2 hasAnchor" number="5.2">
<h2><span class="header-section-number">5.2</span> Yield Curve<a href="importing-data-in-r.html#yield-curve" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In this chapter, we’ll demonstrate how to import a CSV file using real-world Treasury yield curve rates data.</p>
<p>To obtain the yield curve data, follow these steps:</p>
<ol style="list-style-type: decimal">
<li>Visit the U.S. Treasury’s data center by clicking <a href="https://www.treasury.gov/resource-center/data-chart-center">here</a>.</li>
<li>Click on “Data” in the menu bar, then select “Daily Treasury Par Yield Curve Rates.”</li>
<li>On the data page, select “Download CSV” to obtain the yield curve data for the current year.</li>
<li>To access all the yield curve data since 1990, choose “All” under the “Select Time Period” option, and click “Apply.” Please note that when selecting all periods, the “Download CSV” button may not be available.</li>
<li>To manually save the data as a CSV file, you can copy the data by selecting it and using the Ctrl+C (or Cmd+C) command. Open an Excel file, and use the Ctrl+V (or Cmd+V) command to paste the data into the Excel file.</li>
<li>Save the Excel file as a CSV file named ‘yieldcurve.csv’ in a location of your choice, ensuring that it is saved in a familiar folder for easy access.</li>
</ol>
<div id="import-csv-file" class="section level3 hasAnchor" number="5.2.1">
<h3><span class="header-section-number">5.2.1</span> Import CSV File<a href="importing-data-in-r.html#import-csv-file" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>CSV (Comma Separated Values) is a common file format used to store tabular data. As the name suggests, the values in each row of a CSV file are separated by commas. Here’s an example of how data is stored in a CSV file:</p>
<ul>
<li>Male,8,100,3</li>
<li>Female,9,20,3</li>
</ul>
<p>To import the ‘yieldcurve.csv’ CSV file in R, install and load the <code>readr</code> package. Run <code>install.packages("readr")</code> in the console and include the package at the top of your R script. You can then use the <code>read_csv()</code> or <code>read_delim()</code> function to import the yield curve data:</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="importing-data-in-r.html#cb142-1" tabindex="-1"></a><span class="co"># Load the package</span></span>
<span id="cb142-2"><a href="importing-data-in-r.html#cb142-2" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;readr&quot;</span>)</span>
<span id="cb142-3"><a href="importing-data-in-r.html#cb142-3" tabindex="-1"></a></span>
<span id="cb142-4"><a href="importing-data-in-r.html#cb142-4" tabindex="-1"></a><span class="co"># Import CSV file</span></span>
<span id="cb142-5"><a href="importing-data-in-r.html#cb142-5" tabindex="-1"></a>yc <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="at">file =</span> <span class="st">&quot;files/yieldcurve.csv&quot;</span>, <span class="at">col_names =</span> <span class="cn">TRUE</span>)</span>
<span id="cb142-6"><a href="importing-data-in-r.html#cb142-6" tabindex="-1"></a></span>
<span id="cb142-7"><a href="importing-data-in-r.html#cb142-7" tabindex="-1"></a><span class="co"># Import CSV file using the read_delim() function</span></span>
<span id="cb142-8"><a href="importing-data-in-r.html#cb142-8" tabindex="-1"></a>yc <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(<span class="at">file =</span> <span class="st">&quot;files/yieldcurve.csv&quot;</span>, <span class="at">col_names =</span> <span class="cn">TRUE</span>, <span class="at">delim =</span> <span class="st">&quot;,&quot;</span>)</span></code></pre></div>
<p>In the code snippets above, the <code>read_csv()</code> and <code>read_delim()</code> functions from the <code>readr</code> package are used to import a CSV file named “yieldcurve.csv”. The <code>col_names = TRUE</code> argument indicates that the first row of the CSV file contains column names. The <code>delim = ","</code> argument specifies that the columns are separated by commas, which is the standard delimiter for CSV (<em>Comma</em> Separated Values) files. Either one of the two functions can be used to read the CSV file and store the data in the variable <code>yc</code> for further analysis.</p>
<p>To inspect the first few rows of the data, print the <code>yc</code> object in the console. For an overview of the entire dataset, use the <code>View()</code> function, which provides an interface similar to viewing the CSV file in Microsoft Excel:</p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="importing-data-in-r.html#cb143-1" tabindex="-1"></a><span class="co"># Display the data</span></span>
<span id="cb143-2"><a href="importing-data-in-r.html#cb143-2" tabindex="-1"></a>yc</span></code></pre></div>
<pre><code>## # A tibble: 8,382 × 14
##    Date      `1 Mo` `2 Mo` `3 Mo` `4 Mo` `6 Mo`
##    &lt;chr&gt;     &lt;chr&gt;  &lt;chr&gt;   &lt;dbl&gt; &lt;chr&gt;   &lt;dbl&gt;
##  1 01/02/19… N/A    N/A      7.83 N/A      7.89
##  2 01/03/19… N/A    N/A      7.89 N/A      7.94
##  3 01/04/19… N/A    N/A      7.84 N/A      7.9 
##  4 01/05/19… N/A    N/A      7.79 N/A      7.85
##  5 01/08/19… N/A    N/A      7.79 N/A      7.88
##  6 01/09/19… N/A    N/A      7.8  N/A      7.82
##  7 01/10/19… N/A    N/A      7.75 N/A      7.78
##  8 01/11/19… N/A    N/A      7.8  N/A      7.8 
##  9 01/12/19… N/A    N/A      7.74 N/A      7.81
## 10 01/16/19… N/A    N/A      7.89 N/A      7.99
## # ℹ 8,372 more rows
## # ℹ 8 more variables: `1 Yr` &lt;dbl&gt;,
## #   `2 Yr` &lt;dbl&gt;, `3 Yr` &lt;dbl&gt;, `5 Yr` &lt;dbl&gt;,
## #   `7 Yr` &lt;dbl&gt;, `10 Yr` &lt;dbl&gt;,
## #   `20 Yr` &lt;chr&gt;, `30 Yr` &lt;chr&gt;</code></pre>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="importing-data-in-r.html#cb145-1" tabindex="-1"></a><span class="co"># Display the data in a spreadsheet-like format</span></span>
<span id="cb145-2"><a href="importing-data-in-r.html#cb145-2" tabindex="-1"></a><span class="fu">View</span>(yc)</span></code></pre></div>
<p>Both the <code>read_csv()</code> and <code>read_delim()</code> functions convert the CSV file into a tibble (<code>tbl_df</code>), a modern version of the R data frame discussed in Chapter <a href="r-data-types-and-structures.html#tibble">4.6</a>. Remember, a data frame stores data in separate columns, each of which must be of the same data type. Use the <code>class(yc)</code> function to check the data type of the entire dataset, and <code>sapply(yc, class)</code> to check the data type of each column:</p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="importing-data-in-r.html#cb146-1" tabindex="-1"></a><span class="co"># Check the data type of the entire dataset</span></span>
<span id="cb146-2"><a href="importing-data-in-r.html#cb146-2" tabindex="-1"></a><span class="fu">class</span>(yc)</span></code></pre></div>
<pre><code>## [1] &quot;spec_tbl_df&quot; &quot;tbl_df&quot;      &quot;tbl&quot;        
## [4] &quot;data.frame&quot;</code></pre>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="importing-data-in-r.html#cb148-1" tabindex="-1"></a><span class="co"># Check the data type of each column</span></span>
<span id="cb148-2"><a href="importing-data-in-r.html#cb148-2" tabindex="-1"></a><span class="fu">sapply</span>(yc, class)</span></code></pre></div>
<pre><code>##        Date        1 Mo        2 Mo 
## &quot;character&quot; &quot;character&quot; &quot;character&quot; 
##        3 Mo        4 Mo        6 Mo 
##   &quot;numeric&quot; &quot;character&quot;   &quot;numeric&quot; 
##        1 Yr        2 Yr        3 Yr 
##   &quot;numeric&quot;   &quot;numeric&quot;   &quot;numeric&quot; 
##        5 Yr        7 Yr       10 Yr 
##   &quot;numeric&quot;   &quot;numeric&quot;   &quot;numeric&quot; 
##       20 Yr       30 Yr 
## &quot;character&quot; &quot;character&quot;</code></pre>
<p>When importing data in R, it’s possible that R assigns incorrect data types to some columns. For example, the <code>Date</code> column is treated as a character column even though it contains dates, and the <code>30 Yr</code> column is treated as a character column even though it contains interest rates. To address this issue, you can convert the first column to a date type and the remaining columns to numeric data types using the following three steps:</p>
<ol style="list-style-type: decimal">
<li>Replace “N/A” with <code>NA</code>, which represents missing values in R. This step is necessary because R doesn’t recognize “N/A”, and if a column includes “N/A”, R will consider it as a character vector instead of a numeric vector.</li>
</ol>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="importing-data-in-r.html#cb150-1" tabindex="-1"></a>yc[yc <span class="sc">==</span> <span class="st">&quot;N/A&quot;</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span></code></pre></div>
<ol start="2" style="list-style-type: decimal">
<li>Convert all yield columns to numeric data types:</li>
</ol>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="importing-data-in-r.html#cb151-1" tabindex="-1"></a>yc[, <span class="sc">-</span><span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="fu">sapply</span>(yc[, <span class="sc">-</span><span class="dv">1</span>], as.numeric)</span></code></pre></div>
<p>The <code>as.numeric()</code> function converts a data object into a numeric type. In this case, it converts columns with character values like “3” and “4” into the numeric values 3 and 4. The <code>sapply()</code> function applies the <code>as.numeric()</code> function to each of the selected columns. This converts all the interest rates to numeric data types.</p>
<ol start="3" style="list-style-type: decimal">
<li>Convert the date column to a date object, recognizing that the date format is Month/Day/Year or <code>%m/%d/%Y</code>:</li>
</ol>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="importing-data-in-r.html#cb152-1" tabindex="-1"></a><span class="co"># Check the date format</span></span>
<span id="cb152-2"><a href="importing-data-in-r.html#cb152-2" tabindex="-1"></a><span class="fu">head</span>(yc<span class="sc">$</span>Date)</span></code></pre></div>
<pre><code>## [1] &quot;01/02/1990&quot; &quot;01/03/1990&quot; &quot;01/04/1990&quot;
## [4] &quot;01/05/1990&quot; &quot;01/08/1990&quot; &quot;01/09/1990&quot;</code></pre>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="importing-data-in-r.html#cb154-1" tabindex="-1"></a><span class="co"># Convert to date format</span></span>
<span id="cb154-2"><a href="importing-data-in-r.html#cb154-2" tabindex="-1"></a>yc<span class="sc">$</span>Date <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(yc<span class="sc">$</span>Date, <span class="at">format =</span> <span class="st">&quot;%m/%d/%Y&quot;</span>)</span>
<span id="cb154-3"><a href="importing-data-in-r.html#cb154-3" tabindex="-1"></a><span class="fu">head</span>(yc<span class="sc">$</span>Date)</span></code></pre></div>
<pre><code>## [1] &quot;1990-01-02&quot; &quot;1990-01-03&quot; &quot;1990-01-04&quot;
## [4] &quot;1990-01-05&quot; &quot;1990-01-08&quot; &quot;1990-01-09&quot;</code></pre>
<p>Hence, we have successfully imported the yield curve data and performed the necessary conversions to ensure that all columns are in their correct formats:</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="importing-data-in-r.html#cb156-1" tabindex="-1"></a>yc</span></code></pre></div>
<pre><code>## # A tibble: 8,382 × 14
##    Date       `1 Mo` `2 Mo` `3 Mo` `4 Mo`
##    &lt;date&gt;      &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
##  1 1990-01-02     NA     NA   7.83     NA
##  2 1990-01-03     NA     NA   7.89     NA
##  3 1990-01-04     NA     NA   7.84     NA
##  4 1990-01-05     NA     NA   7.79     NA
##  5 1990-01-08     NA     NA   7.79     NA
##  6 1990-01-09     NA     NA   7.8      NA
##  7 1990-01-10     NA     NA   7.75     NA
##  8 1990-01-11     NA     NA   7.8      NA
##  9 1990-01-12     NA     NA   7.74     NA
## 10 1990-01-16     NA     NA   7.89     NA
## # ℹ 8,372 more rows
## # ℹ 9 more variables: `6 Mo` &lt;dbl&gt;,
## #   `1 Yr` &lt;dbl&gt;, `2 Yr` &lt;dbl&gt;, `3 Yr` &lt;dbl&gt;,
## #   `5 Yr` &lt;dbl&gt;, `7 Yr` &lt;dbl&gt;, `10 Yr` &lt;dbl&gt;,
## #   `20 Yr` &lt;dbl&gt;, `30 Yr` &lt;dbl&gt;</code></pre>
<p>Here, <code>&lt;dbl&gt;</code> stands for double, which is the R data type for decimal numbers, also known as numeric type. Converting the yield columns to <code>dbl</code> ensures that the values are treated as numeric and can be used for calculations, analysis, and visualization.</p>
</div>
<div id="plotting-historical-yields" class="section level3 hasAnchor" number="5.2.2">
<h3><span class="header-section-number">5.2.2</span> Plotting Historical Yields<a href="importing-data-in-r.html#plotting-historical-yields" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s use the <code>plot()</code> function to visualize the imported yield curve data. In this case, we will plot the 3-month Treasury rate over time, using the <code>Date</code> column as the x-axis and the <code>3 Mo</code> column as the y-axis:</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="importing-data-in-r.html#cb158-1" tabindex="-1"></a><span class="co"># Plot the 3-month Treasury rate over time</span></span>
<span id="cb158-2"><a href="importing-data-in-r.html#cb158-2" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x =</span> yc<span class="sc">$</span>Date, <span class="at">y =</span> yc<span class="sc">$</span><span class="st">`</span><span class="at">3 Mo</span><span class="st">`</span>, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>,</span>
<span id="cb158-3"><a href="importing-data-in-r.html#cb158-3" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Date&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;%&quot;</span>, <span class="at">main =</span> <span class="st">&quot;3-Month Treasury Rate&quot;</span>)</span></code></pre></div>
<p>In the code snippet above, <code>plot()</code> is the R function used to create the plot. It takes several arguments to customize the appearance and behavior of the plot:</p>
<ul>
<li><code>x</code> represents the data to be plotted on the x-axis. In this case, it corresponds to the <code>Date</code> column from the yield curve data.</li>
<li><code>y</code> represents the data to be plotted on the y-axis. Here, it corresponds to the <code>3 Mo</code> column, which represents the 3-month Treasury rate.</li>
<li><code>type = "l"</code> specifies the type of plot to create. In this case, we use <code>"l"</code> to create a line plot.</li>
<li><code>xlab = "Date"</code> sets the label for the x-axis to “Date”.</li>
<li><code>ylab = "%"</code> sets the label for the y-axis to “%”.</li>
<li><code>main = "3-Month Treasury Rate"</code> sets the title of the plot to “3-Month Treasury Rate”.</li>
</ul>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:yield-historical-plot"></span>
<img src="daer_files/figure-html/yield-historical-plot-1.png" alt="3-Month Treasury Rate" width="80%" />
<p class="caption">
Figure 5.1: 3-Month Treasury Rate
</p>
</div>
<p>The resulting plot, shown in Figure <a href="importing-data-in-r.html#fig:yield-historical-plot">5.1</a>, displays the historical evolution of the 3-month Treasury rate since 1990. It allows us to observe how interest rates have changed over time, with low rates often observed during recessions and high rates during boom periods. Recessions are typically characterized by reduced borrowing and investment activities, leading to decreased demand for credit and lower interest rates. Conversely, boom periods are associated with strong economic growth and increased credit demand, which can drive interest rates upward.</p>
<p>Furthermore, inflation plays a significant role in influencing interest rates through the Fisher effect. When inflation is high, lenders and investors are concerned about the diminishing value of money over time. To compensate for the erosion of purchasing power, lenders typically demand higher interest rates on loans. These higher interest rates reflect the expectation of future inflation and act as a safeguard against the declining value of the money lent. Conversely, when inflation is low, lenders may offer lower interest rates due to reduced concerns about the erosion of purchasing power.</p>
</div>
<div id="plotting-yield-curve" class="section level3 hasAnchor" number="5.2.3">
<h3><span class="header-section-number">5.2.3</span> Plotting Yield Curve<a href="importing-data-in-r.html#plotting-yield-curve" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Next, let’s plot the yield curve. The yield curve is a graphical representation of the relationship between the interest rates (yields) and the time to maturity of a bond. It provides insights into market expectations regarding future interest rates and economic conditions.</p>
<p>To plot the yield curve, we will select the most recently available data from the dataset, which corresponds to the last row. We will extract the interest rates as a numeric vector and the column names (representing the time to maturity) as labels for the x-axis:</p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="importing-data-in-r.html#cb159-1" tabindex="-1"></a><span class="co"># Extract the interest rates of the last row</span></span>
<span id="cb159-2"><a href="importing-data-in-r.html#cb159-2" tabindex="-1"></a>yc_most_recent_data <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">last</span>(yc[, <span class="sc">-</span><span class="dv">1</span>]))</span>
<span id="cb159-3"><a href="importing-data-in-r.html#cb159-3" tabindex="-1"></a>yc_most_recent_data</span></code></pre></div>
<pre><code>##  [1] 5.24 5.39 5.43 5.50 5.47 5.40 4.87 4.49
##  [9] 4.13 3.97 3.81 4.06 3.85</code></pre>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="importing-data-in-r.html#cb161-1" tabindex="-1"></a><span class="co"># Extract the column names of the last row</span></span>
<span id="cb161-2"><a href="importing-data-in-r.html#cb161-2" tabindex="-1"></a>yc_most_recent_labels <span class="ot">&lt;-</span> <span class="fu">colnames</span>(<span class="fu">last</span>(yc[, <span class="sc">-</span><span class="dv">1</span>]))</span>
<span id="cb161-3"><a href="importing-data-in-r.html#cb161-3" tabindex="-1"></a>yc_most_recent_labels</span></code></pre></div>
<pre><code>##  [1] &quot;1 Mo&quot;  &quot;2 Mo&quot;  &quot;3 Mo&quot;  &quot;4 Mo&quot;  &quot;6 Mo&quot; 
##  [6] &quot;1 Yr&quot;  &quot;2 Yr&quot;  &quot;3 Yr&quot;  &quot;5 Yr&quot;  &quot;7 Yr&quot; 
## [11] &quot;10 Yr&quot; &quot;20 Yr&quot; &quot;30 Yr&quot;</code></pre>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="importing-data-in-r.html#cb163-1" tabindex="-1"></a><span class="co"># Plot the yield curve</span></span>
<span id="cb163-2"><a href="importing-data-in-r.html#cb163-2" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x =</span> yc_most_recent_data, <span class="at">xaxt =</span> <span class="st">&#39;n&#39;</span>, <span class="at">type =</span> <span class="st">&quot;o&quot;</span>, <span class="at">pch =</span> <span class="dv">19</span>,</span>
<span id="cb163-3"><a href="importing-data-in-r.html#cb163-3" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Time to Maturity&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Treasury Rate in %&quot;</span>,</span>
<span id="cb163-4"><a href="importing-data-in-r.html#cb163-4" tabindex="-1"></a>     <span class="at">main =</span> <span class="fu">paste</span>(<span class="st">&quot;Yield Curve on&quot;</span>, <span class="fu">format</span>(<span class="fu">last</span>(yc<span class="sc">$</span>Date), <span class="at">format =</span> <span class="st">&#39;%B %d, %Y&#39;</span>)))</span>
<span id="cb163-5"><a href="importing-data-in-r.html#cb163-5" tabindex="-1"></a><span class="fu">axis</span>(<span class="at">side =</span> <span class="dv">1</span>, <span class="at">at =</span> <span class="fu">seq</span>(<span class="dv">1</span>, <span class="fu">length</span>(yc_most_recent_labels), <span class="dv">1</span>), </span>
<span id="cb163-6"><a href="importing-data-in-r.html#cb163-6" tabindex="-1"></a>     <span class="at">labels =</span> yc_most_recent_labels)</span></code></pre></div>
<p>In the code snippet above, <code>plot()</code> is the R function used to create the yield curve plot. Here are the key inputs and arguments used in the function:</p>
<ul>
<li><code>x = yc_most_recent_data</code> represents the interest rates of the most recent yield curve data, which will be plotted on the x-axis.</li>
<li><code>xaxt = 'n'</code> specifies that no x-axis tick labels should be displayed initially. This is useful because we will customize the x-axis tick labels separately using the <code>axis()</code> function.</li>
<li><code>type = "o"</code> specifies that the plot should be created as a line plot with points. This will display the yield curve as a connected line with markers at each data point.</li>
<li><code>pch = 19</code> sets the plot symbol to a solid circle, which will be used as markers for the data points on the yield curve.</li>
<li><code>xlab = "Time to Maturity"</code> sets the label for the x-axis to “Time to Maturity”, indicating the variable represented on the x-axis.</li>
<li><code>ylab = "Treasury Rate in %"</code> sets the label for the y-axis to “Treasury Rate in %”, indicating the variable represented on the y-axis.</li>
<li><code>main = paste("Yield Curve on", format(last(yc$Date), format = '%B %d, %Y'))</code> sets the title of the plot to “Yield Curve on” followed by the date of the most recent yield curve data.</li>
</ul>
<p>Additionally, the <code>axis()</code> function is used to customize the x-axis tick labels. It sets the tick locations using <code>at = seq(1, length(yc_most_recent_labels), 1)</code> to evenly space the ticks along the x-axis. The <code>labels = yc_most_recent_labels</code> argument assigns the column names of the last row (representing maturities) as the tick labels on the x-axis.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:yield-curve-plot"></span>
<img src="daer_files/figure-html/yield-curve-plot-1.png" alt="Yield Curve on June 30, 2023" width="80%" />
<p class="caption">
Figure 5.2: Yield Curve on June 30, 2023
</p>
</div>
<p>The resulting plot, shown in Figure <a href="importing-data-in-r.html#fig:yield-curve-plot">5.2</a>, depicts the yield curve based on the most recent available data, allowing us to visualize the relationship between interest rates and the time to maturity. The x-axis represents the different maturities of the bonds, while the y-axis represents the corresponding treasury rates.</p>
<p>Analyzing the shape of the yield curve can provide insights into market expectations and can be useful for assessing economic conditions and making investment decisions. The yield curve can take different shapes, such as upward-sloping (normal), downward-sloping (inverted), or flat, each indicating different market conditions and expectations for future interest rates.</p>
<p>An upward-sloping yield curve, where longer-term interest rates are higher than shorter-term rates, is often seen during periods of economic expansion. This shape suggests that investors expect higher interest rates in the future as the economy grows and inflationary pressures increase. It reflects an optimistic outlook for economic conditions, as borrowing and lending activity are expected to be robust.</p>
<p>In contrast, a downward-sloping or inverted yield curve, where shorter-term interest rates are higher than longer-term rates, is often considered a predictor of economic slowdown or recession. This shape suggests that investors anticipate lower interest rates in the future as economic growth slows and inflationary pressures decrease. It reflects a more cautious outlook for the economy, as investors seek the safety of longer-term bonds amid expectations of lower returns and potential economic downturn.</p>
<p>Inflation expectations also influence the shape of the yield curve. When there are high inflation expectations for the long term, the yield curve tends to slope upwards. This occurs because lenders demand higher interest rates for longer maturities to compensate for anticipated inflation. However, when there is currently high inflation but expectations are that the central bank will successfully control inflation in the long term, the yield curve may slope downwards. In this case, long-term interest rates are lower than short-term rates, as average inflation over the long term is expected to be lower than in the short term.</p>
</div>
</div>
<div id="michigan-survey" class="section level2 hasAnchor" number="5.3">
<h2><span class="header-section-number">5.3</span> Michigan Survey<a href="importing-data-in-r.html#michigan-survey" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In this chapter, we’ll demonstrate how to import a TSV file using real-world consumer survey data collected by the University of Michigan.</p>
<p>To obtain the Michigan consumer survey data, follow these steps:</p>
<ol style="list-style-type: decimal">
<li>Visit the website of University of Michigan’s surveys of consumers by clicking <a href="https://data.sca.isr.umich.edu/">here</a>.</li>
<li>Click on “DATA” in the menu bar, then select “Time Series.”</li>
<li>On the data page, under Table, select “All: All Tables (Tab-delimited or CSV only)” to obtain the consumer survey data on all topics.</li>
<li>To access all the consumer survey data since 1978, type “1978” under the “Oldest Year” option.</li>
<li>Click on “Tab-Deliminated (Excel)” under the “format” option.</li>
<li>Save the TSV file in a location of your choice, ensuring that it is saved in a familiar folder for easy access.</li>
</ol>
<p>The dataset contains 360 variables with coded column names such as <code>ics_inc31</code> or <code>pago_dk_all</code>. To understand the meaning of these columns, you can visit the same website <a href="https://data.sca.isr.umich.edu/">here</a> and click on <a href="https://data.sca.isr.umich.edu/survey-info.php#">SURVEY INFORMATION</a>. From there, select the <a href="https://data.sca.isr.umich.edu/fetchdoc.php?docid=45121">Time-Series Variable Codebook</a> which is a PDF document that provides detailed explanations for all the column names. By referring to this codebook, you can gain a better understanding of the variables and their corresponding meanings in the dataset.</p>
<div id="import-tsv-file" class="section level3 hasAnchor" number="5.3.1">
<h3><span class="header-section-number">5.3.1</span> Import TSV File<a href="importing-data-in-r.html#import-tsv-file" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>TSV (Tab Separated Values) is a common file format used to store tabular data. As the name suggests, the values in each row of a TSV file are separated by tabs. Here’s an example of how data is stored in a TSV file:</p>
<ul>
<li>Male    8    100    3</li>
<li>Female    9    20    3</li>
</ul>
<p>To import the consumer survey TSV file, you need to install and load the <code>readr</code> package if you haven’t done so already. Once the package is loaded, you can use either the <code>read_tsv()</code> or <code>read_delim()</code> function to read the TSV (Tab-Separated Values) file.</p>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="importing-data-in-r.html#cb164-1" tabindex="-1"></a><span class="co"># Load the package</span></span>
<span id="cb164-2"><a href="importing-data-in-r.html#cb164-2" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;readr&quot;</span>)</span>
<span id="cb164-3"><a href="importing-data-in-r.html#cb164-3" tabindex="-1"></a></span>
<span id="cb164-4"><a href="importing-data-in-r.html#cb164-4" tabindex="-1"></a><span class="co"># Import TSV file</span></span>
<span id="cb164-5"><a href="importing-data-in-r.html#cb164-5" tabindex="-1"></a>cs <span class="ot">&lt;-</span> <span class="fu">read_tsv</span>(<span class="at">file =</span> <span class="st">&quot;files/sca-tableall-on-2023-Jul-01.tsv&quot;</span>, <span class="at">skip =</span> <span class="dv">1</span>)</span>
<span id="cb164-6"><a href="importing-data-in-r.html#cb164-6" tabindex="-1"></a></span>
<span id="cb164-7"><a href="importing-data-in-r.html#cb164-7" tabindex="-1"></a><span class="co"># Import TSV file using the read_delim() function</span></span>
<span id="cb164-8"><a href="importing-data-in-r.html#cb164-8" tabindex="-1"></a>cs <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(<span class="at">file =</span> <span class="st">&quot;files/sca-tableall-on-2023-Jul-01.tsv&quot;</span>, <span class="at">skip =</span> <span class="dv">1</span>, <span class="at">col_names =</span> <span class="cn">TRUE</span>, <span class="at">delim =</span> <span class="st">&quot;</span><span class="sc">\t</span><span class="st">&quot;</span>)</span></code></pre></div>
<p>In the provided code snippets, the <code>file</code> input specifies the file path or URL of the TSV file to be imported. The <code>skip</code> input is used to specify the number of rows to skip at the beginning of the file. In this case, <code>skip = 1</code> indicates that the first line of the TSV file, which contains the title “All Tables”, should be skipped. The <code>col_names</code> input is set to <code>TRUE</code> to indicate that the second line of the TSV file (after skipping 1 row) contains the column names. Lastly, the <code>delim</code> input is set to <code>"\t"</code> to specify that the columns in the TSV file are separated by tabs, which is the standard delimiter for TSV (<em>Tab</em> Separated Values) files.</p>
<p>Note that if the file is neither CSV nor TSV, but rather has an exotic format where columns are separated by a different character that is neither a comma nor a tab, such as “/”, you can use the <code>read_delim()</code> function with the <code>delim = "/"</code> argument to specify the custom delimiter.</p>
<p>To inspect the first few rows of the data, print the <code>cs</code> object in the console. For an overview of the entire dataset, execute <code>View(cs)</code>.</p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="importing-data-in-r.html#cb165-1" tabindex="-1"></a><span class="co"># Display the data</span></span>
<span id="cb165-2"><a href="importing-data-in-r.html#cb165-2" tabindex="-1"></a>cs</span></code></pre></div>
<pre><code>## # A tibble: 545 × 360
##    Month  yyyy ics_all ics_inc31 ics_inc32
##    &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
##  1     1  1978    83.7        NA        NA
##  2     2  1978    84.3        NA        NA
##  3     3  1978    78.8        NA        NA
##  4     4  1978    81.6        NA        NA
##  5     5  1978    82.9        NA        NA
##  6     6  1978    80          NA        NA
##  7     7  1978    82.4        NA        NA
##  8     8  1978    78.4        NA        NA
##  9     9  1978    80.4        NA        NA
## 10    10  1978    79.3        NA        NA
## # ℹ 535 more rows
## # ℹ 355 more variables: ics_inc33 &lt;dbl&gt;,
## #   ics_a1834 &lt;dbl&gt;, ics_a3554 &lt;dbl&gt;,
## #   ics_a5597 &lt;dbl&gt;, ics_ne &lt;dbl&gt;,
## #   ics_nc &lt;dbl&gt;, ics_s &lt;dbl&gt;, ics_w &lt;dbl&gt;,
## #   icc_all &lt;dbl&gt;, ice_all &lt;dbl&gt;,
## #   pago_f_all &lt;dbl&gt;, pago_s_all &lt;dbl&gt;, …</code></pre>
<p>Use <code>sapply(cs, class)</code> to check the data type of each column, to make sure all columns are indeed numeric:</p>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="importing-data-in-r.html#cb167-1" tabindex="-1"></a><span class="co"># Check the data type of each column</span></span>
<span id="cb167-2"><a href="importing-data-in-r.html#cb167-2" tabindex="-1"></a><span class="fu">table</span>(<span class="fu">sapply</span>(cs, class))</span></code></pre></div>
<pre><code>## 
## logical numeric 
##       1     359</code></pre>
<p>Here, since there are 360 columns, the <code>summary()</code> function is applied, which reveals that there are 359 numerical columns, and 1 logical column, which makes sense.</p>
<p>Instead of a date column, the consumer survey has a year (<code>yyyy</code>) and a month (<code>Month</code>) column. To create a date column from the year and month columns, combine them with the <code>paste()</code> function to create a date format of the form Year-Month-Day or <code>%Y-%m-%d</code>:</p>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb169-1"><a href="importing-data-in-r.html#cb169-1" tabindex="-1"></a><span class="co"># Create date column</span></span>
<span id="cb169-2"><a href="importing-data-in-r.html#cb169-2" tabindex="-1"></a>cs<span class="sc">$</span>Date <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(<span class="fu">paste</span>(cs<span class="sc">$</span>yyyy, cs<span class="sc">$</span>Month, <span class="st">&quot;01&quot;</span>, <span class="at">sep =</span> <span class="st">&quot;-&quot;</span>))</span>
<span id="cb169-3"><a href="importing-data-in-r.html#cb169-3" tabindex="-1"></a><span class="fu">head</span>(cs<span class="sc">$</span>Date)</span></code></pre></div>
<pre><code>## [1] &quot;1978-01-01&quot; &quot;1978-02-01&quot; &quot;1978-03-01&quot;
## [4] &quot;1978-04-01&quot; &quot;1978-05-01&quot; &quot;1978-06-01&quot;</code></pre>
</div>
<div id="plotting-consumer-indices" class="section level3 hasAnchor" number="5.3.2">
<h3><span class="header-section-number">5.3.2</span> Plotting Consumer Indices<a href="importing-data-in-r.html#plotting-consumer-indices" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The Michigan Consumer Survey consists of a wide range of survey responses from a sample of households collected every month. These survey responses are gathered to produce indices about how consumers feel each period. The University of Michigan produces three main indices: the Index of Consumer Confidence (ICC), the Index of Current Economic Conditions (ICE), and the Index of Consumer Sentiment (ICS). These indices are designed to measure different aspects of consumer attitudes and perceptions regarding the economy.</p>
<ol style="list-style-type: decimal">
<li><p><strong>Index of Consumer Confidence (ICC)</strong>: The ICC reflects consumers’ expectations about future economic conditions and their overall optimism or pessimism. It is based on consumers’ assessments of their future financial prospects, job availability, and economic outlook. A higher ICC value indicates greater consumer confidence and positive expectations for the economy.</p></li>
<li><p><strong>Index of Current Economic Conditions (ICE)</strong>: The ICE assesses consumers’ perceptions of the current economic environment. It reflects their evaluations of their personal financial situation, job security, and their perception of whether it is a good time to make major purchases. The ICE provides insights into the current economic conditions as perceived by consumers.</p></li>
<li><p><strong>Index of Consumer Sentiment (ICS)</strong>: The ICS combines both the ICC and ICE to provide an overall measure of consumer sentiment. It takes into account consumers’ expectations for the future as well as their assessment of the present economic conditions. The ICS is often used as an indicator of consumer behavior and their likelihood of making purchases and engaging in economic activities.</p></li>
</ol>
<p>These indices are calculated based on survey responses from a sample of households, and they serve as important indicators of consumer sentiment and economic trends. They are widely followed by economists, policymakers, and financial markets as they provide valuable insights into consumers’ attitudes and perceptions, which can impact their spending behavior and overall economic activity.</p>
<p>Let’s use the <code>plot()</code> function to visualize the imported Michigan consumer survey data. In this case, we will plot the three key indices: ICC, ICE, and ICS over time, using the Date column as the x-axis and the three indices as the y-axis:</p>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb171-1"><a href="importing-data-in-r.html#cb171-1" tabindex="-1"></a><span class="co"># Plot ICC, ICE, and ICS over time</span></span>
<span id="cb171-2"><a href="importing-data-in-r.html#cb171-2" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x =</span> cs<span class="sc">$</span>Date, <span class="at">y =</span> cs<span class="sc">$</span>icc_all, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">col =</span> <span class="dv">5</span>, <span class="at">lwd =</span> <span class="dv">3</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">40</span>, <span class="dv">140</span>),</span>
<span id="cb171-3"><a href="importing-data-in-r.html#cb171-3" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Date&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Index&quot;</span>, <span class="at">main =</span> <span class="st">&quot;Key Indices of the Michigan Consumer Survey&quot;</span>)</span>
<span id="cb171-4"><a href="importing-data-in-r.html#cb171-4" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x =</span> cs<span class="sc">$</span>Date, <span class="at">y =</span> cs<span class="sc">$</span>ice_all, <span class="at">col =</span> <span class="dv">2</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb171-5"><a href="importing-data-in-r.html#cb171-5" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x =</span> cs<span class="sc">$</span>Date, <span class="at">y =</span> cs<span class="sc">$</span>ics_all, <span class="at">col =</span> <span class="dv">1</span>, <span class="at">lwd =</span> <span class="fl">1.5</span>)</span>
<span id="cb171-6"><a href="importing-data-in-r.html#cb171-6" tabindex="-1"></a><span class="fu">legend</span>(<span class="at">x =</span> <span class="st">&quot;topleft&quot;</span>, <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">&quot;ICC&quot;</span>, <span class="st">&quot;ICE&quot;</span>, <span class="st">&quot;ICS&quot;</span>), </span>
<span id="cb171-7"><a href="importing-data-in-r.html#cb171-7" tabindex="-1"></a>       <span class="at">col =</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">2</span>, <span class="dv">1</span>), <span class="at">lwd =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">2</span>, <span class="fl">1.5</span>), <span class="at">horiz =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p>In the code snippet provided, the appearance and behavior of the plot are customized using several functions and arguments:</p>
<ul>
<li><code>x</code>: This argument specifies the data to be used for the x-axis of the plot. In this case, it is <code>cs$Date</code>, indicating the “Date” column of the Michigan consumer survey data.</li>
<li><code>y</code>: This argument specifies the data to be used for the y-axis of the plot. In this case, it is <code>cs$icc_all</code>, <code>cs$ice_all</code>, and <code>cs$ics_all</code>, representing the ICC, ICE, and ICS indices from the Michigan consumer survey data.</li>
<li><code>type</code>: This argument determines the type of plot to be created. In this case, it is set to <code>"l"</code>, which stands for “line plot”. This will create a line plot of the data points.</li>
<li><code>col</code>: This argument specifies the color of the lines in the plot. In the code snippet, different colors are used for each index: <code>5</code> for ICC, <code>2</code> for ICE, and <code>1</code> for ICS.</li>
<li><code>lwd</code>: This argument controls the line width of the plot. It is set to <code>3</code> for ICC, <code>2</code> for ICE, and <code>1.5</code> for ICS, indicating different line widths for each index.</li>
<li><code>ylim</code>: This argument sets the limits of the y-axis. In this case, it is set to <code>c(40, 140)</code>, which defines the range of the y-axis from 40 to 140.</li>
<li><code>xlab</code>: This argument specifies the label for the x-axis of the plot. In the code snippet, it is set to <code>"Date"</code>.</li>
<li><code>ylab</code>: This argument specifies the label for the y-axis of the plot. In the code snippet, it is set to <code>"Index"</code>.</li>
<li><code>main</code>: This argument specifies the main title of the plot. In the code snippet, it is set to <code>"Key Indices of the Michigan Consumer Survey"</code>.</li>
<li><code>lines</code>: This function is used to add additional lines to the plot.</li>
<li><code>legend</code>: This function adds a legend to the plot. It is used to create a legend in the top-left corner (<code>x = "topleft"</code>) with labels corresponding to each index (<code>"ICC"</code>, <code>"ICE"</code>, <code>"ICS"</code>) and their respective line colors and widths.</li>
</ul>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:icc-ice-ics-plot"></span>
<img src="daer_files/figure-html/icc-ice-ics-plot-1.png" alt="Key Indices of the Michigan Consumer Survey" width="80%" />
<p class="caption">
Figure 5.3: Key Indices of the Michigan Consumer Survey
</p>
</div>
<p>The resulting plot, shown in Figure <a href="importing-data-in-r.html#fig:icc-ice-ics-plot">5.3</a>, displays the historical evolution of the three Michigan consumer survey indices: ICC, ICE, and ICS. These indices are considered leading indicators because they provide early signals about changes in consumer sentiment and economic conditions. They often reflect consumers’ expectations and attitudes before these changes are fully manifested in traditional economic indicators, such as unemployment rates or GDP growth.</p>
<p>Consumer sentiment plays a crucial role in shaping consumer behavior, including spending patterns, saving habits, and investment decisions. When consumer confidence is high, individuals are more likely to spend and invest, stimulating economic growth. Conversely, low consumer confidence can lead to reduced spending and investment, potentially dampening economic activity. Hence, these indices can serve as an early warning system for potential shifts in economic activity.</p>
<p>By incorporating the consumer survey indices alongside traditional economic indicators, policymakers and analysts can gain a more comprehensive understanding of the economic landscape. While traditional indicators like unemployment rates provide objective measures of economic conditions, the consumer survey indices offer a subjective perspective, reflecting consumers’ beliefs, expectations, and intentions. This subjective insight can provide additional context and help anticipate changes in consumer behavior and overall economic activity.</p>
<p>Therefore, by monitoring both traditional economic indicators and the Michigan consumer survey indices, policymakers and analysts can obtain a more holistic view of the economy, enabling them to make more informed decisions and implement timely interventions to support economic stability and growth.</p>
</div>
</div>
<div id="tealbook" class="section level2 hasAnchor" number="5.4">
<h2><span class="header-section-number">5.4</span> Tealbook<a href="importing-data-in-r.html#tealbook" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In this chapter, we’ll demonstrate how to import an Excel workbook (<code>xls</code> or <code>xlsx</code>) by importing projections data from Tealbooks (formerly known as Greenbooks). The Tealbook contains economic forecasts prepared by the Research staff at the Federal Reserve Board of Governors. These forecasts are produced before each meeting of the Federal Open Market Committee and provide insights into the future performance of the economy. The data from Tealbooks are made available to the public with a five-year lag.</p>
<p>To obtain the Tealbook forecasts, perform the following steps:</p>
<ol style="list-style-type: decimal">
<li>Visit the website of the Federal Reserve Bank of Philadelphia by clicking <a href="https://www.philadelphiafed.org/">here</a>.</li>
<li>Navigate to <a href="https://www.philadelphiafed.org/surveys-and-data">SURVEYS &amp; DATA</a>, select <a href="https://www.philadelphiafed.org/surveys-and-data/real-time-data-research">Real-Time Data Research</a>, choose <a href="https://www.philadelphiafed.org/surveys-and-data/real-time-data-research/greenbook">Tealbook (formerly Greenbook) Data Sets</a>, and finally select <a href="https://www.philadelphiafed.org/surveys-and-data/real-time-data-research/philadelphia-data-set">Philadelphia Fed’s Tealbook (formerly Greenbook) Data Set</a>.</li>
<li>On the data page, download <a href="https://www.philadelphiafed.org/-/media/frbp/assets/surveys-and-data/greenbook-data/documentation/gbweb_row_format.xlsx?la=en&amp;hash=ADEEBF4E1E339624C8C55B9EAB26B23F">Philadelphia Fed’s Tealbook/Greenbook Data Set: Row Format</a>.</li>
<li>Save the Excel workbook as ‘GBweb_Row_Format.xlsx’ in a familiar location for easy retrieval.</li>
</ol>
<p>The Excel workbook contains multiple sheets, each representing different variables. The sheet <code>gRGDP</code>, for example, holds real GDP growth forecasts. Columns <code>gRGDPF1</code> to <code>gRGDPF9</code> represent one- to nine-quarter-ahead forecasts, <code>gRGDPF0</code> represents the nowcast, and <code>gRGDPB1</code> to <code>gRGDPB4</code> represent one- to four-quarter-behind backcasts.</p>
<div id="import-excel-workbook" class="section level3 hasAnchor" number="5.4.1">
<h3><span class="header-section-number">5.4.1</span> Import Excel Workbook<a href="importing-data-in-r.html#import-excel-workbook" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>An Excel workbook (<code>xlsx</code>) is a file that contains one or more spreadsheets (worksheets), which are the separate “pages” or “tabs” within the file. An Excel worksheet, or simply a sheet, is a single spreadsheet within an Excel workbook. It consists of a grid of cells formed by intersecting rows (labeled by numbers) and columns (labeled by letters), which can hold data such as text, numbers, and formulas.</p>
<p>To import the Tealbook, which is an Excel workbook, install and load the <code>readxl</code> package by running <code>install.packages("readxl")</code> in the console and include the package at the beginning of your R script. You can then use the <code>excel_sheets()</code> function to print the names of all Excel worksheets in the workbook, and the <code>read_excel()</code> function to import a particular worksheet:</p>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb172-1"><a href="importing-data-in-r.html#cb172-1" tabindex="-1"></a><span class="co"># Load the package</span></span>
<span id="cb172-2"><a href="importing-data-in-r.html#cb172-2" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;readxl&quot;</span>)</span>
<span id="cb172-3"><a href="importing-data-in-r.html#cb172-3" tabindex="-1"></a></span>
<span id="cb172-4"><a href="importing-data-in-r.html#cb172-4" tabindex="-1"></a><span class="co"># Get names of all Excel worksheets</span></span>
<span id="cb172-5"><a href="importing-data-in-r.html#cb172-5" tabindex="-1"></a>sheet_names <span class="ot">&lt;-</span> <span class="fu">excel_sheets</span>(<span class="at">path =</span> <span class="st">&quot;files/GBweb_Row_Format.xlsx&quot;</span>)</span>
<span id="cb172-6"><a href="importing-data-in-r.html#cb172-6" tabindex="-1"></a>sheet_names</span></code></pre></div>
<pre><code>##  [1] &quot;Documentation&quot; &quot;gRGDP&quot;        
##  [3] &quot;gPGDP&quot;         &quot;UNEMP&quot;        
##  [5] &quot;gPCPI&quot;         &quot;gPCPIX&quot;       
##  [7] &quot;gPPCE&quot;         &quot;gPPCEX&quot;       
##  [9] &quot;gRPCE&quot;         &quot;gRBF&quot;         
## [11] &quot;gRRES&quot;         &quot;gRGOVF&quot;       
## [13] &quot;gRGOVSL&quot;       &quot;gNGDP&quot;        
## [15] &quot;HSTART&quot;        &quot;gIP&quot;</code></pre>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb174-1"><a href="importing-data-in-r.html#cb174-1" tabindex="-1"></a><span class="co"># Import one of the Excel worksheets: &quot;gRGDP&quot;</span></span>
<span id="cb174-2"><a href="importing-data-in-r.html#cb174-2" tabindex="-1"></a>gRGDP <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="at">path =</span> <span class="st">&quot;files/GBweb_Row_Format.xlsx&quot;</span>, <span class="at">sheet =</span> <span class="st">&quot;gRGDP&quot;</span>)</span>
<span id="cb174-3"><a href="importing-data-in-r.html#cb174-3" tabindex="-1"></a>gRGDP</span></code></pre></div>
<pre><code>## # A tibble: 466 × 16
##     DATE gRGDPB4 gRGDPB3 gRGDPB2 gRGDPB1
##    &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
##  1 1967.     5.9     1.9     4       4.5
##  2 1967.     1.9     4       4.5     0  
##  3 1967.     1.9     4       4.5    -0.3
##  4 1967.     1.9     4       4.5    -0.3
##  5 1967.     3.4     3.8    -0.2     2.4
##  6 1967.     3.4     3.8    -0.2     2.4
##  7 1967.     3.4     3.8    -0.2     2.4
##  8 1967.     3.4     3.8    -0.2     2.4
##  9 1967.     3.8    -0.2     2.4     4.2
## 10 1967.     3.8    -0.2     2.4     4.2
## # ℹ 456 more rows
## # ℹ 11 more variables: gRGDPF0 &lt;dbl&gt;,
## #   gRGDPF1 &lt;dbl&gt;, gRGDPF2 &lt;dbl&gt;,
## #   gRGDPF3 &lt;dbl&gt;, gRGDPF4 &lt;dbl&gt;,
## #   gRGDPF5 &lt;dbl&gt;, gRGDPF6 &lt;dbl&gt;,
## #   gRGDPF7 &lt;dbl&gt;, gRGDPF8 &lt;dbl&gt;,
## #   gRGDPF9 &lt;dbl&gt;, GBdate &lt;dbl&gt;</code></pre>
<p>To import all sheets, use the following code:</p>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb176-1"><a href="importing-data-in-r.html#cb176-1" tabindex="-1"></a><span class="co"># Import all worksheets of Excel workbook</span></span>
<span id="cb176-2"><a href="importing-data-in-r.html#cb176-2" tabindex="-1"></a>TB <span class="ot">&lt;-</span> <span class="fu">lapply</span>(sheet_names, <span class="cf">function</span>(x) <span class="fu">read_excel</span>(<span class="at">path =</span> <span class="st">&quot;files/GBweb_Row_Format.xlsx&quot;</span>, <span class="at">sheet =</span> x))</span>
<span id="cb176-3"><a href="importing-data-in-r.html#cb176-3" tabindex="-1"></a><span class="fu">names</span>(TB) <span class="ot">&lt;-</span> sheet_names</span>
<span id="cb176-4"><a href="importing-data-in-r.html#cb176-4" tabindex="-1"></a></span>
<span id="cb176-5"><a href="importing-data-in-r.html#cb176-5" tabindex="-1"></a><span class="co"># Summarize the list containing all Excel worksheets</span></span>
<span id="cb176-6"><a href="importing-data-in-r.html#cb176-6" tabindex="-1"></a><span class="fu">summary</span>(TB)</span></code></pre></div>
<pre><code>##               Length Class  Mode
## Documentation  2     tbl_df list
## gRGDP         16     tbl_df list
## gPGDP         16     tbl_df list
## UNEMP         16     tbl_df list
## gPCPI         16     tbl_df list
## gPCPIX        16     tbl_df list
## gPPCE         16     tbl_df list
## gPPCEX        16     tbl_df list
## gRPCE         16     tbl_df list
## gRBF          16     tbl_df list
## gRRES         16     tbl_df list
## gRGOVF        16     tbl_df list
## gRGOVSL       16     tbl_df list
## gNGDP         16     tbl_df list
## HSTART        16     tbl_df list
## gIP           16     tbl_df list</code></pre>
<p>In the provided code snippet, the <code>lapply()</code> function is used to apply the <code>read_excel()</code> function to each element in the <code>sheet_names</code> list, returning a list that is the same length as the input. Consequently, the <code>TB</code> object becomes a list in which each element is a tibble corresponding to an individual Excel worksheet. For instance, to access the worksheet that contains unemployment forecasts, you would use the following code:</p>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb178-1"><a href="importing-data-in-r.html#cb178-1" tabindex="-1"></a><span class="co"># Print one of the worksheets (unemployment forecasts):</span></span>
<span id="cb178-2"><a href="importing-data-in-r.html#cb178-2" tabindex="-1"></a>TB[[<span class="st">&quot;UNEMP&quot;</span>]]</span></code></pre></div>
<pre><code>## # A tibble: 466 × 16
##     DATE UNEMPB4 UNEMPB3 UNEMPB2 UNEMPB1
##    &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
##  1 1967.     3.8     3.8     3.8     3.7
##  2 1967.     3.8     3.8     3.7     3.7
##  3 1967.     3.8     3.8     3.7     3.7
##  4 1967.     3.8     3.8     3.7     3.7
##  5 1967.     3.8     3.7     3.7     3.8
##  6 1967.     3.8     3.7     3.7     3.8
##  7 1967.     3.8     3.7     3.7     3.8
##  8 1967.     3.8     3.7     3.7     3.8
##  9 1967.     3.7     3.7     3.8     3.9
## 10 1967.     3.7     3.7     3.8     3.9
## # ℹ 456 more rows
## # ℹ 11 more variables: UNEMPF0 &lt;dbl&gt;,
## #   UNEMPF1 &lt;dbl&gt;, UNEMPF2 &lt;dbl&gt;,
## #   UNEMPF3 &lt;dbl&gt;, UNEMPF4 &lt;dbl&gt;,
## #   UNEMPF5 &lt;dbl&gt;, UNEMPF6 &lt;dbl&gt;,
## #   UNEMPF7 &lt;dbl&gt;, UNEMPF8 &lt;dbl&gt;,
## #   UNEMPF9 &lt;dbl&gt;, GBdate &lt;chr&gt;</code></pre>
</div>
<div id="nowcast-and-backcast" class="section level3 hasAnchor" number="5.4.2">
<h3><span class="header-section-number">5.4.2</span> Nowcast and Backcast<a href="importing-data-in-r.html#nowcast-and-backcast" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s explore the forecaster data, interpreting the information provided in the <a href="https://www.philadelphiafed.org/-/media/frbp/assets/surveys-and-data/greenbook-data/documentation/documentation_phila_fed_greenbook_data_set.pdf?la=en&amp;hash=8FBBCD1AADB723B207B25441D0AB66A3">Tealbook Documentation file</a>. This file is accessible on the same page as the data, albeit further down. The data set extends beyond simple forecasts, encompassing nowcasts and backcasts as well.</p>
<p>The imported Excel workbook <code>GBweb_Row_Format.xlsx</code> includes multiple sheets, each one representing distinct variables. Take, for instance, the sheet <code>gPGDP</code>, which contains forecasts for inflation (GDP deflator). Columns <code>gPGDPF1</code> through <code>gPGDPF9</code> represent forecasts for one to nine quarters ahead respectively, while <code>gPGDPF0</code> denotes the nowcast. The columns <code>gPGDPB1</code> to <code>gPGDPB4</code>, on the other hand, symbolize backcasts for one to four quarters in the past.</p>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb180-1"><a href="importing-data-in-r.html#cb180-1" tabindex="-1"></a><span class="co"># Print column names of inflation back-, now-, and forecasts</span></span>
<span id="cb180-2"><a href="importing-data-in-r.html#cb180-2" tabindex="-1"></a><span class="fu">colnames</span>(TB[[<span class="st">&quot;gPGDP&quot;</span>]])</span></code></pre></div>
<pre><code>##  [1] &quot;DATE&quot;    &quot;gPGDPB4&quot; &quot;gPGDPB3&quot; &quot;gPGDPB2&quot;
##  [5] &quot;gPGDPB1&quot; &quot;gPGDPF0&quot; &quot;gPGDPF1&quot; &quot;gPGDPF2&quot;
##  [9] &quot;gPGDPF3&quot; &quot;gPGDPF4&quot; &quot;gPGDPF5&quot; &quot;gPGDPF6&quot;
## [13] &quot;gPGDPF7&quot; &quot;gPGDPF8&quot; &quot;gPGDPF9&quot; &quot;GBdate&quot;</code></pre>
<p>A <strong>nowcast</strong> (<code>gPGDPF0</code>) effectively serves as a present-time prediction. Given the delay in the release of economic data, nowcasting equips economists with the tools to make informed estimates about what current data will ultimately reveal once it is officially published.</p>
<p>Conversely, a <strong>backcast</strong> (<code>gPGDPB1</code> through <code>gPGDPB4</code>) is a forecast formulated for a time period that has already transpired. This might seem counterintuitive, but it’s necessary because the initial estimates of economic data are often revised significantly as more information becomes available.</p>
<p>It is noteworthy that financial data typically doesn’t experience such revisions, since interest rates or asset prices are directly observed on exchanges, eliminating the need for revisions. In contrast, inflation is not directly observable and requires deduction from a wide array of information sources. These sources can encompass export data, industrial production statistics, retail sales data, employment figures, consumer spending metrics, and capital investment data, among others.</p>
<p>In summary, while forecasting seeks to predict future economic scenarios, nowcasting aspires to deliver an accurate snapshot of the current economy, and backcasting strives to enhance our understanding of historical economic conditions.</p>
</div>
<div id="information-date-and-realization-date" class="section level3 hasAnchor" number="5.4.3">
<h3><span class="header-section-number">5.4.3</span> Information Date and Realization Date<a href="importing-data-in-r.html#information-date-and-realization-date" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The imported Excel workbook <code>GBweb_Row_Format.xlsx</code> is structured in a <strong>row format</strong> as opposed to a column format. As clarified in the <a href="https://www.philadelphiafed.org/-/media/frbp/assets/surveys-and-data/greenbook-data/documentation/documentation_phila_fed_greenbook_data_set.pdf?la=en&amp;hash=8FBBCD1AADB723B207B25441D0AB66A3">Tealbook Documentation file</a>, this arrangement means that (1) each row corresponds to a specific Tealbook publication date, and (2) the columns represent the forecasts generated for that particular Tealbook. The forecast horizons include, at most, the four quarters preceding the nowcast quarter, the nowcast quarter itself, and up to nine quarters into the future. Thus, all the values in a single row refer to the same forecast date, yet different forecast horizons.</p>
<p>Let’s define <strong>information date</strong> as the specific date when a forecast is generated, and <strong>realization date</strong> as the exact time period the forecast is referring to. In the row format data structure, each row in the data set corresponds to a specific information date, with the columns indicating different forecast horizons, and hence, different realization dates. This allows a comparative view of how the forecast relates to both current and past data. For instance, if a GDP growth forecast exceeds the nowcast, it suggests an optimistic outlook on that particular information date.</p>
<p>However, it is often useful to compare different information dates that all correspond to the same realization date. For example, the forecast error is calculated by comparing a forecast from an earlier information date with a backcast created at a later information date, while both the forecast and backcast relate to the same realization date. If the data is organized in <strong>column format</strong>, then each row pertains to a certain realization date, and the columns correspond to different information dates. Regardless of whether we import the data in row or column format, we need to be able to manipulate the data set to compare both different information and realization dates with each other.</p>
</div>
<div id="plotting-forecasts" class="section level3 hasAnchor" number="5.4.4">
<h3><span class="header-section-number">5.4.4</span> Plotting Forecasts<a href="importing-data-in-r.html#plotting-forecasts" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s use the <code>plot()</code> function to visualize some of the real GDP growth forecasts. We will plot the Tealbook forecasts for three different information dates, where the x-axis represents the realization date and the y-axis represents the real GDP growth forecasts made at the information date:</p>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb182-1"><a href="importing-data-in-r.html#cb182-1" tabindex="-1"></a><span class="co"># Extract the real GDP growth worksheet</span></span>
<span id="cb182-2"><a href="importing-data-in-r.html#cb182-2" tabindex="-1"></a>gRGDP <span class="ot">&lt;-</span> TB[[<span class="st">&quot;gRGDP&quot;</span>]]</span>
<span id="cb182-3"><a href="importing-data-in-r.html#cb182-3" tabindex="-1"></a></span>
<span id="cb182-4"><a href="importing-data-in-r.html#cb182-4" tabindex="-1"></a><span class="co"># Create a date column capturing the information date</span></span>
<span id="cb182-5"><a href="importing-data-in-r.html#cb182-5" tabindex="-1"></a>gRGDP<span class="sc">$</span>date_info <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(<span class="fu">as.character</span>(gRGDP<span class="sc">$</span>GBdate), <span class="at">format =</span> <span class="st">&quot;%Y%m%d&quot;</span>)</span>
<span id="cb182-6"><a href="importing-data-in-r.html#cb182-6" tabindex="-1"></a></span>
<span id="cb182-7"><a href="importing-data-in-r.html#cb182-7" tabindex="-1"></a><span class="co"># Select information dates to plot</span></span>
<span id="cb182-8"><a href="importing-data-in-r.html#cb182-8" tabindex="-1"></a>dates <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(<span class="fu">c</span>(<span class="st">&quot;2008-06-18&quot;</span>, <span class="st">&quot;2008-12-10&quot;</span>, <span class="st">&quot;2009-08-06&quot;</span>))</span>
<span id="cb182-9"><a href="importing-data-in-r.html#cb182-9" tabindex="-1"></a></span>
<span id="cb182-10"><a href="importing-data-in-r.html#cb182-10" tabindex="-1"></a><span class="co"># Plot forecasts of second information date</span></span>
<span id="cb182-11"><a href="importing-data-in-r.html#cb182-11" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x =</span> <span class="fu">as.yearqtr</span>(dates[<span class="dv">2</span>]) <span class="sc">+</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">4</span>, <span class="dv">9</span>) <span class="sc">/</span> <span class="dv">4</span>, </span>
<span id="cb182-12"><a href="importing-data-in-r.html#cb182-12" tabindex="-1"></a>     <span class="at">y =</span> <span class="fu">as.numeric</span>(gRGDP[gRGDP<span class="sc">$</span>date_info <span class="sc">==</span> dates[<span class="dv">2</span>], <span class="dv">2</span><span class="sc">:</span><span class="dv">15</span>]), </span>
<span id="cb182-13"><a href="importing-data-in-r.html#cb182-13" tabindex="-1"></a>     <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">col =</span> <span class="dv">5</span>, <span class="at">lwd =</span> <span class="dv">5</span>, <span class="at">lty =</span> <span class="dv">1</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">7</span>, <span class="dv">5</span>), </span>
<span id="cb182-14"><a href="importing-data-in-r.html#cb182-14" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">as.yearqtr</span>(dates[<span class="dv">2</span>]) <span class="sc">+</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">6</span>, <span class="dv">8</span>) <span class="sc">/</span> <span class="dv">4</span>,</span>
<span id="cb182-15"><a href="importing-data-in-r.html#cb182-15" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Realization Date&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;%&quot;</span>, </span>
<span id="cb182-16"><a href="importing-data-in-r.html#cb182-16" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Back-, Now-, and Forecasts of Real GDP Growth&quot;</span>)</span>
<span id="cb182-17"><a href="importing-data-in-r.html#cb182-17" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="fu">as.yearqtr</span>(dates[<span class="dv">2</span>]), <span class="at">col =</span> <span class="dv">5</span>, <span class="at">lwd =</span> <span class="dv">5</span>, <span class="at">lty =</span> <span class="dv">1</span>)</span>
<span id="cb182-18"><a href="importing-data-in-r.html#cb182-18" tabindex="-1"></a></span>
<span id="cb182-19"><a href="importing-data-in-r.html#cb182-19" tabindex="-1"></a><span class="co"># Plot forecasts of first information date</span></span>
<span id="cb182-20"><a href="importing-data-in-r.html#cb182-20" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x =</span> <span class="fu">as.yearqtr</span>(dates[<span class="dv">1</span>]) <span class="sc">+</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">4</span>, <span class="dv">9</span>) <span class="sc">/</span> <span class="dv">4</span>, </span>
<span id="cb182-21"><a href="importing-data-in-r.html#cb182-21" tabindex="-1"></a>      <span class="at">y =</span> <span class="fu">as.numeric</span>(gRGDP[gRGDP<span class="sc">$</span>date_info <span class="sc">==</span> dates[<span class="dv">1</span>], <span class="dv">2</span><span class="sc">:</span><span class="dv">15</span>]), </span>
<span id="cb182-22"><a href="importing-data-in-r.html#cb182-22" tabindex="-1"></a>      <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">col =</span> <span class="dv">2</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb182-23"><a href="importing-data-in-r.html#cb182-23" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="fu">as.yearqtr</span>(dates[<span class="dv">1</span>]), <span class="at">col =</span> <span class="dv">2</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb182-24"><a href="importing-data-in-r.html#cb182-24" tabindex="-1"></a></span>
<span id="cb182-25"><a href="importing-data-in-r.html#cb182-25" tabindex="-1"></a><span class="co"># Plot forecasts of third information date</span></span>
<span id="cb182-26"><a href="importing-data-in-r.html#cb182-26" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x =</span> <span class="fu">as.yearqtr</span>(dates[<span class="dv">3</span>]) <span class="sc">+</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">4</span>, <span class="dv">9</span>) <span class="sc">/</span> <span class="dv">4</span>, </span>
<span id="cb182-27"><a href="importing-data-in-r.html#cb182-27" tabindex="-1"></a>      <span class="at">y =</span> <span class="fu">as.numeric</span>(gRGDP[gRGDP<span class="sc">$</span>date_info <span class="sc">==</span> dates[<span class="dv">3</span>], <span class="dv">2</span><span class="sc">:</span><span class="dv">15</span>]), </span>
<span id="cb182-28"><a href="importing-data-in-r.html#cb182-28" tabindex="-1"></a>      <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">col =</span> <span class="dv">1</span>, <span class="at">lwd =</span> <span class="dv">1</span>, <span class="at">lty =</span> <span class="dv">1</span>)</span>
<span id="cb182-29"><a href="importing-data-in-r.html#cb182-29" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="fu">as.yearqtr</span>(dates[<span class="dv">3</span>]), <span class="at">col =</span> <span class="dv">1</span>, <span class="at">lwd =</span> <span class="dv">1</span>, <span class="at">lty =</span> <span class="dv">1</span>)</span>
<span id="cb182-30"><a href="importing-data-in-r.html#cb182-30" tabindex="-1"></a></span>
<span id="cb182-31"><a href="importing-data-in-r.html#cb182-31" tabindex="-1"></a><span class="co"># Add legend</span></span>
<span id="cb182-32"><a href="importing-data-in-r.html#cb182-32" tabindex="-1"></a><span class="fu">legend</span>(<span class="at">x =</span> <span class="st">&quot;bottomright&quot;</span>, <span class="at">legend =</span> <span class="fu">format</span>(dates, <span class="at">format =</span> <span class="st">&quot;%b %d, %Y&quot;</span>),</span>
<span id="cb182-33"><a href="importing-data-in-r.html#cb182-33" tabindex="-1"></a>       <span class="at">title=</span><span class="st">&quot;Information Date&quot;</span>,</span>
<span id="cb182-34"><a href="importing-data-in-r.html#cb182-34" tabindex="-1"></a>       <span class="at">col =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">5</span>, <span class="dv">1</span>), <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">1</span>), <span class="at">lwd =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">5</span>, <span class="dv">1</span>))</span></code></pre></div>
<p>In the code snippet provided, the appearance and behavior of the plot are customized using several functions and arguments:</p>
<ul>
<li><code>x = as.yearqtr(dates[2]) + seq(-4, 9) / 4</code>: This argument specifies the x-values for the line plot. <code>as.yearqtr(dates[2])</code> converts the second date in the <code>dates</code> vector into a quarterly format. <code>seq(-4, 9) / 4</code> generates a sequence of quarterly offsets, which are added to the second date to generate the x-values.</li>
<li><code>y = as.numeric(gRGDP[gRGDP$date_info == dates[2], 2:15])</code>: This argument specifies the y-values for the line plot. It selects the back-, now-, and forecasts (columns 2 through 15) from the <code>gRGDP</code> dataframe for rows where the <code>date_info</code> column equals the second date in the <code>dates</code> vector.</li>
<li><code>type = "l"</code>: This argument specifies that the plot should be a line plot.</li>
<li><code>col = 5</code>: This argument sets the color of the line plot. <code>5</code> corresponds to magenta in R’s default color palette.</li>
<li><code>lwd = 5</code>: This argument specifies the line width. The higher the value, the thicker the line.</li>
<li><code>lty = 1</code>: This argument sets the line type. <code>1</code> corresponds to a solid line.</li>
<li><code>ylim = c(-7, 5)</code>: This argument sets the y-axis limits.</li>
<li><code>xlim = as.yearqtr(dates[2]) + c(-6, 8) / 4</code>: This argument sets the x-axis limits. The limits are calculated in a similar way to the x-values, but with different offsets.</li>
<li><code>xlab = "Realization Date"</code> and <code>ylab = "%"</code>: These arguments label the x-axis and y-axis, respectively.</li>
<li><code>main = "Back-, Now-, and Forecasts of Real GDP Growth"</code>: This argument sets the main title of the plot.</li>
<li><code>abline(v = as.yearqtr(dates[2]), col = 5, lwd = 5, lty = 1)</code>: This function adds a vertical line to the plot at the second date in the <code>dates</code> vector. The color, line width, and line type of the vertical line are specified by the <code>col</code>, <code>lwd</code>, and <code>lty</code> arguments, respectively.</li>
<li><code>lines</code>: This function is used to add additional lines to the plot, corresponding the the first and third date in the <code>dates</code> vector.</li>
<li><code>legend</code>: This function adds a legend to the plot. The <code>x</code> argument specifies the position of the legend, the <code>legend</code> argument specifies the labels, and the <code>title</code> argument specifies the title of the legend. The color, line type, and line width of each label are specified by the <code>col</code>, <code>lty</code>, and <code>lwd</code> arguments, respectively.</li>
</ul>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:forecast-plot"></span>
<img src="daer_files/figure-html/forecast-plot-1.png" alt="Back-, Now-, and Forecasts of Real GDP Growth" width="80%" />
<p class="caption">
Figure 5.4: Back-, Now-, and Forecasts of Real GDP Growth
</p>
</div>
<p>The resulting plot, as shown in Figure <a href="importing-data-in-r.html#fig:forecast-plot">5.4</a>, exhibits backcasts, nowcasts, and forecasts derived at three distinct time periods:</p>
<ol style="list-style-type: decimal">
<li>The dashed red line corresponds to the backcasts, nowcasts, and forecasts made on June 18, 2008.</li>
<li>The thick magenta line represents the backcasts, nowcasts, and forecasts made on December 10, 2008.</li>
<li>The solid black line signifies the backcasts, nowcasts, and forecasts made on August 06, 2009.</li>
</ol>
<p>The vertical lines depict the three information dates.</p>
<p>This figure indicates that considerable revisions occurred between June 18 and December 10, 2008, implying that the Federal Reserve did not anticipate the Great Recession. While the revisions between December 10, 2008 and August 06, 2009 are less drastic, it’s noteworthy that there are considerable revisions in the December 10, 2008 nowcasts and backcasts. Consequently, the Federal Reserve had to operate based on incorrect information about growth in the current and preceding periods.</p>
</div>
<div id="plotting-forecast-errors" class="section level3 hasAnchor" number="5.4.5">
<h3><span class="header-section-number">5.4.5</span> Plotting Forecast Errors<a href="importing-data-in-r.html#plotting-forecast-errors" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The forecast error for a given period is computed by subtracting the forecasted value from the actual value. This error is determined using an <span class="math inline">\(h\)</span>-step ahead forecast, represented as follows:</p>
<p><span class="math display">\[
e_{t,h} = y_t - f_{t,h}
\]</span></p>
<p>In this equation, <span class="math inline">\(e_{t,h}\)</span> stands for the forecast error, <span class="math inline">\(y_t\)</span> is the actual value, <span class="math inline">\(f_{t,h}\)</span> is the forecasted value, and <span class="math inline">\(t\)</span> designates the realization date. The information date of the <span class="math inline">\(h\)</span>-step ahead forecast <span class="math inline">\(f_{t,h}\)</span> is <span class="math inline">\(t-h\)</span>, and for <span class="math inline">\(y_t\)</span> it is either <span class="math inline">\(t\)</span> or <span class="math inline">\(t+k\)</span> with <span class="math inline">\(k&gt;0\)</span> depending on whether the value is observed like asset prices or revised post realization like inflation or GDP growth.</p>
<p>It’s essential to note that the forecast error compares the same realization date with the values of two different information dates. For simplification, we assume that <span class="math inline">\(y_t=f_{t,-1}\)</span>; that is, the 1-step behind backcast is a good approximation of the actual value.</p>
<p>When utilizing the Tealbook inflation data in row format, one might infer that the forecast error is computed by subtracting <code>gPGDPB1</code> from <code>gPGDPF1</code> for each row. However, this would be incorrect as it results in <span class="math inline">\(y_{t-1} - f_{t+1,h}\)</span>, where the information date for both variables is <span class="math inline">\(t\)</span>, but the realization dates are <span class="math inline">\(t-1\)</span> and <span class="math inline">\(t+1\)</span> respectively, and thus do not match.</p>
<p>Therefore, we need to shift the backcast <code>gPGDPB1</code> one period forward, and the one-step ahead forecast <code>gPGDPF1</code> one period backward to compute the one-step ahead forecast error. However, as the realization periods are quarterly, and there are eight FOMC (Federal Open Market Committee) meetings per year, each necessitating Tealbook forecasts, we need to aggregate the information frequency to quarterly as well.</p>
<p>The R code for performing these operations and computing the forecast error is as follows:</p>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb183-1"><a href="importing-data-in-r.html#cb183-1" tabindex="-1"></a><span class="co"># Extract the GDP deflator (inflation) worksheet</span></span>
<span id="cb183-2"><a href="importing-data-in-r.html#cb183-2" tabindex="-1"></a>gPGDP <span class="ot">&lt;-</span> TB[[<span class="st">&quot;gPGDP&quot;</span>]]</span>
<span id="cb183-3"><a href="importing-data-in-r.html#cb183-3" tabindex="-1"></a></span>
<span id="cb183-4"><a href="importing-data-in-r.html#cb183-4" tabindex="-1"></a><span class="co"># Create a date column capturing the information date</span></span>
<span id="cb183-5"><a href="importing-data-in-r.html#cb183-5" tabindex="-1"></a>gPGDP<span class="sc">$</span>date_info <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(<span class="fu">as.character</span>(gPGDP<span class="sc">$</span>GBdate), </span>
<span id="cb183-6"><a href="importing-data-in-r.html#cb183-6" tabindex="-1"></a>                           <span class="at">format =</span> <span class="st">&quot;%Y%m%d&quot;</span>)</span>
<span id="cb183-7"><a href="importing-data-in-r.html#cb183-7" tabindex="-1"></a></span>
<span id="cb183-8"><a href="importing-data-in-r.html#cb183-8" tabindex="-1"></a><span class="co"># Aggregate information frequency to quarterly</span></span>
<span id="cb183-9"><a href="importing-data-in-r.html#cb183-9" tabindex="-1"></a>gPGDP<span class="sc">$</span>date_info_qtr <span class="ot">&lt;-</span> <span class="fu">as.yearqtr</span>(gPGDP<span class="sc">$</span>date_info)</span>
<span id="cb183-10"><a href="importing-data-in-r.html#cb183-10" tabindex="-1"></a>gPGDP_qtr <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(</span>
<span id="cb183-11"><a href="importing-data-in-r.html#cb183-11" tabindex="-1"></a>    <span class="at">x =</span> gPGDP, </span>
<span id="cb183-12"><a href="importing-data-in-r.html#cb183-12" tabindex="-1"></a>    <span class="at">by =</span> <span class="fu">list</span>(<span class="at">date =</span> gPGDP<span class="sc">$</span>date_info_qtr), </span>
<span id="cb183-13"><a href="importing-data-in-r.html#cb183-13" tabindex="-1"></a>    <span class="at">FUN =</span> last</span>
<span id="cb183-14"><a href="importing-data-in-r.html#cb183-14" tabindex="-1"></a>)</span>
<span id="cb183-15"><a href="importing-data-in-r.html#cb183-15" tabindex="-1"></a></span>
<span id="cb183-16"><a href="importing-data-in-r.html#cb183-16" tabindex="-1"></a><span class="co"># Lag the one-step ahead forecasts</span></span>
<span id="cb183-17"><a href="importing-data-in-r.html#cb183-17" tabindex="-1"></a>gPGDP_qtr<span class="sc">$</span>gPGDPF1_lag1 <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb183-18"><a href="importing-data-in-r.html#cb183-18" tabindex="-1"></a>    <span class="cn">NA</span>, </span>
<span id="cb183-19"><a href="importing-data-in-r.html#cb183-19" tabindex="-1"></a>    gPGDP_qtr<span class="sc">$</span>gPGDPF1[<span class="sc">-</span><span class="fu">nrow</span>(gPGDP_qtr)]</span>
<span id="cb183-20"><a href="importing-data-in-r.html#cb183-20" tabindex="-1"></a>)</span>
<span id="cb183-21"><a href="importing-data-in-r.html#cb183-21" tabindex="-1"></a></span>
<span id="cb183-22"><a href="importing-data-in-r.html#cb183-22" tabindex="-1"></a><span class="co"># Lead the one-step behind backcasts</span></span>
<span id="cb183-23"><a href="importing-data-in-r.html#cb183-23" tabindex="-1"></a>gPGDP_qtr<span class="sc">$</span>gPGDPB1_lead1 <span class="ot">&lt;-</span> <span class="fu">c</span>(gPGDP_qtr<span class="sc">$</span>gPGDPB1[<span class="sc">-</span><span class="dv">1</span>], <span class="cn">NA</span>)</span>
<span id="cb183-24"><a href="importing-data-in-r.html#cb183-24" tabindex="-1"></a></span>
<span id="cb183-25"><a href="importing-data-in-r.html#cb183-25" tabindex="-1"></a><span class="co"># Compute forecast error</span></span>
<span id="cb183-26"><a href="importing-data-in-r.html#cb183-26" tabindex="-1"></a>gPGDP_qtr<span class="sc">$</span>error_F1_B1 <span class="ot">&lt;-</span> gPGDP_qtr<span class="sc">$</span>gPGDPB1_lead1 <span class="sc">-</span> </span>
<span id="cb183-27"><a href="importing-data-in-r.html#cb183-27" tabindex="-1"></a>    gPGDP_qtr<span class="sc">$</span>gPGDPF1_lag1</span></code></pre></div>
<p>To visualize the inflation forecast errors, we use the <code>plot()</code> function as demonstrated below:</p>
<div class="sourceCode" id="cb184"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb184-1"><a href="importing-data-in-r.html#cb184-1" tabindex="-1"></a><span class="co"># Plot inflation forecasts for each realization date</span></span>
<span id="cb184-2"><a href="importing-data-in-r.html#cb184-2" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x =</span> gPGDP_qtr<span class="sc">$</span>date, <span class="at">y =</span> gPGDP_qtr<span class="sc">$</span>gPGDPF1_lag1, </span>
<span id="cb184-3"><a href="importing-data-in-r.html#cb184-3" tabindex="-1"></a>     <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">col =</span> <span class="dv">5</span>, <span class="at">lty =</span> <span class="dv">1</span>, <span class="at">lwd =</span> <span class="dv">3</span>, </span>
<span id="cb184-4"><a href="importing-data-in-r.html#cb184-4" tabindex="-1"></a>     <span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="dv">15</span>),</span>
<span id="cb184-5"><a href="importing-data-in-r.html#cb184-5" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Realization Date&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;%&quot;</span>, </span>
<span id="cb184-6"><a href="importing-data-in-r.html#cb184-6" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Forecast Error of Inflation&quot;</span>)</span>
<span id="cb184-7"><a href="importing-data-in-r.html#cb184-7" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="dv">3</span>)</span>
<span id="cb184-8"><a href="importing-data-in-r.html#cb184-8" tabindex="-1"></a></span>
<span id="cb184-9"><a href="importing-data-in-r.html#cb184-9" tabindex="-1"></a><span class="co"># Plot inflation backcasts for each realization date</span></span>
<span id="cb184-10"><a href="importing-data-in-r.html#cb184-10" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x =</span> gPGDP_qtr<span class="sc">$</span>date, <span class="at">y =</span> gPGDP_qtr<span class="sc">$</span>gPGDPB1_lead1, </span>
<span id="cb184-11"><a href="importing-data-in-r.html#cb184-11" tabindex="-1"></a>      <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">col =</span> <span class="dv">1</span>, <span class="at">lty =</span> <span class="dv">1</span>, <span class="at">lwd =</span> <span class="dv">1</span>)</span>
<span id="cb184-12"><a href="importing-data-in-r.html#cb184-12" tabindex="-1"></a></span>
<span id="cb184-13"><a href="importing-data-in-r.html#cb184-13" tabindex="-1"></a><span class="co"># Plot forecast error for each realization date</span></span>
<span id="cb184-14"><a href="importing-data-in-r.html#cb184-14" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x =</span> gPGDP_qtr<span class="sc">$</span>date, <span class="at">y =</span> gPGDP_qtr<span class="sc">$</span>error_F1_B1, </span>
<span id="cb184-15"><a href="importing-data-in-r.html#cb184-15" tabindex="-1"></a>      <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">col =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">1</span>, <span class="at">lwd =</span> <span class="fl">1.5</span>)</span>
<span id="cb184-16"><a href="importing-data-in-r.html#cb184-16" tabindex="-1"></a></span>
<span id="cb184-17"><a href="importing-data-in-r.html#cb184-17" tabindex="-1"></a><span class="co"># Add legend</span></span>
<span id="cb184-18"><a href="importing-data-in-r.html#cb184-18" tabindex="-1"></a><span class="fu">legend</span>(<span class="at">x =</span> <span class="st">&quot;topright&quot;</span>, </span>
<span id="cb184-19"><a href="importing-data-in-r.html#cb184-19" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">&quot;Forecasted Value&quot;</span>, </span>
<span id="cb184-20"><a href="importing-data-in-r.html#cb184-20" tabindex="-1"></a>                  <span class="st">&quot;Actual Value (Backcast)&quot;</span>, </span>
<span id="cb184-21"><a href="importing-data-in-r.html#cb184-21" tabindex="-1"></a>                  <span class="st">&quot;Forecast Error&quot;</span>),</span>
<span id="cb184-22"><a href="importing-data-in-r.html#cb184-22" tabindex="-1"></a>       <span class="at">col =</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">1</span>, <span class="dv">2</span>), <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>), </span>
<span id="cb184-23"><a href="importing-data-in-r.html#cb184-23" tabindex="-1"></a>       <span class="at">lwd =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">1</span>, <span class="fl">1.5</span>))</span></code></pre></div>
<p>The customization of the plot is achieved using a variety of parameters, as discussed earlier.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:forecast-error-plot"></span>
<img src="daer_files/figure-html/forecast-error-plot-1.png" alt="Forecast Error of Inflation" width="80%" />
<p class="caption">
Figure 5.5: Forecast Error of Inflation
</p>
</div>
<p>The resulting plot, shown in Figure <a href="importing-data-in-r.html#fig:forecast-error-plot">5.5</a>, showcases the one-quarter ahead forecast error of inflation (GDP deflator) since 1967. A notable observation is the decrease in the forecast error variance throughout the “Great Moderation” period, which spanned from the mid-1980s to 2007.</p>
<p>The term “Great Moderation” was coined by economists to describe the substantial reduction in the volatility of business cycle fluctuations, which resulted in a more stable economic environment. Multiple factors contributed to this trend. Technological advancements, structural changes, improved inventory management, financial innovation, and, crucially, improved monetary policy, are all credited for this period of economic stability.</p>
<p>Monetary policies became more proactive and preemptive during this period, largely due to a better understanding of the economy and advances in economic modeling. These models, equipped with improved data, allowed for more accurate forecasts and enhanced decision-making capabilities. Consequently, policy actions were often executed before economic disruptions could materialize, thus moderating the volatility of the business cycle.</p>
<p>It is worth noting that the forecast error tends to hover around zero. If the forecast error were consistently smaller than zero, one could simply lower the forecasted value until the forecast error reaches zero, on average, consequently improving the accuracy of the forecasts. Thus, in circumstances where the objective is to minimize forecast error, it is reasonable to expect that the forecast error will average out to zero over time.</p>
<p>The following calculations are in line with the description provided above:</p>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb185-1"><a href="importing-data-in-r.html#cb185-1" tabindex="-1"></a><span class="co"># Compute mean of forecast error</span></span>
<span id="cb185-2"><a href="importing-data-in-r.html#cb185-2" tabindex="-1"></a><span class="fu">mean</span>(gPGDP_qtr<span class="sc">$</span>error_F1_B1, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 0.07871287</code></pre>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb187-1"><a href="importing-data-in-r.html#cb187-1" tabindex="-1"></a><span class="co"># Compute volatility of forecast error (FE)</span></span>
<span id="cb187-2"><a href="importing-data-in-r.html#cb187-2" tabindex="-1"></a><span class="fu">sd</span>(gPGDP_qtr<span class="sc">$</span>error_F1_B1, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 1.237391</code></pre>
<div class="sourceCode" id="cb189"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb189-1"><a href="importing-data-in-r.html#cb189-1" tabindex="-1"></a><span class="co"># Compute volatility of FE before Great Moderation</span></span>
<span id="cb189-2"><a href="importing-data-in-r.html#cb189-2" tabindex="-1"></a><span class="fu">sd</span>(gPGDP_qtr<span class="sc">$</span>error_F1_B1[gPGDP_qtr<span class="sc">$</span>date <span class="sc">&lt;=</span> <span class="fu">as.yearqtr</span>(<span class="st">&quot;1985-01-01&quot;</span>)], </span>
<span id="cb189-3"><a href="importing-data-in-r.html#cb189-3" tabindex="-1"></a>   <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 1.728324</code></pre>
<div class="sourceCode" id="cb191"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb191-1"><a href="importing-data-in-r.html#cb191-1" tabindex="-1"></a><span class="co"># Compute volatility of FE at &amp; after Great Moderation</span></span>
<span id="cb191-2"><a href="importing-data-in-r.html#cb191-2" tabindex="-1"></a><span class="fu">sd</span>(gPGDP_qtr<span class="sc">$</span>error_F1_B1[gPGDP_qtr<span class="sc">$</span>date <span class="sc">&gt;</span> <span class="fu">as.yearqtr</span>(<span class="st">&quot;1985-01-01&quot;</span>)], </span>
<span id="cb191-3"><a href="importing-data-in-r.html#cb191-3" tabindex="-1"></a>   <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 0.8499342</code></pre>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="r-data-types-and-structures.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="downloading-data-in-r.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": false,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
