<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 Getting Started | Module 1: Introduction to RStudio</title>
  <meta name="description" content="This is Module 1 of ECO 4300." />
  <meta name="generator" content="bookdown 0.34 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 Getting Started | Module 1: Introduction to RStudio" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is Module 1 of ECO 4300." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 Getting Started | Module 1: Introduction to RStudio" />
  
  <meta name="twitter:description" content="This is Module 1 of ECO 4300." />
  

<meta name="author" content="Julian F. Ludwig" />


<meta name="date" content="2023-07-01" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="software-installation.html"/>
<link rel="next" href="datacamp.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Module 1: Introduction to R, RStudio, and R Markdown</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Overview</a></li>
<li class="chapter" data-level="1" data-path="software-overview.html"><a href="software-overview.html"><i class="fa fa-check"></i><b>1</b> Software Overview</a></li>
<li class="chapter" data-level="2" data-path="software-installation.html"><a href="software-installation.html"><i class="fa fa-check"></i><b>2</b> Software Installation</a>
<ul>
<li class="chapter" data-level="2.1" data-path="software-installation.html"><a href="software-installation.html#install-r"><i class="fa fa-check"></i><b>2.1</b> Install R</a></li>
<li class="chapter" data-level="2.2" data-path="software-installation.html"><a href="software-installation.html#install-rstudio"><i class="fa fa-check"></i><b>2.2</b> Install RStudio</a></li>
<li class="chapter" data-level="2.3" data-path="software-installation.html"><a href="software-installation.html#install-r-markdown"><i class="fa fa-check"></i><b>2.3</b> Install R Markdown</a></li>
<li class="chapter" data-level="2.4" data-path="software-installation.html"><a href="software-installation.html#install-latex"><i class="fa fa-check"></i><b>2.4</b> Install LaTeX</a></li>
<li class="chapter" data-level="2.5" data-path="software-installation.html"><a href="software-installation.html#install-r-packages"><i class="fa fa-check"></i><b>2.5</b> Install R Packages</a></li>
<li class="chapter" data-level="2.6" data-path="software-installation.html"><a href="software-installation.html#step-test"><i class="fa fa-check"></i><b>2.6</b> 18-Step Test</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="getting-started.html"><a href="getting-started.html"><i class="fa fa-check"></i><b>3</b> Getting Started</a>
<ul>
<li class="chapter" data-level="3.1" data-path="getting-started.html"><a href="getting-started.html#rstudio-interface"><i class="fa fa-check"></i><b>3.1</b> RStudio Interface</a></li>
<li class="chapter" data-level="3.2" data-path="getting-started.html"><a href="getting-started.html#r-data-types-and-structures"><i class="fa fa-check"></i><b>3.2</b> R Data Types and Structures</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="getting-started.html"><a href="getting-started.html#scalar"><i class="fa fa-check"></i><b>3.2.1</b> Scalar</a></li>
<li class="chapter" data-level="3.2.2" data-path="getting-started.html"><a href="getting-started.html#vector"><i class="fa fa-check"></i><b>3.2.2</b> Vector</a></li>
<li class="chapter" data-level="3.2.3" data-path="getting-started.html"><a href="getting-started.html#matrix-matrix"><i class="fa fa-check"></i><b>3.2.3</b> Matrix (<code>matrix</code>)</a></li>
<li class="chapter" data-level="3.2.4" data-path="getting-started.html"><a href="getting-started.html#list-list"><i class="fa fa-check"></i><b>3.2.4</b> List (<code>list</code>)</a></li>
<li class="chapter" data-level="3.2.5" data-path="getting-started.html"><a href="getting-started.html#data-frame-data.frame"><i class="fa fa-check"></i><b>3.2.5</b> Data Frame (<code>data.frame</code>)</a></li>
<li class="chapter" data-level="3.2.6" data-path="getting-started.html"><a href="getting-started.html#tibble"><i class="fa fa-check"></i><b>3.2.6</b> Tibble (<code>tbl_df</code>)</a></li>
<li class="chapter" data-level="3.2.7" data-path="getting-started.html"><a href="getting-started.html#data-table-data.table"><i class="fa fa-check"></i><b>3.2.7</b> Data Table (<code>data.table</code>)</a></li>
<li class="chapter" data-level="3.2.8" data-path="getting-started.html"><a href="getting-started.html#extensible-time-series-xts"><i class="fa fa-check"></i><b>3.2.8</b> Extensible Time Series (<code>xts</code>)</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="getting-started.html"><a href="getting-started.html#importing-data-in-r"><i class="fa fa-check"></i><b>3.3</b> Importing Data in R</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="getting-started.html"><a href="getting-started.html#working-directory"><i class="fa fa-check"></i><b>3.3.1</b> Working Directory</a></li>
<li class="chapter" data-level="3.3.2" data-path="getting-started.html"><a href="getting-started.html#csv-comma-separated-values"><i class="fa fa-check"></i><b>3.3.2</b> CSV (Comma Separated Values)</a></li>
<li class="chapter" data-level="3.3.3" data-path="getting-started.html"><a href="getting-started.html#tsv-tab-separated-values"><i class="fa fa-check"></i><b>3.3.3</b> TSV (Tab Separated Values)</a></li>
<li class="chapter" data-level="3.3.4" data-path="getting-started.html"><a href="getting-started.html#excel-file"><i class="fa fa-check"></i><b>3.3.4</b> Excel File</a></li>
<li class="chapter" data-level="3.3.5" data-path="getting-started.html"><a href="getting-started.html#saving-data"><i class="fa fa-check"></i><b>3.3.5</b> Saving Data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="datacamp.html"><a href="datacamp.html"><i class="fa fa-check"></i><b>4</b> DataCamp</a></li>
<li class="chapter" data-level="5" data-path="assignment.html"><a href="assignment.html"><i class="fa fa-check"></i><b>5</b> Assignment</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Module 1: Introduction to RStudio</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="getting-started" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">Chapter 3</span> Getting Started<a href="getting-started.html#getting-started" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>R is a programming language and free software environment for statistical computing and graphics supported by the R Foundation for Statistical Computing.</p>
<div id="rstudio-interface" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> RStudio Interface<a href="getting-started.html#rstudio-interface" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>After launching RStudio on your computer, navigate to the menu bar and select “File,” then choose “New File,” and finally click on “R Script.” Alternatively, you can use the keyboard shortcut Ctrl+Shift+N (Windows/Linux) or Cmd+Shift+N (Mac) to create a new R script directly.</p>
<div class="figure"><span style="display:block;" id="fig:rstudio-rscript-code"></span>
<img src="files/icons-rstudio/rstudio-rscript-code.png" alt="RStudio Interface"  />
<p class="caption">
Figure 3.1: RStudio Interface
</p>
</div>
<p>Once you have opened a new R script, you will notice that RStudio consists of four main sections:</p>
<ol style="list-style-type: decimal">
<li><p><strong>Source</strong> (top-left): This section is where you write your R scripts. Also known as <strong>do-files</strong>, R scripts are files that contain a sequence of commands which can be executed either wholly or partially. To run a single line in your script, click on that line with your cursor and press the <img src="files/icons-rstudio/run.png" alt="run" /> button. However, to streamline your workflow, I recommend using the keyboard shortcut Ctrl+Enter (Windows/Linux) or Cmd+Enter (Mac) to run the line without reaching for the mouse. If you want to execute only a specific portion of a line, select that part and then press Ctrl+Enter or Cmd+Enter. To run all the commands in your R script, use the <img src="files/icons-rstudio/source.png" alt="source" /> button or the keyboard shortcut Ctrl+Shift+Enter (Windows/Linux) or Cmd+Shift+Enter (Mac).</p></li>
<li><p><strong>Console</strong> (bottom-left): Located below the Source section, the Console is where R executes your commands. You can also directly type commands into the Console and see their output immediately. However, it is advisable to write commands in the R Script instead of the Console. By doing so, you can save the commands for future reference, enabling you to reproduce your results at a later time.</p></li>
<li><p><strong>Environment</strong> (top-right): In the upper-right section, the Environment tab displays the current objects stored in memory, providing an overview of your variables, functions, and data frames. To create a variable, you can use the assignment operator <code>&lt;-</code> (reversed arrow). Once a variable is created and assigned a numeric value, it can be utilized in arithmetic operations. For example:</p></li>
</ol>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="getting-started.html#cb17-1" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="dv">60</span></span>
<span id="cb17-2"><a href="getting-started.html#cb17-2" tabindex="-1"></a>a <span class="sc">+</span> <span class="dv">20</span></span></code></pre></div>
<pre><code>## [1] 80</code></pre>
<ol start="4" style="list-style-type: decimal">
<li><strong>Files/Plots/Packages/Help/Viewer</strong> (bottom-right): The bottom-right panel contains multiple tabs:
<ul>
<li>Files: displays your files and folders</li>
<li>Plots: displays your graphs</li>
<li>Packages: lets you manage your R packages</li>
<li>Help: provides help documentation</li>
<li>Viewer: lets you view local web content</li>
</ul></li>
</ol>
<p>These four main sections of RStudio provide a comprehensive environment for writing, executing, and managing your R code efficiently.</p>
<div id="r-scripts" class="section level4 unnumbered hasAnchor">
<h4>R Scripts<a href="getting-started.html#r-scripts" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>An R script is a text file that contains your R code. You can execute parts of the script by selecting a subset of commands and pressing Ctrl+Enter or Cmd+Enter, or run the entire script by pressing Ctrl+Shift+Enter.</p>
<p>Any text written after a hashtag (<code>#</code>) in an R Script is considered comments and is not executed as code. Comments are valuable for providing explanations or annotations for your commands, enhancing the readability and comprehensibility of your code.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="getting-started.html#cb19-1" tabindex="-1"></a><span class="co"># This is a comment in an R script</span></span>
<span id="cb19-2"><a href="getting-started.html#cb19-2" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">10</span>  <span class="co"># Assign the value 10 to x</span></span>
<span id="cb19-3"><a href="getting-started.html#cb19-3" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="dv">20</span>  <span class="co"># Assign the value 20 to y</span></span>
<span id="cb19-4"><a href="getting-started.html#cb19-4" tabindex="-1"></a>z <span class="ot">&lt;-</span> x <span class="sc">+</span> y  <span class="co"># Add x and y and assign the result to z</span></span>
<span id="cb19-5"><a href="getting-started.html#cb19-5" tabindex="-1"></a><span class="fu">print</span>(z)  <span class="co"># Print the value of z</span></span></code></pre></div>
<pre><code>## [1] 30</code></pre>
<p>The output displayed after two hashtags (<code>##</code>) in the example above: <code>## [1] 30</code>, is not part of the actual R Script. Instead, it represents a line you would observe in your console when running the R Script. It showcases the result or value of the variable <code>z</code> in this case.</p>
<p>To facilitate working with lengthy R scripts, it is recommended to use a separate window. You can open a separate window by selecting <img src="files/icons-rstudio/show-in-new-window.png" alt="show-in-new-window" /> in the top-left corner.</p>
<div class="figure"><span style="display:block;" id="fig:rstudio-rscript-separate"></span>
<img src="files/icons-rstudio/rstudio-rscript-separate.png" alt="RStudio Interface with Separate R Script Window"  />
<p class="caption">
Figure 3.2: RStudio Interface with Separate R Script Window
</p>
</div>
<p>When the R Script is in a separate window, you can easily switch between the R Script window and the Console/Environment/Plot Window by pressing Ctrl+Tab or Cmd+Tab. This allows for convenient navigation between different RStudio windows.</p>
</div>
</div>
<div id="r-data-types-and-structures" class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> R Data Types and Structures<a href="getting-started.html#r-data-types-and-structures" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The R language supports a broad array of operations such as mathematical calculations, logical analyses, and text manipulation. However, the applicability of a function to a variable depends on the variable’s data type. For instance, an arithmetic function to add two variables won’t work if the variables store text.</p>
<p>R supports various data types, including numeric (<code>x &lt;- 15</code>), character (<code>x &lt;- "Hello!"</code>), and logical (<code>x &lt;- TRUE</code> or <code>x &lt;- FALSE</code>). In addition to single values (scalars), R allows variables to hold collections of numbers or strings using vectors, matrices, lists, or data frames. Advanced data structures such as tibbles, data tables, and <code>xts</code> objects provide additional features beyond traditional data frames.</p>
<p>In this section, we will explore the following data types:</p>
<ol style="list-style-type: decimal">
<li><strong>Scalar</strong>: A single data element, such as a number or a character string.</li>
<li><strong>Vector</strong>: A one-dimensional array that contains elements of the same type.</li>
<li><strong>Matrix</strong> (<code>matrix</code>): A two-dimensional array with elements of the same type.</li>
<li><strong>List</strong> (<code>list</code>): A one-dimensional array capable of storing various data types.</li>
<li><strong>Data Frame</strong> (<code>data.frame</code>): A two-dimensional array that can accommodate columns of different types.</li>
<li><strong>Tibble</strong> (<code>tibble</code>): An enhanced version of data frames, offering user-friendly features.</li>
<li><strong>Data Table</strong> (<code>data.table</code>): An optimized data frame extension designed for speed and handling large datasets.</li>
<li><strong>Extensible Time Series</strong> (<code>xts</code>): A time-indexed data frame specifically designed for time series data.</li>
</ol>
<p>Understanding the data type of variables is crucial because it determines the operations and functions that can be applied to them.</p>
<p>It’s worth noting that R provides so-called <strong>wrapper functions</strong>, which are functions that have the same name but perform different actions depending on the data object. These wrapper functions adapt their behavior based on the input data type, allowing for more flexible and intuitive programming. For example, the <code>summary()</code> function in R is a wrapper function. When applied to a numeric vector, it provides statistical summaries such as mean, median, and quartiles. However, when applied to a data frame, it gives a summary of each variable, including the minimum, maximum, and quartiles for numerical variables, as well as counts and levels for categorical variables.</p>
<div id="scalar" class="section level3 hasAnchor" number="3.2.1">
<h3><span class="header-section-number">3.2.1</span> Scalar<a href="getting-started.html#scalar" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Scalars in R are variables holding single objects. You can determine an object’s type by applying the <code>class()</code> function to the variable.</p>
<div id="numbers-characters-and-logical-values" class="section level4 unnumbered hasAnchor">
<h4>Numbers, Characters, and Logical Values<a href="getting-started.html#numbers-characters-and-logical-values" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="getting-started.html#cb21-1" tabindex="-1"></a><span class="co"># Numeric (a.k.a. Double)</span></span>
<span id="cb21-2"><a href="getting-started.html#cb21-2" tabindex="-1"></a>w <span class="ot">&lt;-</span> <span class="fl">5.5</span>  <span class="co"># w is a decimal number.</span></span>
<span id="cb21-3"><a href="getting-started.html#cb21-3" tabindex="-1"></a><span class="fu">class</span>(w)  <span class="co"># Returns &quot;numeric&quot;.</span></span>
<span id="cb21-4"><a href="getting-started.html#cb21-4" tabindex="-1"></a></span>
<span id="cb21-5"><a href="getting-started.html#cb21-5" tabindex="-1"></a><span class="co"># Integer</span></span>
<span id="cb21-6"><a href="getting-started.html#cb21-6" tabindex="-1"></a>x <span class="ot">&lt;-</span> 10L  <span class="co"># The L tells R to store x as an integer instead of a decimal number.</span></span>
<span id="cb21-7"><a href="getting-started.html#cb21-7" tabindex="-1"></a><span class="fu">class</span>(x)  <span class="co"># Returns &quot;integer&quot;.</span></span>
<span id="cb21-8"><a href="getting-started.html#cb21-8" tabindex="-1"></a></span>
<span id="cb21-9"><a href="getting-started.html#cb21-9" tabindex="-1"></a><span class="co"># Complex</span></span>
<span id="cb21-10"><a href="getting-started.html#cb21-10" tabindex="-1"></a>u <span class="ot">&lt;-</span> <span class="dv">3</span> <span class="sc">+</span> 4i <span class="co"># u is a complex number, where 3 is real and 4 is imaginary.</span></span>
<span id="cb21-11"><a href="getting-started.html#cb21-11" tabindex="-1"></a><span class="fu">class</span>(u)  <span class="co"># Returns &quot;complex&quot;.</span></span>
<span id="cb21-12"><a href="getting-started.html#cb21-12" tabindex="-1"></a></span>
<span id="cb21-13"><a href="getting-started.html#cb21-13" tabindex="-1"></a><span class="co"># Character</span></span>
<span id="cb21-14"><a href="getting-started.html#cb21-14" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="st">&quot;Hello, World!&quot;</span>  <span class="co"># y is a character string.</span></span>
<span id="cb21-15"><a href="getting-started.html#cb21-15" tabindex="-1"></a><span class="fu">class</span>(y)  <span class="co"># Returns &quot;character&quot;.</span></span>
<span id="cb21-16"><a href="getting-started.html#cb21-16" tabindex="-1"></a></span>
<span id="cb21-17"><a href="getting-started.html#cb21-17" tabindex="-1"></a><span class="co"># Logical</span></span>
<span id="cb21-18"><a href="getting-started.html#cb21-18" tabindex="-1"></a>z <span class="ot">&lt;-</span> <span class="cn">TRUE</span>  <span class="co"># z is a logical value.</span></span>
<span id="cb21-19"><a href="getting-started.html#cb21-19" tabindex="-1"></a><span class="fu">class</span>(z)  <span class="co"># Returns &quot;logical&quot;.</span></span></code></pre></div>
<pre><code>## [1] &quot;numeric&quot;
## [1] &quot;integer&quot;
## [1] &quot;complex&quot;
## [1] &quot;character&quot;
## [1] &quot;logical&quot;</code></pre>
<p>An object’s type dictates which functions can be applied. For example, mathematical functions are applicable to numbers but not characters:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="getting-started.html#cb23-1" tabindex="-1"></a><span class="co"># Mathematical operations</span></span>
<span id="cb23-2"><a href="getting-started.html#cb23-2" tabindex="-1"></a><span class="dv">2</span> <span class="sc">+</span> <span class="dv">2</span>  <span class="co"># Results in 4.</span></span>
<span id="cb23-3"><a href="getting-started.html#cb23-3" tabindex="-1"></a><span class="dv">3</span> <span class="sc">*</span> <span class="dv">5</span>  <span class="co"># Results in 15.</span></span>
<span id="cb23-4"><a href="getting-started.html#cb23-4" tabindex="-1"></a>(<span class="dv">1</span> <span class="sc">+</span> <span class="dv">2</span>) <span class="sc">*</span> <span class="dv">3</span>  <span class="co"># Results in 9 (parentheses take precedence).</span></span>
<span id="cb23-5"><a href="getting-started.html#cb23-5" tabindex="-1"></a></span>
<span id="cb23-6"><a href="getting-started.html#cb23-6" tabindex="-1"></a><span class="co"># Logical operations</span></span>
<span id="cb23-7"><a href="getting-started.html#cb23-7" tabindex="-1"></a><span class="cn">TRUE</span> <span class="sc">&amp;</span> <span class="cn">FALSE</span>  <span class="co"># Results in FALSE (logical AND).</span></span>
<span id="cb23-8"><a href="getting-started.html#cb23-8" tabindex="-1"></a><span class="cn">TRUE</span> <span class="sc">|</span> <span class="cn">FALSE</span>  <span class="co"># Results in TRUE (logical OR).</span></span>
<span id="cb23-9"><a href="getting-started.html#cb23-9" tabindex="-1"></a></span>
<span id="cb23-10"><a href="getting-started.html#cb23-10" tabindex="-1"></a><span class="co"># String operations</span></span>
<span id="cb23-11"><a href="getting-started.html#cb23-11" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">&quot;Hello&quot;</span>, <span class="st">&quot;World!&quot;</span>)  <span class="co"># Concatenates strings, results in &quot;Hello World!&quot;.</span></span>
<span id="cb23-12"><a href="getting-started.html#cb23-12" tabindex="-1"></a><span class="fu">nchar</span>(<span class="st">&quot;Hello&quot;</span>)  <span class="co"># Counts characters in a string, results in 5.</span></span></code></pre></div>
<pre><code>## [1] 4
## [1] 15
## [1] 9
## [1] FALSE
## [1] TRUE
## [1] &quot;Hello World!&quot;
## [1] 5</code></pre>
</div>
<div id="dates-and-times" class="section level4 unnumbered hasAnchor">
<h4>Dates and Times<a href="getting-started.html#dates-and-times" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>In this course, we also deal with data types specifically designed for storing date and time information:</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="getting-started.html#cb25-1" tabindex="-1"></a><span class="co"># Date</span></span>
<span id="cb25-2"><a href="getting-started.html#cb25-2" tabindex="-1"></a>v <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(<span class="st">&quot;2023-06-30&quot;</span>)  <span class="co"># v is a Date.</span></span>
<span id="cb25-3"><a href="getting-started.html#cb25-3" tabindex="-1"></a><span class="co"># The default input format is %Y-%m-%d, where</span></span>
<span id="cb25-4"><a href="getting-started.html#cb25-4" tabindex="-1"></a><span class="co"># - %Y is year in 4 digits,</span></span>
<span id="cb25-5"><a href="getting-started.html#cb25-5" tabindex="-1"></a><span class="co"># - %m is month with 2 digits, and </span></span>
<span id="cb25-6"><a href="getting-started.html#cb25-6" tabindex="-1"></a><span class="co"># - %d is day with 2 digits.</span></span>
<span id="cb25-7"><a href="getting-started.html#cb25-7" tabindex="-1"></a><span class="fu">class</span>(v)  <span class="co"># Returns &quot;Date&quot;.</span></span></code></pre></div>
<pre><code>## [1] &quot;Date&quot;</code></pre>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="getting-started.html#cb27-1" tabindex="-1"></a><span class="co"># POSIXct (Time)</span></span>
<span id="cb27-2"><a href="getting-started.html#cb27-2" tabindex="-1"></a>t <span class="ot">&lt;-</span> <span class="fu">as.POSIXct</span>(<span class="st">&quot;2023-06-30 18:47:10&quot;</span>, <span class="at">tz =</span> <span class="st">&quot;CDT&quot;</span>)  <span class="co"># t is a POSIXct.</span></span></code></pre></div>
<pre><code>## Warning in strptime(xx, f, tz = tz): unknown timezone &#39;CDT&#39;</code></pre>
<pre><code>## Warning in as.POSIXct.POSIXlt(x): unknown timezone &#39;CDT&#39;</code></pre>
<pre><code>## Warning in strptime(x, f, tz = tz): unknown timezone &#39;CDT&#39;</code></pre>
<pre><code>## Warning in as.POSIXct.POSIXlt(as.POSIXlt(x, tz, ...), tz, ...): unknown
## timezone &#39;CDT&#39;</code></pre>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="getting-started.html#cb32-1" tabindex="-1"></a><span class="co"># The default input format is %Y-%m-%d %H:%M:%S, where</span></span>
<span id="cb32-2"><a href="getting-started.html#cb32-2" tabindex="-1"></a><span class="co"># - %H is hour out of 24,</span></span>
<span id="cb32-3"><a href="getting-started.html#cb32-3" tabindex="-1"></a><span class="co"># - %M is minute out of 60, and</span></span>
<span id="cb32-4"><a href="getting-started.html#cb32-4" tabindex="-1"></a><span class="co"># - %S is second out of 60.</span></span>
<span id="cb32-5"><a href="getting-started.html#cb32-5" tabindex="-1"></a><span class="co"># The tz input is the time zone, where CDT = Central Daylight Time.</span></span>
<span id="cb32-6"><a href="getting-started.html#cb32-6" tabindex="-1"></a><span class="fu">class</span>(t)  <span class="co"># Returns &quot;POSIXct&quot;.</span></span></code></pre></div>
<pre><code>## [1] &quot;POSIXct&quot; &quot;POSIXt&quot;</code></pre>
<p>The default input format, <code>%Y-%m-%d</code> or <code>%Y-%m-%d %H:%M:%S</code>, can be changed by specifying a format input. The output format can be adjusted by applying the <code>format()</code> function to the object:</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="getting-started.html#cb34-1" tabindex="-1"></a><span class="co"># Date with custom input format:</span></span>
<span id="cb34-2"><a href="getting-started.html#cb34-2" tabindex="-1"></a>v <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(<span class="st">&quot;April 6 -- 23&quot;</span>, <span class="at">format =</span> <span class="st">&quot;%B %d -- %y&quot;</span>)</span>
<span id="cb34-3"><a href="getting-started.html#cb34-3" tabindex="-1"></a>v  <span class="co"># Returns default output format: %Y-%m-%d.</span></span></code></pre></div>
<pre><code>## [1] &quot;2023-04-06&quot;</code></pre>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="getting-started.html#cb36-1" tabindex="-1"></a><span class="fu">format</span>(v, <span class="at">format =</span> <span class="st">&quot;%B %d, %Y&quot;</span>)  <span class="co"># Returns a custom output format: &quot;%B %d, %Y&quot;.</span></span></code></pre></div>
<pre><code>## [1] &quot;April 06, 2023&quot;</code></pre>
<p>The syntax for different date formats can be found by typing <code>?strptime</code> in the R console. Some of the most commonly used formats are outlined in the table below:</p>
<table>
<colgroup>
<col width="12%" />
<col width="71%" />
<col width="15%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Specification</th>
<th align="left">Description</th>
<th align="left">Example</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">%a</td>
<td align="left">Abbreviated weekday</td>
<td align="left">Sun, Thu</td>
</tr>
<tr class="even">
<td align="left">%A</td>
<td align="left">Full weekday</td>
<td align="left">Sunday, Thursday</td>
</tr>
<tr class="odd">
<td align="left">%b or %h</td>
<td align="left">Abbreviated month</td>
<td align="left">May, Jul</td>
</tr>
<tr class="even">
<td align="left">%B</td>
<td align="left">Full month</td>
<td align="left">May, July</td>
</tr>
<tr class="odd">
<td align="left">%d</td>
<td align="left">Day of the month, 0-31</td>
<td align="left">27, 07</td>
</tr>
<tr class="even">
<td align="left">%j</td>
<td align="left">Day of the year, 001-366</td>
<td align="left">148, 188</td>
</tr>
<tr class="odd">
<td align="left">%m</td>
<td align="left">Month, 01-12</td>
<td align="left">05, 07</td>
</tr>
<tr class="even">
<td align="left">%U</td>
<td align="left">Week, 01-53, with Sunday as first day of the week</td>
<td align="left">22, 27</td>
</tr>
<tr class="odd">
<td align="left">%w</td>
<td align="left">Weekday, 0-6, Sunday is 0</td>
<td align="left">0, 4</td>
</tr>
<tr class="even">
<td align="left">%W</td>
<td align="left">Week, 00-53, with Monday as first day of the week</td>
<td align="left">21, 27</td>
</tr>
<tr class="odd">
<td align="left">%x</td>
<td align="left">Date, locale-specific</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">%y</td>
<td align="left">Year without century, 00-99</td>
<td align="left">84, 05</td>
</tr>
<tr class="odd">
<td align="left">%Y</td>
<td align="left">Year with century, on input: 00 to 68 prefixed by 20, 69 to 99 prefixed by 19</td>
<td align="left">1984, 2005</td>
</tr>
<tr class="even">
<td align="left">%C</td>
<td align="left">Century</td>
<td align="left">19, 20</td>
</tr>
<tr class="odd">
<td align="left">%D</td>
<td align="left">Date formatted %m/%d/%y</td>
<td align="left">5/27/84</td>
</tr>
<tr class="even">
<td align="left">%u</td>
<td align="left">Weekday, 1-7, Monday is 1</td>
<td align="left">7, 4</td>
</tr>
<tr class="odd">
<td align="left">%n</td>
<td align="left">Newline on output or arbitrary whitespace on input</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">%t</td>
<td align="left">Tab on output or arbitrary whitespace on input</td>
<td align="left"></td>
</tr>
</tbody>
</table>
<p>Here are some example operations for <code>Date</code> objects:</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="getting-started.html#cb38-1" tabindex="-1"></a><span class="co"># Date Operations</span></span>
<span id="cb38-2"><a href="getting-started.html#cb38-2" tabindex="-1"></a>date1 <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(<span class="st">&quot;2023-06-30&quot;</span>)</span>
<span id="cb38-3"><a href="getting-started.html#cb38-3" tabindex="-1"></a>date2 <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(<span class="st">&quot;2023-01-01&quot;</span>)</span>
<span id="cb38-4"><a href="getting-started.html#cb38-4" tabindex="-1"></a></span>
<span id="cb38-5"><a href="getting-started.html#cb38-5" tabindex="-1"></a><span class="co"># Subtract dates to get the number of days between</span></span>
<span id="cb38-6"><a href="getting-started.html#cb38-6" tabindex="-1"></a>days_between <span class="ot">&lt;-</span> date1 <span class="sc">-</span> date2</span>
<span id="cb38-7"><a href="getting-started.html#cb38-7" tabindex="-1"></a>days_between</span></code></pre></div>
<pre><code>## Time difference of 180 days</code></pre>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="getting-started.html#cb40-1" tabindex="-1"></a><span class="co"># Add days to a date</span></span>
<span id="cb40-2"><a href="getting-started.html#cb40-2" tabindex="-1"></a>date_in_future <span class="ot">&lt;-</span> date1 <span class="sc">+</span> <span class="dv">30</span></span>
<span id="cb40-3"><a href="getting-started.html#cb40-3" tabindex="-1"></a>date_in_future</span></code></pre></div>
<pre><code>## [1] &quot;2023-07-30&quot;</code></pre>
</div>
</div>
<div id="vector" class="section level3 hasAnchor" number="3.2.2">
<h3><span class="header-section-number">3.2.2</span> Vector<a href="getting-started.html#vector" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In R, a vector is a homogeneous sequence of elements, meaning they must all be of the same basic type. As such, a vector can hold multiple numbers, but it cannot mix types, such as having both numbers and words. The function <code>c()</code> (for combine) can be used to create a vector:</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="getting-started.html#cb42-1" tabindex="-1"></a><span class="co"># Numeric vector</span></span>
<span id="cb42-2"><a href="getting-started.html#cb42-2" tabindex="-1"></a>numeric_vector <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>)</span>
<span id="cb42-3"><a href="getting-started.html#cb42-3" tabindex="-1"></a><span class="fu">class</span>(numeric_vector)  <span class="co"># Returns &quot;numeric&quot;.</span></span>
<span id="cb42-4"><a href="getting-started.html#cb42-4" tabindex="-1"></a></span>
<span id="cb42-5"><a href="getting-started.html#cb42-5" tabindex="-1"></a><span class="co"># Character vector</span></span>
<span id="cb42-6"><a href="getting-started.html#cb42-6" tabindex="-1"></a>character_vector <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Hello&quot;</span>, <span class="st">&quot;World&quot;</span>, <span class="st">&quot;!&quot;</span>)</span>
<span id="cb42-7"><a href="getting-started.html#cb42-7" tabindex="-1"></a><span class="fu">class</span>(character_vector)  <span class="co"># Returns &quot;character&quot;.</span></span>
<span id="cb42-8"><a href="getting-started.html#cb42-8" tabindex="-1"></a></span>
<span id="cb42-9"><a href="getting-started.html#cb42-9" tabindex="-1"></a><span class="co"># Logical vector</span></span>
<span id="cb42-10"><a href="getting-started.html#cb42-10" tabindex="-1"></a>logical_vector <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="cn">TRUE</span>, <span class="cn">FALSE</span>, <span class="cn">TRUE</span>)</span>
<span id="cb42-11"><a href="getting-started.html#cb42-11" tabindex="-1"></a><span class="fu">class</span>(logical_vector)  <span class="co"># Returns &quot;logical&quot;.</span></span></code></pre></div>
<pre><code>## [1] &quot;numeric&quot;
## [1] &quot;character&quot;
## [1] &quot;logical&quot;</code></pre>
<p>The function <code>c()</code> can also be used to add elements to a vector:</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="getting-started.html#cb44-1" tabindex="-1"></a><span class="co"># Add elements to existing vector:</span></span>
<span id="cb44-2"><a href="getting-started.html#cb44-2" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>)</span>
<span id="cb44-3"><a href="getting-started.html#cb44-3" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(x, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>)</span>
<span id="cb44-4"><a href="getting-started.html#cb44-4" tabindex="-1"></a>x</span></code></pre></div>
<pre><code>## [1] 1 2 3 4 5 6</code></pre>
<p>The <code>sec()</code> function creates a sequence of numbers or dates:</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="getting-started.html#cb46-1" tabindex="-1"></a><span class="co"># Create a sequence of numbers:</span></span>
<span id="cb46-2"><a href="getting-started.html#cb46-2" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">1</span>, <span class="at">to =</span> <span class="fl">1.5</span>, <span class="at">by =</span> <span class="fl">0.1</span>)</span>
<span id="cb46-3"><a href="getting-started.html#cb46-3" tabindex="-1"></a>x</span></code></pre></div>
<pre><code>## [1] 1.0 1.1 1.2 1.3 1.4 1.5</code></pre>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="getting-started.html#cb48-1" tabindex="-1"></a><span class="co"># Create a sequence of dates:</span></span>
<span id="cb48-2"><a href="getting-started.html#cb48-2" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="fu">as.Date</span>(<span class="st">&quot;2004-05-01&quot;</span>), <span class="at">to =</span> <span class="fu">as.Date</span>(<span class="st">&quot;2004-12-01&quot;</span>), <span class="at">by =</span> <span class="st">&quot;month&quot;</span>)</span>
<span id="cb48-3"><a href="getting-started.html#cb48-3" tabindex="-1"></a>x</span></code></pre></div>
<pre><code>## [1] &quot;2004-05-01&quot; &quot;2004-06-01&quot; &quot;2004-07-01&quot; &quot;2004-08-01&quot; &quot;2004-09-01&quot;
## [6] &quot;2004-10-01&quot; &quot;2004-11-01&quot; &quot;2004-12-01&quot;</code></pre>
<p>Missing data is represented as <code>NA</code> (not available). The function <code>is.na()</code> indicates the elements that are missing and <code>anyNA()</code> returns TRUE if the vector contains any missing values:</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="getting-started.html#cb50-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="cn">NA</span>, <span class="cn">NA</span>, <span class="dv">4</span>, <span class="dv">9</span>, <span class="dv">12</span>, <span class="dv">5</span>, <span class="dv">4</span>, <span class="cn">NA</span>)</span>
<span id="cb50-2"><a href="getting-started.html#cb50-2" tabindex="-1"></a><span class="fu">is.na</span>(x)</span></code></pre></div>
<pre><code>##  [1] FALSE FALSE  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE  TRUE</code></pre>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="getting-started.html#cb52-1" tabindex="-1"></a><span class="fu">anyNA</span>(x)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>A generalization of logical vectors are <strong>factors</strong>, which are vectors that restrict entries to be one of predefined categories:</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="getting-started.html#cb54-1" tabindex="-1"></a><span class="co"># Unordered factors, e.g. categories &quot;Male&quot; and &quot;Female&quot;:</span></span>
<span id="cb54-2"><a href="getting-started.html#cb54-2" tabindex="-1"></a>gender_vector <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Male&quot;</span>, <span class="st">&quot;Female&quot;</span>, <span class="st">&quot;Male&quot;</span>, <span class="st">&quot;Male&quot;</span>, <span class="st">&quot;Male&quot;</span>, <span class="st">&quot;Female&quot;</span>, <span class="st">&quot;Male&quot;</span>)</span>
<span id="cb54-3"><a href="getting-started.html#cb54-3" tabindex="-1"></a>factor_gender_vector <span class="ot">&lt;-</span> <span class="fu">factor</span>(gender_vector)</span>
<span id="cb54-4"><a href="getting-started.html#cb54-4" tabindex="-1"></a>factor_gender_vector</span></code></pre></div>
<pre><code>## [1] Male   Female Male   Male   Male   Female Male  
## Levels: Female Male</code></pre>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="getting-started.html#cb56-1" tabindex="-1"></a><span class="co"># Ordered factors, e.g. categories with ordering Low &lt; Medium &lt; High:</span></span>
<span id="cb56-2"><a href="getting-started.html#cb56-2" tabindex="-1"></a>temperature_vector <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;High&quot;</span>, <span class="st">&quot;Low&quot;</span>, <span class="st">&quot;Low&quot;</span>, <span class="st">&quot;Low&quot;</span>, <span class="st">&quot;Medium&quot;</span>, <span class="st">&quot;Low&quot;</span>, <span class="st">&quot;Low&quot;</span>)</span>
<span id="cb56-3"><a href="getting-started.html#cb56-3" tabindex="-1"></a>factor_temperature_vector <span class="ot">&lt;-</span> <span class="fu">factor</span>(temperature_vector, </span>
<span id="cb56-4"><a href="getting-started.html#cb56-4" tabindex="-1"></a>                                    <span class="at">order =</span> <span class="cn">TRUE</span>, </span>
<span id="cb56-5"><a href="getting-started.html#cb56-5" tabindex="-1"></a>                                    <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&quot;Low&quot;</span>, <span class="st">&quot;Medium&quot;</span>, <span class="st">&quot;High&quot;</span>))</span>
<span id="cb56-6"><a href="getting-started.html#cb56-6" tabindex="-1"></a>factor_temperature_vector</span></code></pre></div>
<pre><code>## [1] High   Low    Low    Low    Medium Low    Low   
## Levels: Low &lt; Medium &lt; High</code></pre>
</div>
<div id="matrix-matrix" class="section level3 hasAnchor" number="3.2.3">
<h3><span class="header-section-number">3.2.3</span> Matrix (<code>matrix</code>)<a href="getting-started.html#matrix-matrix" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A matrix in R (<code>matrix</code>) is a two-dimensional array that extends atomic vectors, containing both rows and columns. The elements within a matrix must be of the same data type.</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="getting-started.html#cb58-1" tabindex="-1"></a><span class="co"># Create a 3x3 numeric matrix, column-wise:</span></span>
<span id="cb58-2"><a href="getting-started.html#cb58-2" tabindex="-1"></a>numeric_matrix <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>, <span class="at">nrow =</span> <span class="dv">3</span>, <span class="at">ncol =</span> <span class="dv">3</span>)</span>
<span id="cb58-3"><a href="getting-started.html#cb58-3" tabindex="-1"></a>numeric_matrix</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    4    7
## [2,]    2    5    8
## [3,]    3    6    9</code></pre>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="getting-started.html#cb60-1" tabindex="-1"></a><span class="fu">class</span>(numeric_matrix)  <span class="co"># Returns &quot;matrix&quot;.</span></span></code></pre></div>
<pre><code>## [1] &quot;matrix&quot; &quot;array&quot;</code></pre>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="getting-started.html#cb62-1" tabindex="-1"></a><span class="fu">typeof</span>(numeric_matrix)  <span class="co"># Returns &quot;numeric&quot;.</span></span></code></pre></div>
<pre><code>## [1] &quot;integer&quot;</code></pre>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="getting-started.html#cb64-1" tabindex="-1"></a><span class="co"># Create a 2x3 character matrix, row-wise:</span></span>
<span id="cb64-2"><a href="getting-started.html#cb64-2" tabindex="-1"></a>character_matrix <span class="ot">&lt;-</span> <span class="fu">matrix</span>(letters[<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>], <span class="at">nrow =</span> <span class="dv">2</span>, <span class="at">ncol =</span> <span class="dv">3</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>)</span>
<span id="cb64-3"><a href="getting-started.html#cb64-3" tabindex="-1"></a>character_matrix</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,] &quot;a&quot;  &quot;b&quot;  &quot;c&quot; 
## [2,] &quot;d&quot;  &quot;e&quot;  &quot;f&quot;</code></pre>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="getting-started.html#cb66-1" tabindex="-1"></a><span class="fu">class</span>(character_matrix)  <span class="co"># Returns &quot;matrix&quot;.</span></span></code></pre></div>
<pre><code>## [1] &quot;matrix&quot; &quot;array&quot;</code></pre>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="getting-started.html#cb68-1" tabindex="-1"></a><span class="fu">typeof</span>(character_matrix)  <span class="co"># Returns &quot;character&quot;.</span></span></code></pre></div>
<pre><code>## [1] &quot;character&quot;</code></pre>
<p>To select specific elements, rows, or columns within a matrix, square brackets are used. The <code>cbind()</code> and <code>rbind()</code> functions enable the combination of columns and rows, respectively.</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="getting-started.html#cb70-1" tabindex="-1"></a><span class="co"># Print element in the second row and first column:</span></span>
<span id="cb70-2"><a href="getting-started.html#cb70-2" tabindex="-1"></a>character_matrix[<span class="dv">2</span>, <span class="dv">1</span>]</span></code></pre></div>
<pre><code>## [1] &quot;d&quot;</code></pre>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="getting-started.html#cb72-1" tabindex="-1"></a><span class="co"># Print the second row:</span></span>
<span id="cb72-2"><a href="getting-started.html#cb72-2" tabindex="-1"></a>character_matrix[<span class="dv">2</span>, ]</span></code></pre></div>
<pre><code>## [1] &quot;d&quot; &quot;e&quot; &quot;f&quot;</code></pre>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="getting-started.html#cb74-1" tabindex="-1"></a><span class="co"># Combine matrices:</span></span>
<span id="cb74-2"><a href="getting-started.html#cb74-2" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>, <span class="at">nrow =</span> <span class="dv">2</span>, <span class="at">ncol =</span> <span class="dv">2</span>)</span>
<span id="cb74-3"><a href="getting-started.html#cb74-3" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">101</span><span class="sc">:</span><span class="dv">104</span>, <span class="at">nrow =</span> <span class="dv">2</span>, <span class="at">ncol =</span> <span class="dv">2</span>)</span>
<span id="cb74-4"><a href="getting-started.html#cb74-4" tabindex="-1"></a><span class="fu">rbind</span>(x, y)  <span class="co"># Combines matrices x and y row-wise.</span></span></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    1    3
## [2,]    2    4
## [3,]  101  103
## [4,]  102  104</code></pre>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="getting-started.html#cb76-1" tabindex="-1"></a><span class="fu">cbind</span>(x, y)  <span class="co"># Combines matrices x and y column-wise.</span></span></code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]    1    3  101  103
## [2,]    2    4  102  104</code></pre>
</div>
<div id="list-list" class="section level3 hasAnchor" number="3.2.4">
<h3><span class="header-section-number">3.2.4</span> List (<code>list</code>)<a href="getting-started.html#list-list" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A list (<code>list</code>) in R serve as an ordered collection of objects. In contrast to vectors, elements within a list are not required to be of the same type. Moreover, some list elements may store multiple sub-elements, allowing for complex nested structures. For instance, a single element of a list might itself be a matrix or another list.</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="getting-started.html#cb78-1" tabindex="-1"></a><span class="co"># List</span></span>
<span id="cb78-2"><a href="getting-started.html#cb78-2" tabindex="-1"></a>my_list <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="dv">1</span>, <span class="st">&quot;a&quot;</span>, <span class="cn">TRUE</span>, <span class="dv">1</span><span class="sc">+</span>4i, </span>
<span id="cb78-3"><a href="getting-started.html#cb78-3" tabindex="-1"></a>                <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>), <span class="fu">matrix</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>, <span class="dv">2</span>, <span class="dv">4</span>), <span class="fu">list</span>(<span class="st">&quot;c&quot;</span>,<span class="dv">4</span>))</span>
<span id="cb78-4"><a href="getting-started.html#cb78-4" tabindex="-1"></a><span class="fu">names</span>(my_list) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;num_1&quot;</span>, <span class="st">&quot;char_a&quot;</span>, <span class="st">&quot;log_T&quot;</span>, <span class="st">&quot;complex_1p4i&quot;</span>,</span>
<span id="cb78-5"><a href="getting-started.html#cb78-5" tabindex="-1"></a>                    <span class="st">&quot;vec&quot;</span>, <span class="st">&quot;mat&quot;</span>, <span class="st">&quot;list&quot;</span>)</span>
<span id="cb78-6"><a href="getting-started.html#cb78-6" tabindex="-1"></a>my_list</span></code></pre></div>
<pre><code>## $num_1
## [1] 1
## 
## $char_a
## [1] &quot;a&quot;
## 
## $log_T
## [1] TRUE
## 
## $complex_1p4i
## [1] 1+4i
## 
## $vec
## [1] 1 2 3
## 
## $mat
##      [,1] [,2] [,3] [,4]
## [1,]    1    3    5    7
## [2,]    2    4    6    8
## 
## $list
## $list[[1]]
## [1] &quot;c&quot;
## 
## $list[[2]]
## [1] 4</code></pre>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="getting-started.html#cb80-1" tabindex="-1"></a><span class="fu">class</span>(my_list)  <span class="co"># Returns &quot;list&quot;.</span></span></code></pre></div>
<pre><code>## [1] &quot;list&quot;</code></pre>
<p>The content of elements can be retrieved by using double square brackets:</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="getting-started.html#cb82-1" tabindex="-1"></a><span class="co"># Select second element:</span></span>
<span id="cb82-2"><a href="getting-started.html#cb82-2" tabindex="-1"></a>my_list[[<span class="dv">2</span>]]</span></code></pre></div>
<pre><code>## [1] &quot;a&quot;</code></pre>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="getting-started.html#cb84-1" tabindex="-1"></a><span class="co"># Select element named &quot;mat&quot;:</span></span>
<span id="cb84-2"><a href="getting-started.html#cb84-2" tabindex="-1"></a>my_list[[<span class="st">&quot;mat&quot;</span>]]</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]    1    3    5    7
## [2,]    2    4    6    8</code></pre>
</div>
<div id="data-frame-data.frame" class="section level3 hasAnchor" number="3.2.5">
<h3><span class="header-section-number">3.2.5</span> Data Frame (<code>data.frame</code>)<a href="getting-started.html#data-frame-data.frame" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A data frame (<code>data.frame</code>) in R resembles a matrix in its two-dimensional, rectangular structure. However, unlike a matrix, a data frame allows each column to contain a different data type. Therefore, within each column (or vector), the elements must be homogeneous, but different columns can accommodate distinct types. Typically, when importing data into R, the default object type used is a data frame.</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="getting-started.html#cb86-1" tabindex="-1"></a><span class="co"># Vectors</span></span>
<span id="cb86-2"><a href="getting-started.html#cb86-2" tabindex="-1"></a>student_names <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Anna&quot;</span>, <span class="st">&quot;Ella&quot;</span>, <span class="st">&quot;Sophia&quot;</span>)</span>
<span id="cb86-3"><a href="getting-started.html#cb86-3" tabindex="-1"></a>student_ages <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">23</span>, <span class="dv">21</span>, <span class="dv">25</span>)</span>
<span id="cb86-4"><a href="getting-started.html#cb86-4" tabindex="-1"></a>student_grades <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>, <span class="st">&quot;A&quot;</span>)</span>
<span id="cb86-5"><a href="getting-started.html#cb86-5" tabindex="-1"></a>student_major <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Math&quot;</span>, <span class="st">&quot;Biology&quot;</span>, <span class="st">&quot;Physics&quot;</span>)</span>
<span id="cb86-6"><a href="getting-started.html#cb86-6" tabindex="-1"></a></span>
<span id="cb86-7"><a href="getting-started.html#cb86-7" tabindex="-1"></a><span class="co"># Data frame</span></span>
<span id="cb86-8"><a href="getting-started.html#cb86-8" tabindex="-1"></a>students_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">name =</span> student_names, </span>
<span id="cb86-9"><a href="getting-started.html#cb86-9" tabindex="-1"></a>                          <span class="at">age =</span> student_ages, </span>
<span id="cb86-10"><a href="getting-started.html#cb86-10" tabindex="-1"></a>                          <span class="at">grade =</span> student_grades, </span>
<span id="cb86-11"><a href="getting-started.html#cb86-11" tabindex="-1"></a>                          <span class="at">major =</span> student_major)</span>
<span id="cb86-12"><a href="getting-started.html#cb86-12" tabindex="-1"></a>students_df</span></code></pre></div>
<pre><code>##     name age grade   major
## 1   Anna  23     A    Math
## 2   Ella  21     B Biology
## 3 Sophia  25     A Physics</code></pre>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="getting-started.html#cb88-1" tabindex="-1"></a><span class="fu">class</span>(students_df)  <span class="co"># Returns &quot;data.frame&quot;.</span></span></code></pre></div>
<pre><code>## [1] &quot;data.frame&quot;</code></pre>
<p>Data frames are frequently used for data storage and manipulation in R. The following illustrates some common functions used on data frames:</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="getting-started.html#cb90-1" tabindex="-1"></a><span class="co"># Access a column in the data frame</span></span>
<span id="cb90-2"><a href="getting-started.html#cb90-2" tabindex="-1"></a>students_df<span class="sc">$</span>name</span>
<span id="cb90-3"><a href="getting-started.html#cb90-3" tabindex="-1"></a></span>
<span id="cb90-4"><a href="getting-started.html#cb90-4" tabindex="-1"></a><span class="co"># Alternative way to access a column:</span></span>
<span id="cb90-5"><a href="getting-started.html#cb90-5" tabindex="-1"></a>students_df[[<span class="st">&quot;name&quot;</span>]]</span>
<span id="cb90-6"><a href="getting-started.html#cb90-6" tabindex="-1"></a></span>
<span id="cb90-7"><a href="getting-started.html#cb90-7" tabindex="-1"></a><span class="co"># Access second row in third column:</span></span>
<span id="cb90-8"><a href="getting-started.html#cb90-8" tabindex="-1"></a>students_df[<span class="dv">2</span>, <span class="dv">3</span>]</span></code></pre></div>
<pre><code>## [1] &quot;Anna&quot;   &quot;Ella&quot;   &quot;Sophia&quot;
## [1] &quot;Anna&quot;   &quot;Ella&quot;   &quot;Sophia&quot;
## [1] &quot;B&quot;</code></pre>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="getting-started.html#cb92-1" tabindex="-1"></a><span class="co"># When selecting just one column, data frame produces a vector</span></span>
<span id="cb92-2"><a href="getting-started.html#cb92-2" tabindex="-1"></a><span class="fu">class</span>(students_df[, <span class="dv">3</span>])</span>
<span id="cb92-3"><a href="getting-started.html#cb92-3" tabindex="-1"></a></span>
<span id="cb92-4"><a href="getting-started.html#cb92-4" tabindex="-1"></a><span class="co"># To avoid this, add drop = FALSE</span></span>
<span id="cb92-5"><a href="getting-started.html#cb92-5" tabindex="-1"></a><span class="fu">class</span>(students_df[, <span class="dv">3</span> , <span class="at">drop =</span> <span class="cn">FALSE</span>])</span></code></pre></div>
<pre><code>## [1] &quot;character&quot;
## [1] &quot;data.frame&quot;</code></pre>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="getting-started.html#cb94-1" tabindex="-1"></a><span class="co"># Add a column to the data frame</span></span>
<span id="cb94-2"><a href="getting-started.html#cb94-2" tabindex="-1"></a>students_df<span class="sc">$</span>gpa <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">3.8</span>, <span class="fl">3.5</span>, <span class="fl">3.9</span>)</span>
<span id="cb94-3"><a href="getting-started.html#cb94-3" tabindex="-1"></a>students_df</span></code></pre></div>
<pre><code>##     name age grade   major gpa
## 1   Anna  23     A    Math 3.8
## 2   Ella  21     B Biology 3.5
## 3 Sophia  25     A Physics 3.9</code></pre>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="getting-started.html#cb96-1" tabindex="-1"></a><span class="co"># Subset the data frame</span></span>
<span id="cb96-2"><a href="getting-started.html#cb96-2" tabindex="-1"></a>students_df[students_df<span class="sc">$</span>age <span class="sc">&gt;</span> <span class="dv">22</span> <span class="sc">&amp;</span> students_df<span class="sc">$</span>gpa <span class="sc">&gt;</span> <span class="fl">3.6</span>, ]</span></code></pre></div>
<pre><code>##     name age grade   major gpa
## 1   Anna  23     A    Math 3.8
## 3 Sophia  25     A Physics 3.9</code></pre>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="getting-started.html#cb98-1" tabindex="-1"></a><span class="co"># Number of columns and rows</span></span>
<span id="cb98-2"><a href="getting-started.html#cb98-2" tabindex="-1"></a><span class="fu">ncol</span>(students_df)</span>
<span id="cb98-3"><a href="getting-started.html#cb98-3" tabindex="-1"></a><span class="fu">nrow</span>(students_df)</span>
<span id="cb98-4"><a href="getting-started.html#cb98-4" tabindex="-1"></a></span>
<span id="cb98-5"><a href="getting-started.html#cb98-5" tabindex="-1"></a><span class="co"># Column and row names</span></span>
<span id="cb98-6"><a href="getting-started.html#cb98-6" tabindex="-1"></a><span class="fu">colnames</span>(students_df)</span>
<span id="cb98-7"><a href="getting-started.html#cb98-7" tabindex="-1"></a><span class="fu">rownames</span>(students_df)</span></code></pre></div>
<pre><code>## [1] 5
## [1] 3
## [1] &quot;name&quot;  &quot;age&quot;   &quot;grade&quot; &quot;major&quot; &quot;gpa&quot;  
## [1] &quot;1&quot; &quot;2&quot; &quot;3&quot;</code></pre>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="getting-started.html#cb100-1" tabindex="-1"></a><span class="co"># Change column names</span></span>
<span id="cb100-2"><a href="getting-started.html#cb100-2" tabindex="-1"></a><span class="fu">colnames</span>(students_df) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Name&quot;</span>, <span class="st">&quot;Age&quot;</span>, <span class="st">&quot;Grade&quot;</span>, <span class="st">&quot;Major&quot;</span>, <span class="st">&quot;GPA&quot;</span>)</span>
<span id="cb100-3"><a href="getting-started.html#cb100-3" tabindex="-1"></a>students_df</span></code></pre></div>
<pre><code>##     Name Age Grade   Major GPA
## 1   Anna  23     A    Math 3.8
## 2   Ella  21     B Biology 3.5
## 3 Sophia  25     A Physics 3.9</code></pre>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="getting-started.html#cb102-1" tabindex="-1"></a><span class="co"># Take a look at the data type of each column</span></span>
<span id="cb102-2"><a href="getting-started.html#cb102-2" tabindex="-1"></a><span class="fu">str</span>(students_df)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    3 obs. of  5 variables:
##  $ Name : chr  &quot;Anna&quot; &quot;Ella&quot; &quot;Sophia&quot;
##  $ Age  : num  23 21 25
##  $ Grade: chr  &quot;A&quot; &quot;B&quot; &quot;A&quot;
##  $ Major: chr  &quot;Math&quot; &quot;Biology&quot; &quot;Physics&quot;
##  $ GPA  : num  3.8 3.5 3.9</code></pre>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="getting-started.html#cb104-1" tabindex="-1"></a><span class="co"># Take a look at the data in a separate window</span></span>
<span id="cb104-2"><a href="getting-started.html#cb104-2" tabindex="-1"></a><span class="fu">View</span>(students_df)</span></code></pre></div>
<p>These examples illustrate just a few of the operations you can perform with data frames in R. With additional libraries like <code>dplyr</code>, <code>tidyr</code>, and <code>data.table</code>, more complex manipulations are possible.</p>
</div>
<div id="tibble" class="section level3 hasAnchor" number="3.2.6">
<h3><span class="header-section-number">3.2.6</span> Tibble (<code>tbl_df</code>)<a href="getting-started.html#tibble" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A tibble (<code>tbl_df</code>) is a more convenient version of a data frame. It is part of the <code>tibble</code> package in the <code>tidyverse</code> collection of R packages. To use tibbles, you need to install the <code>tibble</code> package by executing <code>install.packages("tibble")</code> in your console. Don’t forget to include <code>library("tibble")</code> at the beginning of your R script.</p>
<p>To create a tibble, you can use the <code>tibble()</code> function. Here’s an example:</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="getting-started.html#cb105-1" tabindex="-1"></a><span class="co"># Load R package</span></span>
<span id="cb105-2"><a href="getting-started.html#cb105-2" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;tibble&quot;</span>)</span>
<span id="cb105-3"><a href="getting-started.html#cb105-3" tabindex="-1"></a></span>
<span id="cb105-4"><a href="getting-started.html#cb105-4" tabindex="-1"></a><span class="co"># Create a new tibble</span></span>
<span id="cb105-5"><a href="getting-started.html#cb105-5" tabindex="-1"></a>tib <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">name =</span> letters[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>], </span>
<span id="cb105-6"><a href="getting-started.html#cb105-6" tabindex="-1"></a>              <span class="at">id =</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, <span class="dv">3</span>),</span>
<span id="cb105-7"><a href="getting-started.html#cb105-7" tabindex="-1"></a>              <span class="at">age =</span> <span class="fu">sample</span>(<span class="dv">18</span><span class="sc">:</span><span class="dv">70</span>, <span class="dv">3</span>),</span>
<span id="cb105-8"><a href="getting-started.html#cb105-8" tabindex="-1"></a>              <span class="at">sex =</span> <span class="fu">factor</span>(<span class="fu">c</span>(<span class="st">&quot;M&quot;</span>, <span class="st">&quot;F&quot;</span>, <span class="st">&quot;F&quot;</span>)))</span>
<span id="cb105-9"><a href="getting-started.html#cb105-9" tabindex="-1"></a>tib</span></code></pre></div>
<pre><code>## # A tibble: 3 × 4
##   name     id   age sex  
##   &lt;chr&gt; &lt;int&gt; &lt;int&gt; &lt;fct&gt;
## 1 a         5    39 M    
## 2 b         3    19 F    
## 3 c         1    22 F</code></pre>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="getting-started.html#cb107-1" tabindex="-1"></a><span class="fu">class</span>(tib)</span></code></pre></div>
<pre><code>## [1] &quot;tbl_df&quot;     &quot;tbl&quot;        &quot;data.frame&quot;</code></pre>
<p>One advantage of tibbles is that they make it easy to calculate and create new columns. Here’s an example:</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="getting-started.html#cb109-1" tabindex="-1"></a>tib <span class="ot">&lt;-</span> <span class="fu">tibble</span>(tib, <span class="at">idvage =</span> id<span class="sc">/</span>age)</span>
<span id="cb109-2"><a href="getting-started.html#cb109-2" tabindex="-1"></a>tib</span></code></pre></div>
<pre><code>## # A tibble: 3 × 5
##   name     id   age sex   idvage
##   &lt;chr&gt; &lt;int&gt; &lt;int&gt; &lt;fct&gt;  &lt;dbl&gt;
## 1 a         5    39 M     0.128 
## 2 b         3    19 F     0.158 
## 3 c         1    22 F     0.0455</code></pre>
<p>Unlike regular data frames, tibbles allow non-standard column names. You can use special characters or numbers as column names. Here’s an example:</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="getting-started.html#cb111-1" tabindex="-1"></a><span class="fu">tibble</span>(<span class="st">`</span><span class="at">:)</span><span class="st">`</span> <span class="ot">=</span> <span class="st">&quot;smile&quot;</span>, <span class="st">`</span><span class="at"> </span><span class="st">`</span> <span class="ot">=</span> <span class="st">&quot;space&quot;</span>, <span class="st">`</span><span class="at">2000</span><span class="st">`</span> <span class="ot">=</span> <span class="st">&quot;number&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 3
##   `:)`  ` `   `2000`
##   &lt;chr&gt; &lt;chr&gt; &lt;chr&gt; 
## 1 smile space number</code></pre>
<p>Another way to create a tibble is with the <code>tribble()</code> function. It allows you to define column headings using formulas starting with ~ and separate entries with commas. Here’s an example:</p>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="getting-started.html#cb113-1" tabindex="-1"></a><span class="fu">tribble</span>(</span>
<span id="cb113-2"><a href="getting-started.html#cb113-2" tabindex="-1"></a>    <span class="sc">~</span>x, <span class="sc">~</span>y, <span class="sc">~</span>z,</span>
<span id="cb113-3"><a href="getting-started.html#cb113-3" tabindex="-1"></a>    <span class="st">&quot;a&quot;</span>, <span class="dv">2</span>, <span class="fl">3.6</span>,</span>
<span id="cb113-4"><a href="getting-started.html#cb113-4" tabindex="-1"></a>    <span class="st">&quot;b&quot;</span>, <span class="dv">1</span>, <span class="fl">8.5</span></span>
<span id="cb113-5"><a href="getting-started.html#cb113-5" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 3
##   x         y     z
##   &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 a         2   3.6
## 2 b         1   8.5</code></pre>
<p>For additional functions and a helpful cheat sheet on <code>tibble</code> and <code>dplyr</code>, you can refer to this <a href="https://github.com/rstudio/cheatsheets/raw/master/data-transformation.pdf">cheat sheet</a>.</p>
<div id="tidyverse" class="section level4 unnumbered hasAnchor">
<h4>Tidyverse<a href="getting-started.html#tidyverse" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The <code>tibble</code> package is part of the <code>tidyverse</code> environment, which is a collection of R packages with a shared design philosophy, grammar, and data structures. To install <code>tidyverse</code>, execute <code>install.packages("tidyverse")</code>, which includes <code>tibble</code>, <code>readr</code>, <code>dplyr</code>, <code>tidyr</code>, <code>ggplot2</code>, and more. Key functions in the <code>tidyverse</code> include <code>select()</code>, <code>filter()</code>, <code>mutate()</code>, <code>arrange()</code>, <code>count()</code>, <code>group_by()</code>, and <code>summarize()</code>. An interesting operator in the <code>tidyverse</code> is the <a href="https://www.datacamp.com/community/tutorials/pipe-r-tutorial">pipe operator</a> <code>%&gt;%</code>, which allows you to chain functions together in a readable and sequential manner. With the pipe operator, you can order the functions as they are applied, making your code more expressive and easier to understand. Here’s an example:</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="getting-started.html#cb115-1" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;tidyverse&quot;</span>)</span></code></pre></div>
<pre><code>## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
## ✔ dplyr     1.1.2     ✔ purrr     1.0.1
## ✔ forcats   1.0.0     ✔ readr     2.1.4
## ✔ ggplot2   3.4.2     ✔ stringr   1.5.0
## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::first()  masks xts::first()
## ✖ dplyr::lag()    masks stats::lag()
## ✖ dplyr::last()   masks xts::last()
## ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="getting-started.html#cb117-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.109</span>, <span class="fl">0.359</span>, <span class="fl">0.63</span>, <span class="fl">0.996</span>, <span class="fl">0.515</span>, <span class="fl">0.142</span>, <span class="fl">0.017</span>, <span class="fl">0.829</span>, <span class="fl">0.907</span>)</span>
<span id="cb117-2"><a href="getting-started.html#cb117-2" tabindex="-1"></a></span>
<span id="cb117-3"><a href="getting-started.html#cb117-3" tabindex="-1"></a><span class="co"># Apply several functions to x:</span></span>
<span id="cb117-4"><a href="getting-started.html#cb117-4" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">exp</span>(<span class="fu">diff</span>(<span class="fu">log</span>(x))), <span class="dv">1</span>)</span>
<span id="cb117-5"><a href="getting-started.html#cb117-5" tabindex="-1"></a>y</span></code></pre></div>
<pre><code>## [1]  3.3  1.8  1.6  0.5  0.3  0.1 48.8  1.1</code></pre>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="getting-started.html#cb119-1" tabindex="-1"></a><span class="co"># Perform the same computations using pipe operators:</span></span>
<span id="cb119-2"><a href="getting-started.html#cb119-2" tabindex="-1"></a>y <span class="ot">&lt;-</span> x <span class="sc">%&gt;%</span> <span class="fu">log</span>() <span class="sc">%&gt;%</span> <span class="fu">diff</span>() <span class="sc">%&gt;%</span> <span class="fu">exp</span>() <span class="sc">%&gt;%</span> <span class="fu">round</span>(<span class="dv">1</span>)</span>
<span id="cb119-3"><a href="getting-started.html#cb119-3" tabindex="-1"></a>y</span></code></pre></div>
<pre><code>## [1]  3.3  1.8  1.6  0.5  0.3  0.1 48.8  1.1</code></pre>
<p>By using the <code>%&gt;%</code> operator, each function is applied to the previous result, simplifying the code and improving its readability.</p>
<p>To delve deeper into the tidyverse, explore their official website: <a href="https://www.tidyverse.org">www.tidyverse.org</a>. Another resource is the R-Bootcamp, available at <a href="https://r-bootcamp.netlify.app/">r-bootcamp.netlify.app</a>. Additionally, <a href="https://learn.datacamp.com/">DataCamp</a> provides a comprehensive skill track devoted to the tidyverse, named <a href="https://learn.datacamp.com/skill-tracks/tidyverse-fundamentals">Tidyverse Fundamentals with R</a>.</p>
</div>
</div>
<div id="data-table-data.table" class="section level3 hasAnchor" number="3.2.7">
<h3><span class="header-section-number">3.2.7</span> Data Table (<code>data.table</code>)<a href="getting-started.html#data-table-data.table" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A data table (<code>data.table</code>) is similar to a data frame but with more advanced features for data manipulation. In fact, <code>data.table</code> and <code>tibble</code> can be considered competitors, with each offering enhancements over the standard data frame. While data tables offer high-speed functions and are optimized for large datasets, tibbles from the <code>tidyverse</code> are slower but are more user-friendly. The syntax used in <code>data.table</code> functions may seem esoteric, differing from that used in <code>tidyverse</code>. Like tibble, <code>data.table</code> is not a part of base R. It requires the installation of the <code>data.table</code> package via <code>install.packages("data.table")</code>, followed by <code>library("data.table")</code> at the beginning of your script.</p>
<p>To create a data table, you can use the <code>data.table()</code> function. Here’s an example:</p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="getting-started.html#cb121-1" tabindex="-1"></a><span class="co"># Load R package</span></span>
<span id="cb121-2"><a href="getting-started.html#cb121-2" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;data.table&quot;</span>)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;data.table&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:lubridate&#39;:
## 
##     hour, isoweek, mday, minute, month, quarter, second, wday, week,
##     yday, year</code></pre>
<pre><code>## The following objects are masked from &#39;package:dplyr&#39;:
## 
##     between, first, last</code></pre>
<pre><code>## The following object is masked from &#39;package:purrr&#39;:
## 
##     transpose</code></pre>
<pre><code>## The following objects are masked from &#39;package:xts&#39;:
## 
##     first, last</code></pre>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="getting-started.html#cb127-1" tabindex="-1"></a><span class="co"># Create a new data.table:</span></span>
<span id="cb127-2"><a href="getting-started.html#cb127-2" tabindex="-1"></a>dt <span class="ot">&lt;-</span> <span class="fu">data.table</span>(<span class="at">name =</span> letters[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>], </span>
<span id="cb127-3"><a href="getting-started.html#cb127-3" tabindex="-1"></a>                 <span class="at">id =</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,<span class="dv">3</span>),</span>
<span id="cb127-4"><a href="getting-started.html#cb127-4" tabindex="-1"></a>                 <span class="at">age =</span> <span class="fu">sample</span>(<span class="dv">18</span><span class="sc">:</span><span class="dv">70</span>,<span class="dv">3</span>), </span>
<span id="cb127-5"><a href="getting-started.html#cb127-5" tabindex="-1"></a>                 <span class="at">sex =</span> <span class="fu">factor</span>(<span class="fu">c</span>(<span class="st">&quot;M&quot;</span>, <span class="st">&quot;F&quot;</span>, <span class="st">&quot;F&quot;</span>)))</span>
<span id="cb127-6"><a href="getting-started.html#cb127-6" tabindex="-1"></a>dt</span></code></pre></div>
<pre><code>##    name id age sex
## 1:    a  4  18   M
## 2:    b  1  45   F
## 3:    c  5  54   F</code></pre>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="getting-started.html#cb129-1" tabindex="-1"></a><span class="fu">class</span>(dt)</span></code></pre></div>
<pre><code>## [1] &quot;data.table&quot; &quot;data.frame&quot;</code></pre>
<p>Columns in a data table can be referenced directly, and new variables can be created using the <code>:=</code> operator:</p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="getting-started.html#cb131-1" tabindex="-1"></a><span class="co"># Selection with data frame vs. data table:</span></span>
<span id="cb131-2"><a href="getting-started.html#cb131-2" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(dt) <span class="co"># create a data frame for comparison</span></span>
<span id="cb131-3"><a href="getting-started.html#cb131-3" tabindex="-1"></a>df[df<span class="sc">$</span>sex <span class="sc">==</span> <span class="st">&quot;M&quot;</span>, ] <span class="co"># select with data frame</span></span></code></pre></div>
<pre><code>##   name id age sex
## 1    a  4  18   M</code></pre>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="getting-started.html#cb133-1" tabindex="-1"></a>dt[sex <span class="sc">==</span> <span class="st">&quot;M&quot;</span>, ] <span class="co"># select with data table</span></span></code></pre></div>
<pre><code>##    name id age sex
## 1:    a  4  18   M</code></pre>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="getting-started.html#cb135-1" tabindex="-1"></a><span class="co"># Variable assignment with data frame vs. data table:</span></span>
<span id="cb135-2"><a href="getting-started.html#cb135-2" tabindex="-1"></a>df<span class="sc">$</span>id_over_age <span class="ot">&lt;-</span> df<span class="sc">$</span>id <span class="sc">/</span> df<span class="sc">$</span>age <span class="co"># assign with data frame</span></span>
<span id="cb135-3"><a href="getting-started.html#cb135-3" tabindex="-1"></a>dt[, id_over_age <span class="sc">:=</span> id <span class="sc">/</span> age] <span class="co"># assign with data table</span></span></code></pre></div>
<p>You can select multiple variables with a list:</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="getting-started.html#cb136-1" tabindex="-1"></a>dt[, <span class="fu">list</span>(sex, age)]</span></code></pre></div>
<pre><code>##    sex age
## 1:   M  18
## 2:   F  45
## 3:   F  54</code></pre>
<p>Multiple variables can be assigned simultaneously, where the LHS of the <code>:=</code> operator is a character vector of new variable names, and the RHS is a list of operations:</p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="getting-started.html#cb138-1" tabindex="-1"></a>dt[, <span class="fu">c</span>(<span class="st">&quot;id_times_age&quot;</span>, <span class="st">&quot;id_plus_age&quot;</span>) <span class="sc">:=</span> <span class="fu">list</span>(id <span class="sc">*</span> age, id <span class="sc">+</span> age)]</span>
<span id="cb138-2"><a href="getting-started.html#cb138-2" tabindex="-1"></a>dt</span></code></pre></div>
<pre><code>##    name id age sex id_over_age id_times_age id_plus_age
## 1:    a  4  18   M  0.22222222           72          22
## 2:    b  1  45   F  0.02222222           45          46
## 3:    c  5  54   F  0.09259259          270          59</code></pre>
<p>Many operations in data analysis need to be done by group (e.g. calculating average unemployment by year). In such cases, data table introduces a third dimension to perform these operations. Specifically, the data table syntax is <code>DT[i,j,by]</code> with options to</p>
<ul>
<li>subset rows using <code>i</code> (which rows?),</li>
<li>manipulate columns with <code>j</code> (what to do?), and</li>
<li>group according to <code>by</code> (grouped by what?).</li>
</ul>
<p>Here is an example:</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="getting-started.html#cb140-1" tabindex="-1"></a><span class="co"># Produce table with average age by sex:</span></span>
<span id="cb140-2"><a href="getting-started.html#cb140-2" tabindex="-1"></a>dt[, <span class="fu">mean</span>(age), by <span class="ot">=</span> sex]</span></code></pre></div>
<pre><code>##    sex   V1
## 1:   M 18.0
## 2:   F 49.5</code></pre>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="getting-started.html#cb142-1" tabindex="-1"></a><span class="co"># Do the same but name the columns &quot;Gender&quot; and &quot;Age by Gender&quot;:</span></span>
<span id="cb142-2"><a href="getting-started.html#cb142-2" tabindex="-1"></a>dt[, <span class="fu">list</span>(<span class="st">`</span><span class="at">Age by Gender</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">mean</span>(age)), by <span class="ot">=</span> <span class="fu">list</span>(<span class="at">Gender =</span> sex)]</span></code></pre></div>
<pre><code>##    Gender Age by Gender
## 1:      M          18.0
## 2:      F          49.5</code></pre>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb144-1"><a href="getting-started.html#cb144-1" tabindex="-1"></a><span class="co"># Assign a new variable with average age by sex named &quot;age_by_sex&quot;:</span></span>
<span id="cb144-2"><a href="getting-started.html#cb144-2" tabindex="-1"></a>dt[, age_by_sex <span class="sc">:=</span> <span class="fu">mean</span>(age), by <span class="ot">=</span> sex]</span>
<span id="cb144-3"><a href="getting-started.html#cb144-3" tabindex="-1"></a>dt</span></code></pre></div>
<pre><code>##    name id age sex id_over_age id_times_age id_plus_age age_by_sex
## 1:    a  4  18   M  0.22222222           72          22       18.0
## 2:    b  1  45   F  0.02222222           45          46       49.5
## 3:    c  5  54   F  0.09259259          270          59       49.5</code></pre>
<p>For additional information about data tables and their powerful features, check out the <a href="https://cran.r-project.org/web/packages/data.table/vignettes/datatable-intro.html">Intro to Data Table</a> documentation and this <a href="https://s3.amazonaws.com/assets.datacamp.com/blog_assets/datatable_Cheat_Sheet_R.pdf">cheat sheet</a> for <code>data.table</code> functions. Furthermore, <a href="https://learn.datacamp.com/">DataCamp</a> provides several courses on <code>data.table</code>, such as:</p>
<ul>
<li><a href="https://learn.datacamp.com/courses/data-manipulation-with-datatable-in-r">Data Manipulation with data.table in R</a></li>
<li><a href="https://learn.datacamp.com/courses/joining-data-with-datatable-in-r">Joining Data with data.table in R</a></li>
<li><a href="https://learn.datacamp.com/courses/time-series-with-datatable-in-r">Time Series with data.table in R</a></li>
</ul>
</div>
<div id="extensible-time-series-xts" class="section level3 hasAnchor" number="3.2.8">
<h3><span class="header-section-number">3.2.8</span> Extensible Time Series (<code>xts</code>)<a href="getting-started.html#extensible-time-series-xts" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><code>xts</code> (e<strong>x</strong>tensible <strong>t</strong>ime <strong>s</strong>eries) objects are specialized data structures designed for time series data. These are datasets where each observation corresponds to a specific timestamp. <code>xts</code> objects attach an index to the data, aligning each data point with its associated time. This functionality simplifies data manipulation and minimizes potential errors:</p>
<div class="figure"><span style="display:block;" id="fig:matrix-with-index"></span>
<img src="files/matrixwithindex-wide.png" alt="Data with Index. *Source*: [DataCamp](https://learn.datacamp.com/courses/manipulating-time-series-data-with-xts-and-zoo-in-r)."  />
<p class="caption">
Figure 3.3: Data with Index. <em>Source</em>: <a href="https://learn.datacamp.com/courses/manipulating-time-series-data-with-xts-and-zoo-in-r">DataCamp</a>.
</p>
</div>
<p>The index attached to an <code>xts</code> object is usually a <code>Date</code> or <code>POSIXct</code> vector, maintaining the data in chronological order from earliest to latest. If you wish to sort data (such as stock prices) by another variable (like trade volume), you’ll first need to convert the <code>xts</code> object back to a data frame, as <code>xts</code> objects preserve the time order. <code>xts</code> objects are built upon <code>zoo</code> objects (Zeileis’ Ordered Observations), another class of time-indexed data structures. <code>xts</code> objects enhance these base structures by providing additional features.</p>
<p>Like <code>tibble</code> and <code>data.table</code>, <code>xts</code> is not included in base R. To use it, you need to install the <code>xts</code> package using <code>install.packages("xts")</code>, then include <code>library("xts")</code> at the start of your script.</p>
<p>To create an <code>xts</code> object, use the <code>xts()</code> function which associates data with a time index (<code>order.by = time_index</code>):</p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="getting-started.html#cb146-1" tabindex="-1"></a><span class="co"># Load R package</span></span>
<span id="cb146-2"><a href="getting-started.html#cb146-2" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;xts&quot;</span>)</span>
<span id="cb146-3"><a href="getting-started.html#cb146-3" tabindex="-1"></a></span>
<span id="cb146-4"><a href="getting-started.html#cb146-4" tabindex="-1"></a><span class="co"># Create a new xts object from a matrix:</span></span>
<span id="cb146-5"><a href="getting-started.html#cb146-5" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>, <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">nrow =</span> <span class="dv">2</span>, <span class="at">dimnames =</span> <span class="fu">list</span>(<span class="cn">NULL</span>, <span class="fu">c</span>(<span class="st">&quot;a&quot;</span>, <span class="st">&quot;b&quot;</span>)))</span>
<span id="cb146-6"><a href="getting-started.html#cb146-6" tabindex="-1"></a>data</span></code></pre></div>
<pre><code>##      a b
## [1,] 1 3
## [2,] 2 4</code></pre>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="getting-started.html#cb148-1" tabindex="-1"></a>time_index <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(<span class="fu">c</span>(<span class="st">&quot;2020-06-01&quot;</span>, <span class="st">&quot;2020-07-01&quot;</span>))</span>
<span id="cb148-2"><a href="getting-started.html#cb148-2" tabindex="-1"></a>time_index</span></code></pre></div>
<pre><code>## [1] &quot;2020-06-01&quot; &quot;2020-07-01&quot;</code></pre>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="getting-started.html#cb150-1" tabindex="-1"></a>dxts <span class="ot">&lt;-</span> <span class="fu">xts</span>(<span class="at">x =</span> data, <span class="at">order.by =</span> time_index)</span>
<span id="cb150-2"><a href="getting-started.html#cb150-2" tabindex="-1"></a>dxts</span></code></pre></div>
<pre><code>##            a b
## 2020-06-01 1 3
## 2020-07-01 2 4</code></pre>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="getting-started.html#cb152-1" tabindex="-1"></a><span class="fu">class</span>(dxts)</span></code></pre></div>
<pre><code>## [1] &quot;xts&quot; &quot;zoo&quot;</code></pre>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="getting-started.html#cb154-1" tabindex="-1"></a><span class="fu">tclass</span>(dxts)</span></code></pre></div>
<pre><code>## [1] &quot;Date&quot;</code></pre>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="getting-started.html#cb156-1" tabindex="-1"></a><span class="co"># Extract time index</span></span>
<span id="cb156-2"><a href="getting-started.html#cb156-2" tabindex="-1"></a><span class="fu">index</span>(dxts)</span></code></pre></div>
<pre><code>## [1] &quot;2020-06-01&quot; &quot;2020-07-01&quot;</code></pre>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="getting-started.html#cb158-1" tabindex="-1"></a><span class="co"># Extract data without time index</span></span>
<span id="cb158-2"><a href="getting-started.html#cb158-2" tabindex="-1"></a><span class="fu">coredata</span>(dxts)</span></code></pre></div>
<pre><code>##      a b
## [1,] 1 3
## [2,] 2 4</code></pre>
<p>To delve deeper into <code>xts</code> and <code>zoo</code> objects, consider reading the guides <a href="https://rstudio-pubs-static.s3.amazonaws.com/288218_117e183e74964557a5da4fc5902fc671.html">Manipulating Time Series Data in R with xts &amp; zoo</a> and <a href="https://rpubs.com/rmariscal/404513">Time Series in R: Quick Reference</a>. Additionally, <a href="https://learn.datacamp.com/">DataCamp</a> provides in-depth courses on these topics:</p>
<ul>
<li><a href="https://learn.datacamp.com/courses/manipulating-time-series-data-with-xts-and-zoo-in-r">Manipulating Time Series Data with xts and zoo in R</a></li>
<li><a href="https://learn.datacamp.com/courses/importing-and-managing-financial-data-in-r">Importing and Managing Financial Data in R</a></li>
</ul>
<p>If you’re working within the <code>tidyverse</code> environment, the R package <a href="http://www.stats.bris.ac.uk/R/web/packages/tidyquant/vignettes/TQ02-quant-integrations-in-tidyquant.html"><code>tidyquant</code></a> offers seamless integration with <code>xts</code> and <code>zoo</code>. Lastly, this handy <a href="https://s3.amazonaws.com/assets.datacamp.com/blog_assets/xts_Cheat_Sheet_R.pdf">cheat sheet</a> provides a quick reference on <code>xts</code> and <code>zoo</code> functions.</p>
</div>
</div>
<div id="importing-data-in-r" class="section level2 hasAnchor" number="3.3">
<h2><span class="header-section-number">3.3</span> Importing Data in R<a href="getting-started.html#importing-data-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>R is a software specialized for data analysis. To analyze data using R, the data must first be imported into the R environment. R offers robust functionality for importing data in a variety of formats. This section explores how to import data from CSV, TSV, and Excel files. Before we dive into specifics, let’s ensure RStudio can locate the data stored on your computer.</p>
<div id="working-directory" class="section level3 hasAnchor" number="3.3.1">
<h3><span class="header-section-number">3.3.1</span> Working Directory<a href="getting-started.html#working-directory" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The working directory in R is the folder where R starts when it’s looking for files to read or write. If you’re not sure where your current working directory is, you can use the <code>getwd()</code> (get working directory) command in R to find out:</p>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="getting-started.html#cb160-1" tabindex="-1"></a><span class="fu">getwd</span>()</span></code></pre></div>
<pre><code>## [1] &quot;/Users/julianludwig/Library/CloudStorage/Dropbox/Economics/teaching/4300_2023/module-01&quot;</code></pre>
<p>To change your working directory, use the <code>setwd()</code> (set working directory) function:</p>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="getting-started.html#cb162-1" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">&quot;your/folder/path&quot;</span>)</span></code></pre></div>
<p>Be sure to replace <code>"your/folder/path"</code> with the actual path to your folder.</p>
<p>When your files are stored in the same directory as your working directory, defined using the <code>setwd()</code> function, you can directly access these files by their names. For instance, <code>read_csv("yieldcurve.csv")</code> will successfully read the file if “yieldcurve.csv” is in the working directory. If the file is located in a subfolder within the working directory, for example a folder named <code>files</code>, you would need to specify the folder in the file path when calling the file: <code>read_csv("files/yieldcurve.csv")</code>.</p>
<p>To find out the folder path for a specific file or folder on your computer, you can follow these steps:</p>
<div id="for-windows-1" class="section level4 unnumbered hasAnchor">
<h4>For Windows:<a href="getting-started.html#for-windows-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ol style="list-style-type: decimal">
<li>Navigate to the folder using the File Explorer.</li>
<li>Once you are in the folder, click on the address bar at the top of the File Explorer window. The address bar will now show the full path to the folder. This is the path you can set in R using the <code>setwd()</code> function.</li>
</ol>
<p>An example of a folder path on Windows might look like this: <code>C:/Users/YourName/Documents/R</code>.</p>
</div>
<div id="for-macos-1" class="section level4 unnumbered hasAnchor">
<h4>For MacOS:<a href="getting-started.html#for-macos-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ol style="list-style-type: decimal">
<li>Open Finder and navigate to the folder.</li>
<li>Once you are in the folder, Command-click (or right-click and hold, if you have a mouse) on the folder’s name at the top of the Finder window. A drop-down menu will appear showing the folder hierarchy.</li>
<li>Hover over each folder in the hierarchy to show the full path, then copy this path.</li>
</ol>
<p>An example of a folder path on macOS might look like this: <code>/Users/YourName/Documents/R</code>.</p>
<p>Remember, when setting the working directory in R, you need to use forward slashes (<code>/</code>) in the folder path, even on Windows where the convention is to use backslashes (<code>\</code>).</p>
</div>
</div>
<div id="csv-comma-separated-values" class="section level3 hasAnchor" number="3.3.2">
<h3><span class="header-section-number">3.3.2</span> CSV (Comma Separated Values)<a href="getting-started.html#csv-comma-separated-values" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>CSV (Comma Separated Values) is a common file format used to store tabular data. As the name suggests, the values in each row of a CSV file are separated by commas. Here’s an example of how data is stored in a CSV file:</p>
<ul>
<li>Male,8,100,3</li>
<li>Female,9,20,3</li>
</ul>
<p>In this section, we’ll demonstrate how to import a CSV file using real-world Treasury yield curve rates data.</p>
<div id="import-yield-curve-data-in-csv-format" class="section level4 unnumbered hasAnchor">
<h4>Import Yield Curve Data in CSV Format<a href="getting-started.html#import-yield-curve-data-in-csv-format" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>To obtain the yield curve data, follow these steps:</p>
<ol style="list-style-type: decimal">
<li>Visit the U.S. Treasury’s data center by clicking <a href="https://www.treasury.gov/resource-center/data-chart-center">here</a>.</li>
<li>Click on “Data” in the menu bar, then select “Daily Treasury Par Yield Curve Rates.”</li>
<li>On the data page, select “Download CSV” to obtain the yield curve data for the current year.</li>
<li>To access all the yield curve data since 1990, choose “All” under the “Select Time Period” option, and click “Apply.” Please note that when selecting all periods, the “Download CSV” button may not be available.</li>
<li>To manually save the data as a CSV file, you can copy the data by selecting it and using the Ctrl+C (or Cmd+C) command. Open an Excel file, and use the Ctrl+V (or Cmd+V) command to paste the data into the Excel file.</li>
<li>Save the Excel file as a CSV file named ‘yieldcurve.csv’ in a location of your choice, ensuring that it is saved in a familiar folder for easy access.</li>
</ol>
<p>Next, install and load the <code>readr</code> package. Run <code>install.packages("readr")</code> in the console and include the package at the top of your R script. You can then use the <code>read_csv()</code> or <code>read_delim()</code> function to import the yield curve data:</p>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="getting-started.html#cb163-1" tabindex="-1"></a><span class="co"># Load the package</span></span>
<span id="cb163-2"><a href="getting-started.html#cb163-2" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;readr&quot;</span>)</span>
<span id="cb163-3"><a href="getting-started.html#cb163-3" tabindex="-1"></a></span>
<span id="cb163-4"><a href="getting-started.html#cb163-4" tabindex="-1"></a><span class="co"># Import CSV file</span></span>
<span id="cb163-5"><a href="getting-started.html#cb163-5" tabindex="-1"></a>yc <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="at">file =</span> <span class="st">&quot;files/yieldcurve.csv&quot;</span>, <span class="at">col_names =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## Warning: One or more parsing issues, call `problems()` on your data frame for details,
## e.g.:
##   dat &lt;- vroom(...)
##   problems(dat)</code></pre>
<pre><code>## Rows: 8382 Columns: 14
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr (6): Date, 1 Mo, 2 Mo, 4 Mo, 20 Yr, 30 Yr
## dbl (8): 3 Mo, 6 Mo, 1 Yr, 2 Yr, 3 Yr, 5 Yr, 7 Yr, 10 Yr
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="getting-started.html#cb166-1" tabindex="-1"></a><span class="co"># Import CSV file using the read_delim() function</span></span>
<span id="cb166-2"><a href="getting-started.html#cb166-2" tabindex="-1"></a>yc <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(<span class="at">file =</span> <span class="st">&quot;files/yieldcurve.csv&quot;</span>, <span class="at">col_names =</span> <span class="cn">TRUE</span>, <span class="at">delim =</span> <span class="st">&quot;,&quot;</span>)</span></code></pre></div>
<pre><code>## Warning: One or more parsing issues, call `problems()` on your data frame for details,
## e.g.:
##   dat &lt;- vroom(...)
##   problems(dat)</code></pre>
<pre><code>## Rows: 8382 Columns: 14
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr (6): Date, 1 Mo, 2 Mo, 4 Mo, 20 Yr, 30 Yr
## dbl (8): 3 Mo, 6 Mo, 1 Yr, 2 Yr, 3 Yr, 5 Yr, 7 Yr, 10 Yr
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<p>In the code snippets above, the <code>read_csv()</code> and <code>read_delim()</code> functions from the <code>readr</code> package are used to import a CSV file named “yieldcurve.csv”. The <code>col_names = TRUE</code> argument indicates that the first row of the CSV file contains column names. The <code>delim = ","</code> argument specifies that the columns are separated by commas, which is the standard delimiter for CSV (<em>Comma</em> Separated Values) files. Either one of the two functions can be used to read the CSV file and store the data in the variable <code>yc</code> for further analysis.</p>
<p>To inspect the first few rows of the data, print the <code>yc</code> object in the console. For an overview of the entire dataset, use the <code>View()</code> function, which provides an interface similar to viewing the CSV file in Microsoft Excel:</p>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb169-1"><a href="getting-started.html#cb169-1" tabindex="-1"></a><span class="co"># Display the data</span></span>
<span id="cb169-2"><a href="getting-started.html#cb169-2" tabindex="-1"></a>yc</span></code></pre></div>
<pre><code>## # A tibble: 8,382 × 14
##    Date    `1 Mo` `2 Mo` `3 Mo` `4 Mo` `6 Mo` `1 Yr` `2 Yr` `3 Yr` `5 Yr` `7 Yr`
##    &lt;chr&gt;   &lt;chr&gt;  &lt;chr&gt;   &lt;dbl&gt; &lt;chr&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
##  1 01/02/… N/A    N/A      7.83 N/A      7.89   7.81   7.87   7.9    7.87   7.98
##  2 01/03/… N/A    N/A      7.89 N/A      7.94   7.85   7.94   7.96   7.92   8.04
##  3 01/04/… N/A    N/A      7.84 N/A      7.9    7.82   7.92   7.93   7.91   8.02
##  4 01/05/… N/A    N/A      7.79 N/A      7.85   7.79   7.9    7.94   7.92   8.03
##  5 01/08/… N/A    N/A      7.79 N/A      7.88   7.81   7.9    7.95   7.92   8.05
##  6 01/09/… N/A    N/A      7.8  N/A      7.82   7.78   7.91   7.94   7.92   8.05
##  7 01/10/… N/A    N/A      7.75 N/A      7.78   7.77   7.91   7.95   7.92   8   
##  8 01/11/… N/A    N/A      7.8  N/A      7.8    7.77   7.91   7.95   7.94   8.01
##  9 01/12/… N/A    N/A      7.74 N/A      7.81   7.76   7.93   7.98   7.99   8.07
## 10 01/16/… N/A    N/A      7.89 N/A      7.99   7.92   8.1    8.13   8.11   8.18
## # ℹ 8,372 more rows
## # ℹ 3 more variables: `10 Yr` &lt;dbl&gt;, `20 Yr` &lt;chr&gt;, `30 Yr` &lt;chr&gt;</code></pre>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb171-1"><a href="getting-started.html#cb171-1" tabindex="-1"></a><span class="co"># Display the data in a spreadsheet-like format</span></span>
<span id="cb171-2"><a href="getting-started.html#cb171-2" tabindex="-1"></a><span class="fu">View</span>(yc)</span></code></pre></div>
<p>Both the <code>read_csv()</code> and <code>read_delim()</code> functions convert the CSV file into a tibble (<code>tbl_df</code>), a modern version of the R data frame discussed in Section <a href="getting-started.html#tibble">3.2.6</a>. Remember, a data frame stores data in separate columns, each of which must be of the same data type. Use the <code>class(yc)</code> function to check the data type of the entire dataset, and <code>sapply(yc, class)</code> to check the data type of each column:</p>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb172-1"><a href="getting-started.html#cb172-1" tabindex="-1"></a><span class="co"># Check the data type of the entire dataset</span></span>
<span id="cb172-2"><a href="getting-started.html#cb172-2" tabindex="-1"></a><span class="fu">class</span>(yc)</span></code></pre></div>
<pre><code>## [1] &quot;spec_tbl_df&quot; &quot;tbl_df&quot;      &quot;tbl&quot;         &quot;data.frame&quot;</code></pre>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb174-1"><a href="getting-started.html#cb174-1" tabindex="-1"></a><span class="co"># Check the data type of each column</span></span>
<span id="cb174-2"><a href="getting-started.html#cb174-2" tabindex="-1"></a><span class="fu">sapply</span>(yc, class)</span></code></pre></div>
<pre><code>##        Date        1 Mo        2 Mo        3 Mo        4 Mo        6 Mo 
## &quot;character&quot; &quot;character&quot; &quot;character&quot;   &quot;numeric&quot; &quot;character&quot;   &quot;numeric&quot; 
##        1 Yr        2 Yr        3 Yr        5 Yr        7 Yr       10 Yr 
##   &quot;numeric&quot;   &quot;numeric&quot;   &quot;numeric&quot;   &quot;numeric&quot;   &quot;numeric&quot;   &quot;numeric&quot; 
##       20 Yr       30 Yr 
## &quot;character&quot; &quot;character&quot;</code></pre>
<p>When importing data in R, it’s possible that R assigns incorrect data types to some columns. For example, the <code>Date</code> column is treated as a character column even though it contains dates, and the <code>30 Yr</code> column is treated as a character column even though it contains interest rates. To address this issue, you can convert the first column to a date type and the remaining columns to numeric data types using the following three steps:</p>
<ol style="list-style-type: decimal">
<li>Replace “N/A” with <code>NA</code>, which represents missing values in R. This step is necessary because R doesn’t recognize “N/A”, and if a column includes “N/A”, R will consider it as a character vector instead of a numeric vector.</li>
</ol>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb176-1"><a href="getting-started.html#cb176-1" tabindex="-1"></a>yc[yc <span class="sc">==</span> <span class="st">&quot;N/A&quot;</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span></code></pre></div>
<ol start="2" style="list-style-type: decimal">
<li>Convert all yield columns to numeric data types:</li>
</ol>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb177-1"><a href="getting-started.html#cb177-1" tabindex="-1"></a>yc[, <span class="sc">-</span><span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="fu">sapply</span>(yc[, <span class="sc">-</span><span class="dv">1</span>], as.numeric)</span></code></pre></div>
<p>The <code>as.numeric()</code> function converts a data object into a numeric type. In this case, it converts columns with character values like “3” and “4” into the numeric values 3 and 4. The <code>sapply()</code> function applies the <code>as.numeric()</code> function to each of the selected columns. This converts all the interest rates to numeric data types.</p>
<ol start="3" style="list-style-type: decimal">
<li>Convert the date column to a date object, recognizing that the date format is Month/Day/Year or <code>%m/%d/%Y</code>:</li>
</ol>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb178-1"><a href="getting-started.html#cb178-1" tabindex="-1"></a><span class="co"># Check the date format</span></span>
<span id="cb178-2"><a href="getting-started.html#cb178-2" tabindex="-1"></a><span class="fu">head</span>(yc<span class="sc">$</span>Date)</span></code></pre></div>
<pre><code>## [1] &quot;01/02/1990&quot; &quot;01/03/1990&quot; &quot;01/04/1990&quot; &quot;01/05/1990&quot; &quot;01/08/1990&quot;
## [6] &quot;01/09/1990&quot;</code></pre>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb180-1"><a href="getting-started.html#cb180-1" tabindex="-1"></a><span class="co"># Convert to date format</span></span>
<span id="cb180-2"><a href="getting-started.html#cb180-2" tabindex="-1"></a>yc<span class="sc">$</span>Date <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(yc<span class="sc">$</span>Date, <span class="at">format =</span> <span class="st">&quot;%m/%d/%Y&quot;</span>)</span>
<span id="cb180-3"><a href="getting-started.html#cb180-3" tabindex="-1"></a><span class="fu">head</span>(yc<span class="sc">$</span>Date)</span></code></pre></div>
<pre><code>## [1] &quot;1990-01-02&quot; &quot;1990-01-03&quot; &quot;1990-01-04&quot; &quot;1990-01-05&quot; &quot;1990-01-08&quot;
## [6] &quot;1990-01-09&quot;</code></pre>
<p>Hence, we have successfully imported the yield curve data and performed the necessary conversions to ensure that all columns are in their correct formats:</p>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb182-1"><a href="getting-started.html#cb182-1" tabindex="-1"></a>yc</span></code></pre></div>
<pre><code>## # A tibble: 8,382 × 14
##    Date       `1 Mo` `2 Mo` `3 Mo` `4 Mo` `6 Mo` `1 Yr` `2 Yr` `3 Yr` `5 Yr`
##    &lt;date&gt;      &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
##  1 1990-01-02     NA     NA   7.83     NA   7.89   7.81   7.87   7.9    7.87
##  2 1990-01-03     NA     NA   7.89     NA   7.94   7.85   7.94   7.96   7.92
##  3 1990-01-04     NA     NA   7.84     NA   7.9    7.82   7.92   7.93   7.91
##  4 1990-01-05     NA     NA   7.79     NA   7.85   7.79   7.9    7.94   7.92
##  5 1990-01-08     NA     NA   7.79     NA   7.88   7.81   7.9    7.95   7.92
##  6 1990-01-09     NA     NA   7.8      NA   7.82   7.78   7.91   7.94   7.92
##  7 1990-01-10     NA     NA   7.75     NA   7.78   7.77   7.91   7.95   7.92
##  8 1990-01-11     NA     NA   7.8      NA   7.8    7.77   7.91   7.95   7.94
##  9 1990-01-12     NA     NA   7.74     NA   7.81   7.76   7.93   7.98   7.99
## 10 1990-01-16     NA     NA   7.89     NA   7.99   7.92   8.1    8.13   8.11
## # ℹ 8,372 more rows
## # ℹ 4 more variables: `7 Yr` &lt;dbl&gt;, `10 Yr` &lt;dbl&gt;, `20 Yr` &lt;dbl&gt;, `30 Yr` &lt;dbl&gt;</code></pre>
<p>Here, <code>&lt;dbl&gt;</code> stands for double, which is the R data type for decimal numbers, also known as numeric type. Converting the yield columns to <code>dbl</code> ensures that the values are treated as numeric and can be used for calculations, analysis, and visualization.</p>
</div>
<div id="plot-historical-trends-in-treasury-yields" class="section level4 unnumbered hasAnchor">
<h4>Plot Historical Trends in Treasury Yields<a href="getting-started.html#plot-historical-trends-in-treasury-yields" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Let’s use the <code>plot()</code> function to visualize the imported yield curve data. In this case, we will plot the 3-month Treasury rate over time, using the <code>Date</code> column as the x-axis and the <code>3 Mo</code> column as the y-axis:</p>
<div class="sourceCode" id="cb184"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb184-1"><a href="getting-started.html#cb184-1" tabindex="-1"></a><span class="co"># Plot the 3-month Treasury rate over time</span></span>
<span id="cb184-2"><a href="getting-started.html#cb184-2" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x =</span> yc<span class="sc">$</span>Date, <span class="at">y =</span> yc<span class="sc">$</span><span class="st">`</span><span class="at">3 Mo</span><span class="st">`</span>, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>,</span>
<span id="cb184-3"><a href="getting-started.html#cb184-3" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Date&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;%&quot;</span>, <span class="at">main =</span> <span class="st">&quot;3-Month Treasury Rate&quot;</span>)</span></code></pre></div>
<p>In the code snippet above, <code>plot()</code> is the R function used to create the plot. It takes several arguments to customize the appearance and behavior of the plot:</p>
<ul>
<li><code>x</code> represents the data to be plotted on the x-axis. In this case, it corresponds to the <code>Date</code> column from the yield curve data.</li>
<li><code>y</code> represents the data to be plotted on the y-axis. Here, it corresponds to the <code>3 Mo</code> column, which represents the 3-month Treasury rate.</li>
<li><code>type = "l"</code> specifies the type of plot to create. In this case, we use <code>"l"</code> to create a line plot.</li>
<li><code>xlab = "Date"</code> sets the label for the x-axis to “Date”.</li>
<li><code>ylab = "%"</code> sets the label for the y-axis to “%”.</li>
<li><code>main = "3-Month Treasury Rate"</code> sets the title of the plot to “3-Month Treasury Rate”.</li>
</ul>
<div class="figure"><span style="display:block;" id="fig:yield-historical-plot"></span>
<img src="_main_files/figure-html/yield-historical-plot-1.png" alt="3-Month Treasury Rate" width="672" />
<p class="caption">
Figure 3.4: 3-Month Treasury Rate
</p>
</div>
<p>The resulting plot, shown in Figure <a href="getting-started.html#fig:yield-historical-plot">3.4</a>, displays the historical evolution of the 3-month Treasury rate since 1990. It allows us to observe how interest rates have changed over time, with low rates often observed during recessions and high rates during boom periods. Recessions are typically characterized by reduced borrowing and investment activities, leading to decreased demand for credit and lower interest rates. Conversely, boom periods are associated with strong economic growth and increased credit demand, which can drive interest rates upward.</p>
<p>Furthermore, inflation plays a significant role in influencing interest rates through the Fisher effect. When inflation is high, lenders and investors are concerned about the diminishing value of money over time. To compensate for the erosion of purchasing power, lenders typically demand higher interest rates on loans. These higher interest rates reflect the expectation of future inflation and act as a safeguard against the declining value of the money lent. Conversely, when inflation is low, lenders may offer lower interest rates due to reduced concerns about the erosion of purchasing power.</p>
</div>
<div id="plot-yield-curve" class="section level4 unnumbered hasAnchor">
<h4>Plot Yield Curve<a href="getting-started.html#plot-yield-curve" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Next, let’s plot the yield curve. The yield curve is a graphical representation of the relationship between the interest rates (yields) and the time to maturity of a bond. It provides insights into market expectations regarding future interest rates and economic conditions.</p>
<p>To plot the yield curve, we will select the most recently available data from the dataset, which corresponds to the last row. We will extract the interest rates as a numeric vector and the column names (representing the time to maturity) as labels for the x-axis:</p>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb185-1"><a href="getting-started.html#cb185-1" tabindex="-1"></a><span class="co"># Extract the interest rates of the last row</span></span>
<span id="cb185-2"><a href="getting-started.html#cb185-2" tabindex="-1"></a>yc_most_recent_data <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">last</span>(yc[, <span class="sc">-</span><span class="dv">1</span>]))</span>
<span id="cb185-3"><a href="getting-started.html#cb185-3" tabindex="-1"></a>yc_most_recent_data</span></code></pre></div>
<pre><code>##  [1] 5.24 5.39 5.43 5.50 5.47 5.40 4.87 4.49 4.13 3.97 3.81 4.06 3.85</code></pre>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb187-1"><a href="getting-started.html#cb187-1" tabindex="-1"></a><span class="co"># Extract the column names of the last row</span></span>
<span id="cb187-2"><a href="getting-started.html#cb187-2" tabindex="-1"></a>yc_most_recent_labels <span class="ot">&lt;-</span> <span class="fu">colnames</span>(<span class="fu">last</span>(yc[, <span class="sc">-</span><span class="dv">1</span>]))</span>
<span id="cb187-3"><a href="getting-started.html#cb187-3" tabindex="-1"></a>yc_most_recent_labels</span></code></pre></div>
<pre><code>##  [1] &quot;1 Mo&quot;  &quot;2 Mo&quot;  &quot;3 Mo&quot;  &quot;4 Mo&quot;  &quot;6 Mo&quot;  &quot;1 Yr&quot;  &quot;2 Yr&quot;  &quot;3 Yr&quot;  &quot;5 Yr&quot; 
## [10] &quot;7 Yr&quot;  &quot;10 Yr&quot; &quot;20 Yr&quot; &quot;30 Yr&quot;</code></pre>
<div class="sourceCode" id="cb189"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb189-1"><a href="getting-started.html#cb189-1" tabindex="-1"></a><span class="co"># Plot the yield curve</span></span>
<span id="cb189-2"><a href="getting-started.html#cb189-2" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x =</span> yc_most_recent_data, <span class="at">xaxt =</span> <span class="st">&#39;n&#39;</span>, <span class="at">type =</span> <span class="st">&quot;o&quot;</span>, <span class="at">pch =</span> <span class="dv">19</span>,</span>
<span id="cb189-3"><a href="getting-started.html#cb189-3" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Time to Maturity&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Treasury Rate in %&quot;</span>,</span>
<span id="cb189-4"><a href="getting-started.html#cb189-4" tabindex="-1"></a>     <span class="at">main =</span> <span class="fu">paste</span>(<span class="st">&quot;Yield Curve on&quot;</span>, <span class="fu">format</span>(<span class="fu">last</span>(yc<span class="sc">$</span>Date), <span class="at">format =</span> <span class="st">&#39;%B %d, %Y&#39;</span>)))</span>
<span id="cb189-5"><a href="getting-started.html#cb189-5" tabindex="-1"></a><span class="fu">axis</span>(<span class="at">side =</span> <span class="dv">1</span>, <span class="at">at =</span> <span class="fu">seq</span>(<span class="dv">1</span>, <span class="fu">length</span>(yc_most_recent_labels), <span class="dv">1</span>), </span>
<span id="cb189-6"><a href="getting-started.html#cb189-6" tabindex="-1"></a>     <span class="at">labels =</span> yc_most_recent_labels)</span></code></pre></div>
<p>In the code snippet above, <code>plot()</code> is the R function used to create the yield curve plot. Here are the key inputs and arguments used in the function:</p>
<ul>
<li><code>x = yc_most_recent_data</code> represents the interest rates of the most recent yield curve data, which will be plotted on the x-axis.</li>
<li><code>xaxt = 'n'</code> specifies that no x-axis tick labels should be displayed initially. This is useful because we will customize the x-axis tick labels separately using the <code>axis()</code> function.</li>
<li><code>type = "o"</code> specifies that the plot should be created as a line plot with points. This will display the yield curve as a connected line with markers at each data point.</li>
<li><code>pch = 19</code> sets the plot symbol to a solid circle, which will be used as markers for the data points on the yield curve.</li>
<li><code>xlab = "Time to Maturity"</code> sets the label for the x-axis to “Time to Maturity”, indicating the variable represented on the x-axis.</li>
<li><code>ylab = "Treasury Rate in %"</code> sets the label for the y-axis to “Treasury Rate in %”, indicating the variable represented on the y-axis.</li>
<li><code>main = paste("Yield Curve on", format(last(yc$Date), format = '%B %d, %Y'))</code> sets the title of the plot to “Yield Curve on” followed by the date of the most recent yield curve data.</li>
</ul>
<p>Additionally, the <code>axis()</code> function is used to customize the x-axis tick labels. It sets the tick locations using <code>at = seq(1, length(yc_most_recent_labels), 1)</code> to evenly space the ticks along the x-axis. The <code>labels = yc_most_recent_labels</code> argument assigns the column names of the last row (representing maturities) as the tick labels on the x-axis.</p>
<div class="figure"><span style="display:block;" id="fig:yield-curve-plot"></span>
<img src="_main_files/figure-html/yield-curve-plot-1.png" alt="Yield Curve on June 30, 2023" width="672" />
<p class="caption">
Figure 3.5: Yield Curve on June 30, 2023
</p>
</div>
<p>The resulting plot, shown in Figure <a href="getting-started.html#fig:yield-curve-plot">3.5</a>, depicts the yield curve based on the most recent available data, allowing us to visualize the relationship between interest rates and the time to maturity. The x-axis represents the different maturities of the bonds, while the y-axis represents the corresponding treasury rates.</p>
<p>Analyzing the shape of the yield curve can provide insights into market expectations and can be useful for assessing economic conditions and making investment decisions. The yield curve can take different shapes, such as upward-sloping (normal), downward-sloping (inverted), or flat, each indicating different market conditions and expectations for future interest rates.</p>
<p>An upward-sloping yield curve, where longer-term interest rates are higher than shorter-term rates, is often seen during periods of economic expansion. This shape suggests that investors expect higher interest rates in the future as the economy grows and inflationary pressures increase. It reflects an optimistic outlook for economic conditions, as borrowing and lending activity are expected to be robust.</p>
<p>In contrast, a downward-sloping or inverted yield curve, where shorter-term interest rates are higher than longer-term rates, is often considered a predictor of economic slowdown or recession. This shape suggests that investors anticipate lower interest rates in the future as economic growth slows and inflationary pressures decrease. It reflects a more cautious outlook for the economy, as investors seek the safety of longer-term bonds amid expectations of lower returns and potential economic downturn.</p>
<p>Inflation expectations also influence the shape of the yield curve. When there are high inflation expectations for the long term, the yield curve tends to slope upwards. This occurs because lenders demand higher interest rates for longer maturities to compensate for anticipated inflation. However, when there is currently high inflation but expectations are that the central bank will successfully control inflation in the long term, the yield curve may slope downwards. In this case, long-term interest rates are lower than short-term rates, as average inflation over the long term is expected to be lower than in the short term.</p>
</div>
</div>
<div id="tsv-tab-separated-values" class="section level3 hasAnchor" number="3.3.3">
<h3><span class="header-section-number">3.3.3</span> TSV (Tab Separated Values)<a href="getting-started.html#tsv-tab-separated-values" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>TSV (Tab Separated Values) is a common file format used to store tabular data. As the name suggests, the values in each row of a TSV file are separated by tabs. Here’s an example of how data is stored in a TSV file:</p>
<ul>
<li>Male    8    100    3</li>
<li>Female    9    20    3</li>
</ul>
<p>In this section, we’ll demonstrate how to import a TSV file using real-world consumer survey data collected by the University of Michigan.</p>
<div id="import-michigan-consumer-survey-data-in-tsv-format" class="section level4 unnumbered hasAnchor">
<h4>Import Michigan Consumer Survey Data in TSV Format<a href="getting-started.html#import-michigan-consumer-survey-data-in-tsv-format" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>To obtain the Michigan consumer survey data, follow these steps:</p>
<ol style="list-style-type: decimal">
<li>Visit the website of University of Michigan’s surveys of consumers by clicking <a href="https://data.sca.isr.umich.edu/">here</a>.</li>
<li>Click on “DATA” in the menu bar, then select “Time Series.”</li>
<li>On the data page, under Table, select “All: All Tables (Tab-delimited or CSV only)” to obtain the consumer survey data on all topics.</li>
<li>To access all the consumer survey data since 1978, type “1978” under the “Oldest Year” option.</li>
<li>Click on “Tab-Deliminated (Excel)” under the “format” option.</li>
<li>Save the TSV file in a location of your choice, ensuring that it is saved in a familiar folder for easy access.</li>
</ol>
<p>The dataset contains 360 variables with coded column names such as <code>ics_inc31</code> or <code>pago_dk_all</code>. To understand the meaning of these columns, you can visit the same website <a href="https://data.sca.isr.umich.edu/">here</a> and click on <a href="https://data.sca.isr.umich.edu/survey-info.php#">SURVEY INFORMATION</a>. From there, select the <a href="https://data.sca.isr.umich.edu/fetchdoc.php?docid=45121">Time-Series Variable Codebook</a> which is a PDF document that provides detailed explanations for all the column names. By referring to this codebook, you can gain a better understanding of the variables and their corresponding meanings in the dataset.</p>
<p>Next, to import the consumer survey data, you need to install and load the <code>readr</code> package if you haven’t done so already. Once the package is loaded, you can use either the <code>read_tsv()</code> or <code>read_delim()</code> function to read the TSV (Tab-Separated Values) file.</p>
<div class="sourceCode" id="cb190"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb190-1"><a href="getting-started.html#cb190-1" tabindex="-1"></a><span class="co"># Load the package</span></span>
<span id="cb190-2"><a href="getting-started.html#cb190-2" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;readr&quot;</span>)</span>
<span id="cb190-3"><a href="getting-started.html#cb190-3" tabindex="-1"></a></span>
<span id="cb190-4"><a href="getting-started.html#cb190-4" tabindex="-1"></a><span class="co"># Import TSV file</span></span>
<span id="cb190-5"><a href="getting-started.html#cb190-5" tabindex="-1"></a>cs <span class="ot">&lt;-</span> <span class="fu">read_tsv</span>(<span class="at">file =</span> <span class="st">&quot;files/sca-tableall-on-2023-Jul-01.tsv&quot;</span>, <span class="at">skip =</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## New names:
## Rows: 545 Columns: 360
## ── Column specification
## ──────────────────────────────────────────────────────── Delimiter: &quot;\t&quot; dbl
## (359): Month, yyyy, ics_all, ics_inc31, ics_inc32, ics_inc33, ics_a1834,... lgl
## (1): ...360
## ℹ Use `spec()` to retrieve the full column specification for this data. ℹ
## Specify the column types or set `show_col_types = FALSE` to quiet this message.
## • `` -&gt; `...360`</code></pre>
<div class="sourceCode" id="cb192"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb192-1"><a href="getting-started.html#cb192-1" tabindex="-1"></a><span class="co"># Import TSV file using the read_delim() function</span></span>
<span id="cb192-2"><a href="getting-started.html#cb192-2" tabindex="-1"></a>cs <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(<span class="at">file =</span> <span class="st">&quot;files/sca-tableall-on-2023-Jul-01.tsv&quot;</span>, <span class="at">skip =</span> <span class="dv">1</span>, <span class="at">col_names =</span> <span class="cn">TRUE</span>, <span class="at">delim =</span> <span class="st">&quot;</span><span class="sc">\t</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## New names:
## Rows: 545 Columns: 360
## ── Column specification
## ──────────────────────────────────────────────────────── Delimiter: &quot;\t&quot; dbl
## (359): Month, yyyy, ics_all, ics_inc31, ics_inc32, ics_inc33, ics_a1834,... lgl
## (1): ...360
## ℹ Use `spec()` to retrieve the full column specification for this data. ℹ
## Specify the column types or set `show_col_types = FALSE` to quiet this message.
## • `` -&gt; `...360`</code></pre>
<p>In the provided code snippets, the <code>file</code> input specifies the file path or URL of the TSV file to be imported. The <code>skip</code> input is used to specify the number of rows to skip at the beginning of the file. In this case, <code>skip = 1</code> indicates that the first line of the TSV file, which contains the title “All Tables”, should be skipped. The <code>col_names</code> input is set to <code>TRUE</code> to indicate that the second line of the TSV file (after skipping 1 row) contains the column names. Lastly, the <code>delim</code> input is set to <code>"\t"</code> to specify that the columns in the TSV file are separated by tabs, which is the standard delimiter for TSV (<em>Tab</em> Separated Values) files.</p>
<p>Note that if the file is neither CSV nor TSV, but rather has an exotic format where columns are separated by a different character that is neither a comma nor a tab, such as “/”, you can use the <code>read_delim()</code> function with the <code>delim = "/"</code> argument to specify the custom delimiter.</p>
<p>To inspect the first few rows of the data, print the <code>cs</code> object in the console. For an overview of the entire dataset, execute <code>View(cs)</code>.</p>
<div class="sourceCode" id="cb194"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb194-1"><a href="getting-started.html#cb194-1" tabindex="-1"></a><span class="co"># Display the data</span></span>
<span id="cb194-2"><a href="getting-started.html#cb194-2" tabindex="-1"></a>cs</span></code></pre></div>
<pre><code>## # A tibble: 545 × 360
##    Month  yyyy ics_all ics_inc31 ics_inc32 ics_inc33 ics_a1834 ics_a3554
##    &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
##  1     1  1978    83.7        NA        NA        NA      93.7      86.7
##  2     2  1978    84.3        NA        NA        NA      99.7      82.3
##  3     3  1978    78.8        NA        NA        NA      91.7      76.8
##  4     4  1978    81.6        NA        NA        NA      91.8      79.7
##  5     5  1978    82.9        NA        NA        NA      95.1      78.9
##  6     6  1978    80          NA        NA        NA      91.7      75.7
##  7     7  1978    82.4        NA        NA        NA      92.2      78.4
##  8     8  1978    78.4        NA        NA        NA      87.8      77.2
##  9     9  1978    80.4        NA        NA        NA      86.6      83.9
## 10    10  1978    79.3        NA        NA        NA      90.6      76.7
## # ℹ 535 more rows
## # ℹ 352 more variables: ics_a5597 &lt;dbl&gt;, ics_ne &lt;dbl&gt;, ics_nc &lt;dbl&gt;,
## #   ics_s &lt;dbl&gt;, ics_w &lt;dbl&gt;, icc_all &lt;dbl&gt;, ice_all &lt;dbl&gt;, pago_f_all &lt;dbl&gt;,
## #   pago_s_all &lt;dbl&gt;, pago_u_all &lt;dbl&gt;, pago_dk_all &lt;dbl&gt;, pago_r_all &lt;dbl&gt;,
## #   pagorn_hy_all &lt;dbl&gt;, pagorn_ha_all &lt;dbl&gt;, pagorn_ld_all &lt;dbl&gt;,
## #   pagorn_ly_all &lt;dbl&gt;, pagorn_hp_all &lt;dbl&gt;, pagorn_la_all &lt;dbl&gt;,
## #   pagorn_hd_all &lt;dbl&gt;, pagorn_ny_all &lt;dbl&gt;, pagorn_nad_all &lt;dbl&gt;, …</code></pre>
<p>Use <code>sapply(cs, class)</code> to check the data type of each column, to make sure all columns are indeed numeric:</p>
<div class="sourceCode" id="cb196"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb196-1"><a href="getting-started.html#cb196-1" tabindex="-1"></a><span class="co"># Check the data type of each column</span></span>
<span id="cb196-2"><a href="getting-started.html#cb196-2" tabindex="-1"></a><span class="fu">table</span>(<span class="fu">sapply</span>(cs, class))</span></code></pre></div>
<pre><code>## 
## logical numeric 
##       1     359</code></pre>
<p>Here, since there are 360 columns, the <code>summary()</code> function is applied, which reveals that there are 359 numerical columns, and 1 logical column, which makes sense.</p>
<p>Instead of a date column, the consumer survey has a year (<code>yyyy</code>) and a month (<code>Month</code>) column. To create a date column from the year and month columns, combine them with the <code>paste()</code> function to create a date format of the form Year-Month-Day or <code>%Y-%m-%d</code>:</p>
<div class="sourceCode" id="cb198"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb198-1"><a href="getting-started.html#cb198-1" tabindex="-1"></a><span class="co"># Create date column</span></span>
<span id="cb198-2"><a href="getting-started.html#cb198-2" tabindex="-1"></a>cs<span class="sc">$</span>Date <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(<span class="fu">paste</span>(cs<span class="sc">$</span>yyyy, cs<span class="sc">$</span>Month, <span class="st">&quot;01&quot;</span>, <span class="at">sep =</span> <span class="st">&quot;-&quot;</span>))</span>
<span id="cb198-3"><a href="getting-started.html#cb198-3" tabindex="-1"></a><span class="fu">head</span>(cs<span class="sc">$</span>Date)</span></code></pre></div>
<pre><code>## [1] &quot;1978-01-01&quot; &quot;1978-02-01&quot; &quot;1978-03-01&quot; &quot;1978-04-01&quot; &quot;1978-05-01&quot;
## [6] &quot;1978-06-01&quot;</code></pre>
</div>
<div id="plot-consumer-indices" class="section level4 unnumbered hasAnchor">
<h4>Plot Consumer Indices<a href="getting-started.html#plot-consumer-indices" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The Michigan Consumer Survey consists of a wide range of survey responses from a sample of households collected every month. These survey responses are gathered to produce indices about how consumers feel each period. The University of Michigan produces three main indices: the Index of Consumer Confidence (ICC), the Index of Current Economic Conditions (ICE), and the Index of Consumer Sentiment (ICS). These indices are designed to measure different aspects of consumer attitudes and perceptions regarding the economy.</p>
<ol style="list-style-type: decimal">
<li><p><strong>Index of Consumer Confidence (ICC)</strong>: The ICC reflects consumers’ expectations about future economic conditions and their overall optimism or pessimism. It is based on consumers’ assessments of their future financial prospects, job availability, and economic outlook. A higher ICC value indicates greater consumer confidence and positive expectations for the economy.</p></li>
<li><p><strong>Index of Current Economic Conditions (ICE)</strong>: The ICE assesses consumers’ perceptions of the current economic environment. It reflects their evaluations of their personal financial situation, job security, and their perception of whether it is a good time to make major purchases. The ICE provides insights into the current economic conditions as perceived by consumers.</p></li>
<li><p><strong>Index of Consumer Sentiment (ICS)</strong>: The ICS combines both the ICC and ICE to provide an overall measure of consumer sentiment. It takes into account consumers’ expectations for the future as well as their assessment of the present economic conditions. The ICS is often used as an indicator of consumer behavior and their likelihood of making purchases and engaging in economic activities.</p></li>
</ol>
<p>These indices are calculated based on survey responses from a sample of households, and they serve as important indicators of consumer sentiment and economic trends. They are widely followed by economists, policymakers, and financial markets as they provide valuable insights into consumers’ attitudes and perceptions, which can impact their spending behavior and overall economic activity.</p>
<p>Let’s use the <code>plot()</code> function to visualize the imported Michigan consumer survey data. In this case, we will plot the three key indices: ICC, ICE, and ICS over time, using the Date column as the x-axis and the three indices as the y-axis:</p>
<div class="sourceCode" id="cb200"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb200-1"><a href="getting-started.html#cb200-1" tabindex="-1"></a><span class="co"># Plot ICC, ICE, and ICS over time</span></span>
<span id="cb200-2"><a href="getting-started.html#cb200-2" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x =</span> cs<span class="sc">$</span>Date, <span class="at">y =</span> cs<span class="sc">$</span>icc_all, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">col =</span> <span class="dv">5</span>, <span class="at">lwd =</span> <span class="dv">3</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">40</span>, <span class="dv">140</span>),</span>
<span id="cb200-3"><a href="getting-started.html#cb200-3" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Date&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Index&quot;</span>, <span class="at">main =</span> <span class="st">&quot;Key Indices of the Michigan Consumer Survey&quot;</span>)</span>
<span id="cb200-4"><a href="getting-started.html#cb200-4" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x =</span> cs<span class="sc">$</span>Date, <span class="at">y =</span> cs<span class="sc">$</span>ice_all, <span class="at">col =</span> <span class="dv">2</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb200-5"><a href="getting-started.html#cb200-5" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x =</span> cs<span class="sc">$</span>Date, <span class="at">y =</span> cs<span class="sc">$</span>ics_all, <span class="at">col =</span> <span class="dv">1</span>, <span class="at">lwd =</span> <span class="fl">1.5</span>)</span>
<span id="cb200-6"><a href="getting-started.html#cb200-6" tabindex="-1"></a><span class="fu">legend</span>(<span class="at">x =</span> <span class="st">&quot;topleft&quot;</span>, <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">&quot;ICC&quot;</span>, <span class="st">&quot;ICE&quot;</span>, <span class="st">&quot;ICS&quot;</span>), </span>
<span id="cb200-7"><a href="getting-started.html#cb200-7" tabindex="-1"></a>       <span class="at">col =</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">2</span>, <span class="dv">1</span>), <span class="at">lwd =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">2</span>, <span class="fl">1.5</span>), <span class="at">horiz =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p>In the code snippet provided, the appearance and behavior of the plot are customized using several functions and arguments:</p>
<ul>
<li><code>x</code>: This argument specifies the data to be used for the x-axis of the plot. In this case, it is <code>cs$Date</code>, indicating the “Date” column of the Michigan consumer survey data.</li>
<li><code>y</code>: This argument specifies the data to be used for the y-axis of the plot. In this case, it is <code>cs$icc_all</code>, <code>cs$ice_all</code>, and <code>cs$ics_all</code>, representing the ICC, ICE, and ICS indices from the Michigan consumer survey data.</li>
<li><code>type</code>: This argument determines the type of plot to be created. In this case, it is set to <code>"l"</code>, which stands for “line plot”. This will create a line plot of the data points.</li>
<li><code>col</code>: This argument specifies the color of the lines in the plot. In the code snippet, different colors are used for each index: <code>5</code> for ICC, <code>2</code> for ICE, and <code>1</code> for ICS.</li>
<li><code>lwd</code>: This argument controls the line width of the plot. It is set to <code>3</code> for ICC, <code>2</code> for ICE, and <code>1.5</code> for ICS, indicating different line widths for each index.</li>
<li><code>ylim</code>: This argument sets the limits of the y-axis. In this case, it is set to <code>c(40, 140)</code>, which defines the range of the y-axis from 40 to 140.</li>
<li><code>xlab</code>: This argument specifies the label for the x-axis of the plot. In the code snippet, it is set to <code>"Date"</code>.</li>
<li><code>ylab</code>: This argument specifies the label for the y-axis of the plot. In the code snippet, it is set to <code>"Index"</code>.</li>
<li><code>main</code>: This argument specifies the main title of the plot. In the code snippet, it is set to <code>"Key Indices of the Michigan Consumer Survey"</code>.</li>
<li><code>lines</code>: This function is used to add additional lines to the plot.</li>
<li><code>legend</code>: This function adds a legend to the plot. It is used to create a legend in the top-left corner (<code>x = "topleft"</code>) with labels corresponding to each index (<code>"ICC"</code>, <code>"ICE"</code>, <code>"ICS"</code>) and their respective line colors and widths.</li>
</ul>
<div class="figure"><span style="display:block;" id="fig:icc-ice-ics-plot"></span>
<img src="_main_files/figure-html/icc-ice-ics-plot-1.png" alt="Key Indices of the Michigan Consumer Survey" width="672" />
<p class="caption">
Figure 3.6: Key Indices of the Michigan Consumer Survey
</p>
</div>
<p>The resulting plot, shown in Figure <a href="getting-started.html#fig:icc-ice-ics-plot">3.6</a>, displays the historical evolution of the three Michigan consumer survey indices: ICC, ICE, and ICS. These indices are considered leading indicators because they provide early signals about changes in consumer sentiment and economic conditions. They often reflect consumers’ expectations and attitudes before these changes are fully manifested in traditional economic indicators, such as unemployment rates or GDP growth.</p>
<p>Consumer sentiment plays a crucial role in shaping consumer behavior, including spending patterns, saving habits, and investment decisions. When consumer confidence is high, individuals are more likely to spend and invest, stimulating economic growth. Conversely, low consumer confidence can lead to reduced spending and investment, potentially dampening economic activity. Hence, these indices can serve as an early warning system for potential shifts in economic activity.</p>
<p>By incorporating the consumer survey indices alongside traditional economic indicators, policymakers and analysts can gain a more comprehensive understanding of the economic landscape. While traditional indicators like unemployment rates provide objective measures of economic conditions, the consumer survey indices offer a subjective perspective, reflecting consumers’ beliefs, expectations, and intentions. This subjective insight can provide additional context and help anticipate changes in consumer behavior and overall economic activity.</p>
<p>Therefore, by monitoring both traditional economic indicators and the Michigan consumer survey indices, policymakers and analysts can obtain a more holistic view of the economy, enabling them to make more informed decisions and implement timely interventions to support economic stability and growth.</p>
</div>
</div>
<div id="excel-file" class="section level3 hasAnchor" number="3.3.4">
<h3><span class="header-section-number">3.3.4</span> Excel File<a href="getting-started.html#excel-file" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>CSV (Comma Separated Values) is a common file format used to store tabular data. As the name suggests, the values in each row of a CSV file are separated by commas. Here’s an example of how data is stored in a CSV file:</p>
<ul>
<li>Male,8,100,3</li>
<li>Female,9,20,3</li>
</ul>
<p>In this section, we’ll demonstrate how to import a CSV file using real-world Treasury yield curve rates data.</p>
<div id="import-yield-curve-data-in-csv-format-1" class="section level4 unnumbered hasAnchor">
<h4>Import Yield Curve Data in CSV Format<a href="getting-started.html#import-yield-curve-data-in-csv-format-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>To obtain the yield curve data, follow these steps:</p>
<ol style="list-style-type: decimal">
<li>Visit the U.S. Treasury’s data center by clicking <a href="https://www.treasury.gov/resource-center/data-chart-center">here</a>.</li>
<li>Click on “Data” in the menu bar, then select “Daily Treasury Par Yield Curve Rates.”</li>
<li>On the data page, select “Download CSV” to obtain the yield curve data for the current year.</li>
<li>To access all the yield curve data since 1990, choose “All” under the “Select Time Period” option, and click “Apply.” Please note that when selecting all periods, the “Download CSV” button may not be available.</li>
<li>To manually save the data as a CSV file, you can copy the data by selecting it and using the Ctrl+C (or Cmd+C) command. Open an Excel file, and use the Ctrl+V (or Cmd+V) command to paste the data into the Excel file.</li>
<li>Save the Excel file as a CSV file named ‘yieldcurve.csv’ in a location of your choice, ensuring that it is saved in a familiar folder for easy access.</li>
</ol>
<p>Next, install and load the <code>readr</code> package. Run <code>install.packages("readr")</code> in the console and include the package at the top of your R script. You can then use the <code>read_csv()</code> or <code>read_delim()</code> function to import the yield curve data:</p>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb201-1"><a href="getting-started.html#cb201-1" tabindex="-1"></a><span class="co"># Load the package</span></span>
<span id="cb201-2"><a href="getting-started.html#cb201-2" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;readr&quot;</span>)</span>
<span id="cb201-3"><a href="getting-started.html#cb201-3" tabindex="-1"></a></span>
<span id="cb201-4"><a href="getting-started.html#cb201-4" tabindex="-1"></a><span class="co"># Import CSV file</span></span>
<span id="cb201-5"><a href="getting-started.html#cb201-5" tabindex="-1"></a>yc <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="at">file =</span> <span class="st">&quot;files/yieldcurve.csv&quot;</span>, <span class="at">col_names =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## Warning: One or more parsing issues, call `problems()` on your data frame for details,
## e.g.:
##   dat &lt;- vroom(...)
##   problems(dat)</code></pre>
<pre><code>## Rows: 8382 Columns: 14
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr (6): Date, 1 Mo, 2 Mo, 4 Mo, 20 Yr, 30 Yr
## dbl (8): 3 Mo, 6 Mo, 1 Yr, 2 Yr, 3 Yr, 5 Yr, 7 Yr, 10 Yr
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<div class="sourceCode" id="cb204"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb204-1"><a href="getting-started.html#cb204-1" tabindex="-1"></a><span class="co"># Import CSV file using the read_delim() function</span></span>
<span id="cb204-2"><a href="getting-started.html#cb204-2" tabindex="-1"></a>yc <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(<span class="at">file =</span> <span class="st">&quot;files/yieldcurve.csv&quot;</span>, <span class="at">col_names =</span> <span class="cn">TRUE</span>, <span class="at">delim =</span> <span class="st">&quot;,&quot;</span>)</span></code></pre></div>
<pre><code>## Warning: One or more parsing issues, call `problems()` on your data frame for details,
## e.g.:
##   dat &lt;- vroom(...)
##   problems(dat)</code></pre>
<pre><code>## Rows: 8382 Columns: 14
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr (6): Date, 1 Mo, 2 Mo, 4 Mo, 20 Yr, 30 Yr
## dbl (8): 3 Mo, 6 Mo, 1 Yr, 2 Yr, 3 Yr, 5 Yr, 7 Yr, 10 Yr
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<p>In the code snippets above, the <code>read_csv()</code> and <code>read_delim()</code> functions from the <code>readr</code> package are used to import a CSV file named “yieldcurve.csv”. The <code>col_names = TRUE</code> argument indicates that the first row of the CSV file contains column names. The <code>delim = ","</code> argument specifies that the columns are separated by commas, which is the standard delimiter for CSV (<em>Comma</em> Separated Values) files. Either one of the two functions can be used to read the CSV file and store the data in the variable <code>yc</code> for further analysis.</p>
<p>To import Excel files, we use the <code>readxl</code> package. To import an Excel file, execute <code>install.packages("readxl")</code> in the console, and then load the package at the start of your R script.</p>
<div class="sourceCode" id="cb207"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb207-1"><a href="getting-started.html#cb207-1" tabindex="-1"></a><span class="co"># Load the package</span></span>
<span id="cb207-2"><a href="getting-started.html#cb207-2" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;readxl&quot;</span>)</span>
<span id="cb207-3"><a href="getting-started.html#cb207-3" tabindex="-1"></a></span>
<span id="cb207-4"><a href="getting-started.html#cb207-4" tabindex="-1"></a><span class="co"># Print names of all worksheets</span></span>
<span id="cb207-5"><a href="getting-started.html#cb207-5" tabindex="-1"></a><span class="co"># Replace &#39;path&#39; with your Excel file path</span></span>
<span id="cb207-6"><a href="getting-started.html#cb207-6" tabindex="-1"></a><span class="co"># excel_sheets(path=&quot;car.xlsx&quot;)</span></span>
<span id="cb207-7"><a href="getting-started.html#cb207-7" tabindex="-1"></a></span>
<span id="cb207-8"><a href="getting-started.html#cb207-8" tabindex="-1"></a><span class="co"># Import the sheet you want</span></span>
<span id="cb207-9"><a href="getting-started.html#cb207-9" tabindex="-1"></a><span class="co"># Replace &#39;path&#39; and &#39;sheet&#39; with your Excel file path and sheet name</span></span>
<span id="cb207-10"><a href="getting-started.html#cb207-10" tabindex="-1"></a><span class="co"># car &lt;- read_excel(path=&quot;car.xlsx&quot;,sheet=&quot;Statistics_A&quot;,col_names=TRUE)</span></span>
<span id="cb207-11"><a href="getting-started.html#cb207-11" tabindex="-1"></a></span>
<span id="cb207-12"><a href="getting-started.html#cb207-12" tabindex="-1"></a><span class="co"># Import all sheets</span></span>
<span id="cb207-13"><a href="getting-started.html#cb207-13" tabindex="-1"></a><span class="co"># Replace &#39;path&#39; with your Excel file path</span></span>
<span id="cb207-14"><a href="getting-started.html#cb207-14" tabindex="-1"></a><span class="co"># car_list &lt;- lapply(excel_sheets(path=&quot;car.xlsx&quot;),read_excel, path=&quot;car.xlsx&quot;,col_names=TRUE)</span></span></code></pre></div>
</div>
</div>
<div id="saving-data" class="section level3 hasAnchor" number="3.3.5">
<h3><span class="header-section-number">3.3.5</span> Saving Data<a href="getting-started.html#saving-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Once the data has been imported and possibly manipulated, it can be saved in various formats.</p>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb208-1"><a href="getting-started.html#cb208-1" tabindex="-1"></a><span class="co"># Save data in different formats</span></span>
<span id="cb208-2"><a href="getting-started.html#cb208-2" tabindex="-1"></a><span class="fu">save</span>(yc, <span class="at">file=</span><span class="st">&quot;yieldcurve.RData&quot;</span>)</span>
<span id="cb208-3"><a href="getting-started.html#cb208-3" tabindex="-1"></a><span class="fu">write_csv</span>(<span class="at">x=</span>yc, <span class="at">path=</span><span class="st">&quot;yieldcurve.csv&quot;</span>, <span class="at">na=</span><span class="st">&quot;NA&quot;</span>)</span></code></pre></div>
<pre><code>## Warning: The `path` argument of `write_csv()` is deprecated as of readr 1.4.0.
## ℹ Please use the `file` argument instead.
## This warning is displayed once every 8 hours.
## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
## generated.</code></pre>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb210-1"><a href="getting-started.html#cb210-1" tabindex="-1"></a><span class="co"># Other formats can be used by replacing &#39;yieldcurve&#39; with your data and &#39;path&#39; with your desired file name and format</span></span></code></pre></div>
<p>For more information on importing data in R, consider taking DataCamp’s <a href="https://learn.datacamp.com/courses/introduction-to-importing-data-in-r">Introduction to Importing Data in R</a> course.</p>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="software-installation.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="datacamp.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/index.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
